/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { HubConnection, IStreamResult, Subject } from '@microsoft/signalr';
import type { IChatHub, IGameClient } from './TRPG.GameSessions.Hubs';
import type { SceneSnapshot } from '../TRPG.GameSessions.Responses';
import type { CombatantState, CombatUpdatePayload } from '../TRPG.Combat.ClientModels';
import type { HostileEncounterState, EncounterResolutionFact } from '../TRPG.Encounters.Responses';
import type { SkillLevelUp, CharacterLevelUp } from '../TRPG.Creatures.ClientModels';
import type { QuestDialogRequested, QuestObjectiveCompleted } from '../TRPG.Quests.ClientModels';


// components

export type Disposable = {
    dispose(): void;
}

export type HubProxyFactory<T> = {
    createHubProxy(connection: HubConnection): T;
}

export type ReceiverRegister<T> = {
    register(connection: HubConnection, receiver: T): Disposable;
}

type ReceiverMethod = {
    methodName: string,
    method: (...args: any[]) => void
}

class ReceiverMethodSubscription implements Disposable {

    public constructor(
        private connection: HubConnection,
        private receiverMethod: ReceiverMethod[]) {
    }

    public readonly dispose = () => {
        for (const it of this.receiverMethod) {
            this.connection.off(it.methodName, it.method);
        }
    }
}

// API

export type HubProxyFactoryProvider = {
    (hubType: "IChatHub"): HubProxyFactory<IChatHub>;
}

export const getHubProxyFactory = ((hubType: string) => {
    if(hubType === "IChatHub") {
        return IChatHub_HubProxyFactory.Instance;
    }
}) as HubProxyFactoryProvider;

export type ReceiverRegisterProvider = {
    (receiverType: "IGameClient"): ReceiverRegister<IGameClient>;
}

export const getReceiverRegister = ((receiverType: string) => {
    if(receiverType === "IGameClient") {
        return IGameClient_Binder.Instance;
    }
}) as ReceiverRegisterProvider;

// HubProxy

class IChatHub_HubProxyFactory implements HubProxyFactory<IChatHub> {
    public static Instance = new IChatHub_HubProxyFactory();

    private constructor() {
    }

    public readonly createHubProxy = (connection: HubConnection): IChatHub => {
        return new IChatHub_HubProxy(connection);
    }
}

class IChatHub_HubProxy implements IChatHub {

    public constructor(private connection: HubConnection) {
    }

    public readonly endSession = async (): Promise<void> => {
        return await this.connection.invoke("EndSession");
    }

    public readonly receiveOpening = (): IStreamResult<string> => {
        return this.connection.stream("ReceiveOpening");
    }

    public readonly sendChat = (message: string): IStreamResult<string> => {
        return this.connection.stream("SendChat", message);
    }

    public readonly sendWait = (hours: number): IStreamResult<string> => {
        return this.connection.stream("SendWait", hours);
    }

    public readonly sendFlee = (): IStreamResult<string> => {
        return this.connection.stream("SendFlee");
    }

    public readonly resolveUseAbilityCombatAction = async (targetId: string, abilityName: string): Promise<void> => {
        return await this.connection.invoke("ResolveUseAbilityCombatAction", targetId, abilityName);
    }

    public readonly resolveUseItemCombatAction = async (itemName: string): Promise<void> => {
        return await this.connection.invoke("ResolveUseItemCombatAction", itemName);
    }

    public readonly resolveAttackEncounterAction = (): IStreamResult<string> => {
        return this.connection.stream("ResolveAttackEncounterAction");
    }

    public readonly resolveEvadeEncounterAction = (): IStreamResult<string> => {
        return this.connection.stream("ResolveEvadeEncounterAction");
    }

    public readonly resolveRetreatEncounterAction = (): IStreamResult<string> => {
        return this.connection.stream("ResolveRetreatEncounterAction");
    }
}


// Receiver

class IGameClient_Binder implements ReceiverRegister<IGameClient> {

    public static Instance = new IGameClient_Binder();

    private constructor() {
    }

    public readonly register = (connection: HubConnection, receiver: IGameClient): Disposable => {

        const __sceneSnapshot = (...args: [SceneSnapshot]) => receiver.sceneSnapshot(...args);
        const __combatStarted = (...args: [CombatantState[]]) => receiver.combatStarted(...args);
        const __combatUpdated = (...args: [CombatUpdatePayload]) => receiver.combatUpdated(...args);
        const __encounterStarted = (...args: [HostileEncounterState]) => receiver.encounterStarted(...args);
        const __encounterResolved = (...args: [EncounterResolutionFact]) => receiver.encounterResolved(...args);
        const __skillLevelUp = (...args: [SkillLevelUp]) => receiver.skillLevelUp(...args);
        const __characterLevelUp = (...args: [CharacterLevelUp]) => receiver.characterLevelUp(...args);
        const __questDialogRequested = (...args: [QuestDialogRequested]) => receiver.questDialogRequested(...args);
        const __questObjectiveCompleted = (...args: [QuestObjectiveCompleted]) => receiver.questObjectiveCompleted(...args);
        const __questJournalUpdated = () => receiver.questJournalUpdated();

        connection.on("SceneSnapshot", __sceneSnapshot);
        connection.on("CombatStarted", __combatStarted);
        connection.on("CombatUpdated", __combatUpdated);
        connection.on("EncounterStarted", __encounterStarted);
        connection.on("EncounterResolved", __encounterResolved);
        connection.on("SkillLevelUp", __skillLevelUp);
        connection.on("CharacterLevelUp", __characterLevelUp);
        connection.on("QuestDialogRequested", __questDialogRequested);
        connection.on("QuestObjectiveCompleted", __questObjectiveCompleted);
        connection.on("QuestJournalUpdated", __questJournalUpdated);

        const methodList: ReceiverMethod[] = [
            { methodName: "SceneSnapshot", method: __sceneSnapshot },
            { methodName: "CombatStarted", method: __combatStarted },
            { methodName: "CombatUpdated", method: __combatUpdated },
            { methodName: "EncounterStarted", method: __encounterStarted },
            { methodName: "EncounterResolved", method: __encounterResolved },
            { methodName: "SkillLevelUp", method: __skillLevelUp },
            { methodName: "CharacterLevelUp", method: __characterLevelUp },
            { methodName: "QuestDialogRequested", method: __questDialogRequested },
            { methodName: "QuestObjectiveCompleted", method: __questObjectiveCompleted },
            { methodName: "QuestJournalUpdated", method: __questJournalUpdated }
        ]

        return new ReceiverMethodSubscription(connection, methodList);
    }
}

