/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { HubConnection, IStreamResult, Subject } from '@microsoft/signalr';
import type { IChatHub, IGameClient } from './TRPG.GameSessions.Hubs';
import type { SceneSnapshot, CrimeNotification } from '../TRPG.GameSessions.Responses';
import type { CombatStartedPayload, CombatUpdatePayload } from '../TRPG.Combat.Responses';
import type { HostileEncounterState, HostileEncounterResolutionFact, GuardEncounterState, GuardEncounterResolutionFact, TheftEncounterState, TheftEncounterResolutionFact } from '../TRPG.Encounters.Responses';
import type { SkillLevelUp, CharacterLevelUp } from '../TRPG.Creatures.Responses';
import type { QuestDialogRequested, QuestObjectiveCompleted, QuestJournalUpdated } from '../TRPG.Quests.Responses';


// components

export type Disposable = {
    dispose(): void;
}

export type HubProxyFactory<T> = {
    createHubProxy(connection: HubConnection): T;
}

export type ReceiverRegister<T> = {
    register(connection: HubConnection, receiver: T): Disposable;
}

type ReceiverMethod = {
    methodName: string,
    method: (...args: any[]) => void
}

class ReceiverMethodSubscription implements Disposable {

    public constructor(
        private connection: HubConnection,
        private receiverMethod: ReceiverMethod[]) {
    }

    public readonly dispose = () => {
        for (const it of this.receiverMethod) {
            this.connection.off(it.methodName, it.method);
        }
    }
}

// API

export type HubProxyFactoryProvider = {
    (hubType: "IChatHub"): HubProxyFactory<IChatHub>;
}

export const getHubProxyFactory = ((hubType: string) => {
    if(hubType === "IChatHub") {
        return IChatHub_HubProxyFactory.Instance;
    }
}) as HubProxyFactoryProvider;

export type ReceiverRegisterProvider = {
    (receiverType: "IGameClient"): ReceiverRegister<IGameClient>;
}

export const getReceiverRegister = ((receiverType: string) => {
    if(receiverType === "IGameClient") {
        return IGameClient_Binder.Instance;
    }
}) as ReceiverRegisterProvider;

// HubProxy

class IChatHub_HubProxyFactory implements HubProxyFactory<IChatHub> {
    public static Instance = new IChatHub_HubProxyFactory();

    private constructor() {
    }

    public readonly createHubProxy = (connection: HubConnection): IChatHub => {
        return new IChatHub_HubProxy(connection);
    }
}

class IChatHub_HubProxy implements IChatHub {

    public constructor(private connection: HubConnection) {
    }

    public readonly endSession = async (): Promise<void> => {
        return await this.connection.invoke("EndSession");
    }

    public readonly receiveOpening = (): IStreamResult<string> => {
        return this.connection.stream("ReceiveOpening");
    }

    public readonly sendChat = (message: string): IStreamResult<string> => {
        return this.connection.stream("SendChat", message);
    }

    public readonly sendWait = (hours: number, minutes: number): IStreamResult<string> => {
        return this.connection.stream("SendWait", hours, minutes);
    }

    public readonly sendFlee = (): IStreamResult<string> => {
        return this.connection.stream("SendFlee");
    }

    public readonly sendRespawn = (): IStreamResult<string> => {
        return this.connection.stream("SendRespawn");
    }

    public readonly resolveUseAbilityCombatAction = (targetId: string, abilityName: string): IStreamResult<string> => {
        return this.connection.stream("ResolveUseAbilityCombatAction", targetId, abilityName);
    }

    public readonly resolveUseItemCombatAction = (itemName: string): IStreamResult<string> => {
        return this.connection.stream("ResolveUseItemCombatAction", itemName);
    }

    public readonly resolveAttackEncounterAction = (): IStreamResult<string> => {
        return this.connection.stream("ResolveAttackEncounterAction");
    }

    public readonly resolveEvadeEncounterAction = (): IStreamResult<string> => {
        return this.connection.stream("ResolveEvadeEncounterAction");
    }

    public readonly resolveRetreatEncounterAction = (): IStreamResult<string> => {
        return this.connection.stream("ResolveRetreatEncounterAction");
    }

    public readonly resolvePayFineEncounterAction = (): IStreamResult<string> => {
        return this.connection.stream("ResolvePayFineEncounterAction");
    }

    public readonly resolveGoToJailEncounterAction = (): IStreamResult<string> => {
        return this.connection.stream("ResolveGoToJailEncounterAction");
    }

    public readonly resolveResistArrestEncounterAction = (): IStreamResult<string> => {
        return this.connection.stream("ResolveResistArrestEncounterAction");
    }

    public readonly startTheftEncounterNarration = (encounterId: string): IStreamResult<string> => {
        return this.connection.stream("StartTheftEncounterNarration", encounterId);
    }

    public readonly resolveApologizeTheftEncounterAction = (): IStreamResult<string> => {
        return this.connection.stream("ResolveApologizeTheftEncounterAction");
    }

    public readonly resolveFightTheftEncounterAction = (): IStreamResult<string> => {
        return this.connection.stream("ResolveFightTheftEncounterAction");
    }

    public readonly acknowledgeEvents = async (flushId: string): Promise<void> => {
        return await this.connection.invoke("AcknowledgeEvents", flushId);
    }
}


// Receiver

class IGameClient_Binder implements ReceiverRegister<IGameClient> {

    public static Instance = new IGameClient_Binder();

    private constructor() {
    }

    public readonly register = (connection: HubConnection, receiver: IGameClient): Disposable => {

        const __sceneSnapshot = (...args: [SceneSnapshot]) => receiver.sceneSnapshot(...args);
        const __combatStarted = (...args: [CombatStartedPayload]) => receiver.combatStarted(...args);
        const __combatUpdated = (...args: [CombatUpdatePayload]) => receiver.combatUpdated(...args);
        const __hostileEncounterStarted = (...args: [HostileEncounterState]) => receiver.hostileEncounterStarted(...args);
        const __hostileEncounterResolved = (...args: [HostileEncounterResolutionFact]) => receiver.hostileEncounterResolved(...args);
        const __guardEncounterStarted = (...args: [GuardEncounterState]) => receiver.guardEncounterStarted(...args);
        const __guardEncounterResolved = (...args: [GuardEncounterResolutionFact]) => receiver.guardEncounterResolved(...args);
        const __theftEncounterStarted = (...args: [TheftEncounterState]) => receiver.theftEncounterStarted(...args);
        const __theftEncounterResolved = (...args: [TheftEncounterResolutionFact]) => receiver.theftEncounterResolved(...args);
        const __skillLevelUp = (...args: [SkillLevelUp]) => receiver.skillLevelUp(...args);
        const __characterLevelUp = (...args: [CharacterLevelUp]) => receiver.characterLevelUp(...args);
        const __questDialogRequested = (...args: [QuestDialogRequested]) => receiver.questDialogRequested(...args);
        const __questObjectiveCompleted = (...args: [QuestObjectiveCompleted]) => receiver.questObjectiveCompleted(...args);
        const __questJournalUpdated = (...args: [QuestJournalUpdated]) => receiver.questJournalUpdated(...args);
        const __crimeWitnessed = (...args: [CrimeNotification]) => receiver.crimeWitnessed(...args);
        const __crimeWitnessesRemoved = (...args: [CrimeNotification]) => receiver.crimeWitnessesRemoved(...args);
        const __requestAck = (...args: [string]) => receiver.requestAck(...args);

        connection.on("SceneSnapshot", __sceneSnapshot);
        connection.on("CombatStarted", __combatStarted);
        connection.on("CombatUpdated", __combatUpdated);
        connection.on("HostileEncounterStarted", __hostileEncounterStarted);
        connection.on("HostileEncounterResolved", __hostileEncounterResolved);
        connection.on("GuardEncounterStarted", __guardEncounterStarted);
        connection.on("GuardEncounterResolved", __guardEncounterResolved);
        connection.on("TheftEncounterStarted", __theftEncounterStarted);
        connection.on("TheftEncounterResolved", __theftEncounterResolved);
        connection.on("SkillLevelUp", __skillLevelUp);
        connection.on("CharacterLevelUp", __characterLevelUp);
        connection.on("QuestDialogRequested", __questDialogRequested);
        connection.on("QuestObjectiveCompleted", __questObjectiveCompleted);
        connection.on("QuestJournalUpdated", __questJournalUpdated);
        connection.on("CrimeWitnessed", __crimeWitnessed);
        connection.on("CrimeWitnessesRemoved", __crimeWitnessesRemoved);
        connection.on("RequestAck", __requestAck);

        const methodList: ReceiverMethod[] = [
            { methodName: "SceneSnapshot", method: __sceneSnapshot },
            { methodName: "CombatStarted", method: __combatStarted },
            { methodName: "CombatUpdated", method: __combatUpdated },
            { methodName: "HostileEncounterStarted", method: __hostileEncounterStarted },
            { methodName: "HostileEncounterResolved", method: __hostileEncounterResolved },
            { methodName: "GuardEncounterStarted", method: __guardEncounterStarted },
            { methodName: "GuardEncounterResolved", method: __guardEncounterResolved },
            { methodName: "TheftEncounterStarted", method: __theftEncounterStarted },
            { methodName: "TheftEncounterResolved", method: __theftEncounterResolved },
            { methodName: "SkillLevelUp", method: __skillLevelUp },
            { methodName: "CharacterLevelUp", method: __characterLevelUp },
            { methodName: "QuestDialogRequested", method: __questDialogRequested },
            { methodName: "QuestObjectiveCompleted", method: __questObjectiveCompleted },
            { methodName: "QuestJournalUpdated", method: __questJournalUpdated },
            { methodName: "CrimeWitnessed", method: __crimeWitnessed },
            { methodName: "CrimeWitnessesRemoved", method: __crimeWitnessesRemoved },
            { methodName: "RequestAck", method: __requestAck }
        ]

        return new ReceiverMethodSubscription(connection, methodList);
    }
}

