/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { IStreamResult, Subject } from '@microsoft/signalr';
import type { ActionResult, SceneSnapshot, CreaturesArrivedPayload, CreaturesLeftPayload, CreaturesMovedPayload, CreaturesUpdatedPayload, CaravansArrivedPayload, CaravansLeftPayload, CaravansUpdatedPayload, WeatherChangedPayload, ClockReanchoredPayload, CrimeNotification } from '../TRPG.GameSessions.Responses';
import type { CombatStarted, CombatUpdated } from '../TRPG.Combat.Responses';
import type { HostileEncounterState, HostileEncounterResolutionFact, ShakedownEncounterState, ShakedownEncounterResolutionFact, GuardEncounterState, GuardEncounterResolutionFact, SuspicionEncounterState, SuspicionEncounterResolutionFact, TrapEncounterState, TrapEncounterResolutionFact, TheftEncounterState, TheftEncounterResolutionFact } from '../TRPG.Encounters.Responses';
import type { PlayerVitalsUpdated, SkillLevelUp, CharacterLevelUp } from '../TRPG.Creatures.Responses';
import type { QuestObjectiveCompleted, QuestJournalUpdated } from '../TRPG.Quests.Responses';

export type IChatHub = {
    /**
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    endSession(): Promise<void>;
    /**
    * @param message Transpiled from string
    * @param cancellationToken Transpiled from System.Threading.CancellationToken
    * @returns Transpiled from System.Collections.Generic.IAsyncEnumerable<string>
    */
    sendChat(message: string): IStreamResult<string>;
    /**
    * @param hours Transpiled from int
    * @param minutes Transpiled from int
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    sendWait(hours: number, minutes: number): Promise<ActionResult>;
    /**
    * @param seatId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    sendSitDown(seatId: string): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    sendStandUp(): Promise<ActionResult>;
    /**
    * @param hours Transpiled from int
    * @param minutes Transpiled from int
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    sendSleep(hours: number, minutes: number): Promise<ActionResult>;
    /**
    * @param triggerId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    sendActivateTrigger(triggerId: string): Promise<ActionResult>;
    /**
    * @param questId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    sendAcceptQuest(questId: string): Promise<ActionResult>;
    /**
    * @param questId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    sendCompleteQuest(questId: string): Promise<ActionResult>;
    /**
    * @param recipientId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    sendDeliverItem(recipientId: string): Promise<ActionResult>;
    /**
    * @param caravanId Transpiled from System.Guid
    * @param destinationLocationId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    sendPurchaseCaravanTicket(caravanId: string, destinationLocationId: string): Promise<ActionResult>;
    /**
    * @param caravanId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    sendBoardCaravan(caravanId: string): Promise<ActionResult>;
    /**
    * @param connectorId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    sendMove(connectorId: string): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    sendFlee(): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    sendRespawn(): Promise<ActionResult>;
    /**
    * @param targetId Transpiled from System.Guid
    * @param abilityName Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    sendCastAbility(targetId: string, abilityName: string): Promise<ActionResult>;
    /**
    * @param targetId Transpiled from System.Guid
    * @param abilityName Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveUseAbilityCombatAction(targetId: string, abilityName: string): Promise<ActionResult>;
    /**
    * @param itemName Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveUseItemCombatAction(itemName: string): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveAttackEncounterAction(): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveFleeEncounterAction(): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveIntimidateEncounterAction(): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolvePayTollEncounterAction(): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveFightEncounterAction(): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveFleeShakedownEncounterAction(): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolvePayFineEncounterAction(): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveGoToJailEncounterAction(): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveResistArrestEncounterAction(): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveComplySuspicionAction(): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveFleeSuspicionAction(): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveAttemptTrapAction(): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveWithdrawTrapAction(): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveDisarmTrapAction(): Promise<ActionResult>;
    /**
    * @param encounterId Transpiled from System.Guid
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    startTheftEncounter(encounterId: string): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveApologizeTheftEncounterAction(): Promise<ActionResult>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task<TRPG.GameSessions.Responses.ActionResult>
    */
    resolveFleeTheftEncounterAction(): Promise<ActionResult>;
}

export type IGameClient = {
    /**
    * @param snapshot Transpiled from TRPG.GameSessions.Responses.SceneSnapshot
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    sceneSnapshot(snapshot: SceneSnapshot): Promise<void>;
    /**
    * @param payload Transpiled from TRPG.GameSessions.Responses.CreaturesArrivedPayload
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    creaturesArrived(payload: CreaturesArrivedPayload): Promise<void>;
    /**
    * @param payload Transpiled from TRPG.GameSessions.Responses.CreaturesLeftPayload
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    creaturesLeft(payload: CreaturesLeftPayload): Promise<void>;
    /**
    * @param payload Transpiled from TRPG.GameSessions.Responses.CreaturesMovedPayload
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    creaturesMoved(payload: CreaturesMovedPayload): Promise<void>;
    /**
    * @param payload Transpiled from TRPG.GameSessions.Responses.CreaturesUpdatedPayload
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    creaturesUpdated(payload: CreaturesUpdatedPayload): Promise<void>;
    /**
    * @param payload Transpiled from TRPG.GameSessions.Responses.CaravansArrivedPayload
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    caravansArrived(payload: CaravansArrivedPayload): Promise<void>;
    /**
    * @param payload Transpiled from TRPG.GameSessions.Responses.CaravansLeftPayload
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    caravansLeft(payload: CaravansLeftPayload): Promise<void>;
    /**
    * @param payload Transpiled from TRPG.GameSessions.Responses.CaravansUpdatedPayload
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    caravansUpdated(payload: CaravansUpdatedPayload): Promise<void>;
    /**
    * @param payload Transpiled from TRPG.GameSessions.Responses.WeatherChangedPayload
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    weatherChanged(payload: WeatherChangedPayload): Promise<void>;
    /**
    * @param payload Transpiled from TRPG.GameSessions.Responses.ClockReanchoredPayload
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    clockReanchored(payload: ClockReanchoredPayload): Promise<void>;
    /**
    * @param payload Transpiled from TRPG.Combat.Responses.CombatStarted
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    combatStarted(payload: CombatStarted): Promise<void>;
    /**
    * @param update Transpiled from TRPG.Combat.Responses.CombatUpdated
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    combatUpdated(update: CombatUpdated): Promise<void>;
    /**
    * @param encounter Transpiled from TRPG.Encounters.Responses.HostileEncounterState
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    hostileEncounterStarted(encounter: HostileEncounterState): Promise<void>;
    /**
    * @param fact Transpiled from TRPG.Encounters.Responses.HostileEncounterResolutionFact
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    hostileEncounterResolved(fact: HostileEncounterResolutionFact): Promise<void>;
    /**
    * @param encounter Transpiled from TRPG.Encounters.Responses.ShakedownEncounterState
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    shakedownEncounterStarted(encounter: ShakedownEncounterState): Promise<void>;
    /**
    * @param fact Transpiled from TRPG.Encounters.Responses.ShakedownEncounterResolutionFact
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    shakedownEncounterResolved(fact: ShakedownEncounterResolutionFact): Promise<void>;
    /**
    * @param encounter Transpiled from TRPG.Encounters.Responses.GuardEncounterState
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    guardEncounterStarted(encounter: GuardEncounterState): Promise<void>;
    /**
    * @param fact Transpiled from TRPG.Encounters.Responses.GuardEncounterResolutionFact
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    guardEncounterResolved(fact: GuardEncounterResolutionFact): Promise<void>;
    /**
    * @param encounter Transpiled from TRPG.Encounters.Responses.SuspicionEncounterState
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    suspicionEncounterStarted(encounter: SuspicionEncounterState): Promise<void>;
    /**
    * @param fact Transpiled from TRPG.Encounters.Responses.SuspicionEncounterResolutionFact
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    suspicionEncounterResolved(fact: SuspicionEncounterResolutionFact): Promise<void>;
    /**
    * @param encounter Transpiled from TRPG.Encounters.Responses.TrapEncounterState
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    trapEncounterStarted(encounter: TrapEncounterState): Promise<void>;
    /**
    * @param fact Transpiled from TRPG.Encounters.Responses.TrapEncounterResolutionFact
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    trapEncounterResolved(fact: TrapEncounterResolutionFact): Promise<void>;
    /**
    * @param encounter Transpiled from TRPG.Encounters.Responses.TheftEncounterState
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    theftEncounterStarted(encounter: TheftEncounterState): Promise<void>;
    /**
    * @param fact Transpiled from TRPG.Encounters.Responses.TheftEncounterResolutionFact
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    theftEncounterResolved(fact: TheftEncounterResolutionFact): Promise<void>;
    /**
    * @param vitals Transpiled from TRPG.Creatures.Responses.PlayerVitalsUpdated
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    playerVitalsUpdated(vitals: PlayerVitalsUpdated): Promise<void>;
    /**
    * @param skillLevelUp Transpiled from TRPG.Creatures.Responses.SkillLevelUp
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    skillLevelUp(skillLevelUp: SkillLevelUp): Promise<void>;
    /**
    * @param characterLevelUp Transpiled from TRPG.Creatures.Responses.CharacterLevelUp
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    characterLevelUp(characterLevelUp: CharacterLevelUp): Promise<void>;
    /**
    * @param objective Transpiled from TRPG.Quests.Responses.QuestObjectiveCompleted
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    questObjectiveCompleted(objective: QuestObjectiveCompleted): Promise<void>;
    /**
    * @param questJournal Transpiled from TRPG.Quests.Responses.QuestJournalUpdated
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    questJournalUpdated(questJournal: QuestJournalUpdated): Promise<void>;
    /**
    * @param notification Transpiled from TRPG.GameSessions.Responses.CrimeNotification
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    crimeWitnessed(notification: CrimeNotification): Promise<void>;
    /**
    * @param notification Transpiled from TRPG.GameSessions.Responses.CrimeNotification
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    crimeWitnessesRemoved(notification: CrimeNotification): Promise<void>;
}

