/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { IStreamResult, Subject } from '@microsoft/signalr';
import type { SceneSnapshot, CrimeNotification } from '../TRPG.GameSessions.Responses';
import type { CombatantState, CombatUpdatePayload } from '../TRPG.Combat.Responses';
import type { HostileEncounterState, HostileEncounterResolutionFact, GuardEncounterState, GuardEncounterResolutionFact, TheftEncounterState, TheftEncounterResolutionFact } from '../TRPG.Encounters.Responses';
import type { SkillLevelUp, CharacterLevelUp } from '../TRPG.Creatures.Responses';
import type { QuestDialogRequested, QuestObjectiveCompleted } from '../TRPG.Quests.Responses';

export type IChatHub = {
    /**
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    endSession(): Promise<void>;
    /**
    * @param cancellationToken Transpiled from System.Threading.CancellationToken
    * @returns Transpiled from System.Collections.Generic.IAsyncEnumerable<string>
    */
    receiveOpening(): IStreamResult<string>;
    /**
    * @param message Transpiled from string
    * @param cancellationToken Transpiled from System.Threading.CancellationToken
    * @returns Transpiled from System.Collections.Generic.IAsyncEnumerable<string>
    */
    sendChat(message: string): IStreamResult<string>;
    /**
    * @param hours Transpiled from int
    * @param minutes Transpiled from int
    * @param cancellationToken Transpiled from System.Threading.CancellationToken
    * @returns Transpiled from System.Collections.Generic.IAsyncEnumerable<string>
    */
    sendWait(hours: number, minutes: number): IStreamResult<string>;
    /**
    * @param cancellationToken Transpiled from System.Threading.CancellationToken
    * @returns Transpiled from System.Collections.Generic.IAsyncEnumerable<string>
    */
    sendFlee(): IStreamResult<string>;
    /**
    * @param targetId Transpiled from System.Guid
    * @param abilityName Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    resolveUseAbilityCombatAction(targetId: string, abilityName: string): Promise<void>;
    /**
    * @param itemName Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    resolveUseItemCombatAction(itemName: string): Promise<void>;
    /**
    * @param cancellationToken Transpiled from System.Threading.CancellationToken
    * @returns Transpiled from System.Collections.Generic.IAsyncEnumerable<string>
    */
    resolveAttackEncounterAction(): IStreamResult<string>;
    /**
    * @param cancellationToken Transpiled from System.Threading.CancellationToken
    * @returns Transpiled from System.Collections.Generic.IAsyncEnumerable<string>
    */
    resolveEvadeEncounterAction(): IStreamResult<string>;
    /**
    * @param cancellationToken Transpiled from System.Threading.CancellationToken
    * @returns Transpiled from System.Collections.Generic.IAsyncEnumerable<string>
    */
    resolveRetreatEncounterAction(): IStreamResult<string>;
    /**
    * @param cancellationToken Transpiled from System.Threading.CancellationToken
    * @returns Transpiled from System.Collections.Generic.IAsyncEnumerable<string>
    */
    resolvePayFineEncounterAction(): IStreamResult<string>;
    /**
    * @param cancellationToken Transpiled from System.Threading.CancellationToken
    * @returns Transpiled from System.Collections.Generic.IAsyncEnumerable<string>
    */
    resolveGoToJailEncounterAction(): IStreamResult<string>;
    /**
    * @param cancellationToken Transpiled from System.Threading.CancellationToken
    * @returns Transpiled from System.Collections.Generic.IAsyncEnumerable<string>
    */
    resolveResistArrestEncounterAction(): IStreamResult<string>;
    /**
    * @param encounterId Transpiled from System.Guid
    * @param cancellationToken Transpiled from System.Threading.CancellationToken
    * @returns Transpiled from System.Collections.Generic.IAsyncEnumerable<string>
    */
    startTheftEncounterNarration(encounterId: string): IStreamResult<string>;
    /**
    * @param cancellationToken Transpiled from System.Threading.CancellationToken
    * @returns Transpiled from System.Collections.Generic.IAsyncEnumerable<string>
    */
    resolveApologizeTheftEncounterAction(): IStreamResult<string>;
    /**
    * @param cancellationToken Transpiled from System.Threading.CancellationToken
    * @returns Transpiled from System.Collections.Generic.IAsyncEnumerable<string>
    */
    resolveFightTheftEncounterAction(): IStreamResult<string>;
}

export type IGameClient = {
    /**
    * @param snapshot Transpiled from TRPG.GameSessions.Responses.SceneSnapshot
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    sceneSnapshot(snapshot: SceneSnapshot): Promise<void>;
    /**
    * @param combatants Transpiled from System.Collections.Generic.IReadOnlyCollection<TRPG.Combat.Responses.CombatantState>
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    combatStarted(combatants: CombatantState[]): Promise<void>;
    /**
    * @param update Transpiled from TRPG.Combat.Responses.CombatUpdatePayload
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    combatUpdated(update: CombatUpdatePayload): Promise<void>;
    /**
    * @param encounter Transpiled from TRPG.Encounters.Responses.HostileEncounterState
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    hostileEncounterStarted(encounter: HostileEncounterState): Promise<void>;
    /**
    * @param fact Transpiled from TRPG.Encounters.Responses.HostileEncounterResolutionFact
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    hostileEncounterResolved(fact: HostileEncounterResolutionFact): Promise<void>;
    /**
    * @param encounter Transpiled from TRPG.Encounters.Responses.GuardEncounterState
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    guardEncounterStarted(encounter: GuardEncounterState): Promise<void>;
    /**
    * @param fact Transpiled from TRPG.Encounters.Responses.GuardEncounterResolutionFact
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    guardEncounterResolved(fact: GuardEncounterResolutionFact): Promise<void>;
    /**
    * @param encounter Transpiled from TRPG.Encounters.Responses.TheftEncounterState
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    theftEncounterStarted(encounter: TheftEncounterState): Promise<void>;
    /**
    * @param fact Transpiled from TRPG.Encounters.Responses.TheftEncounterResolutionFact
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    theftEncounterResolved(fact: TheftEncounterResolutionFact): Promise<void>;
    /**
    * @param skillLevelUp Transpiled from TRPG.Creatures.Responses.SkillLevelUp
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    skillLevelUp(skillLevelUp: SkillLevelUp): Promise<void>;
    /**
    * @param characterLevelUp Transpiled from TRPG.Creatures.Responses.CharacterLevelUp
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    characterLevelUp(characterLevelUp: CharacterLevelUp): Promise<void>;
    /**
    * @param questDialog Transpiled from TRPG.Quests.Responses.QuestDialogRequested
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    questDialogRequested(questDialog: QuestDialogRequested): Promise<void>;
    /**
    * @param objective Transpiled from TRPG.Quests.Responses.QuestObjectiveCompleted
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    questObjectiveCompleted(objective: QuestObjectiveCompleted): Promise<void>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    questJournalUpdated(): Promise<void>;
    /**
    * @param notification Transpiled from TRPG.GameSessions.Responses.CrimeNotification
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    crimeWitnessed(notification: CrimeNotification): Promise<void>;
    /**
    * @param notification Transpiled from TRPG.GameSessions.Responses.CrimeNotification
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    crimeWitnessesRemoved(notification: CrimeNotification): Promise<void>;
}

