// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TRPG.Data;

#nullable disable

namespace TRPG.Migrations
{
    [DbContext(typeof(TrpgDbContext))]
    [Migration("20260628021415_AddCityIsCapital")]
    partial class AddCityIsCapital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TRPG.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("building_type");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("FactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("faction_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_buildings");

                    b.HasIndex("CityId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_buildings_city_id_name");

                    b.ToTable("buildings", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.BuildingOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_building_owners");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_building_owners_owner_id");

                    b.HasIndex("BuildingId", "OwnerId")
                        .IsUnique()
                        .HasDatabaseName("ix_building_owners_building_id_owner_id");

                    b.ToTable("building_owners", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<bool>("IsCapital")
                        .HasColumnType("boolean")
                        .HasColumnName("is_capital");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_country_id_name");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.ContainerItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_id");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_container_items");

                    b.HasIndex("ContainerId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_container_items_container_id_index");

                    b.ToTable("container_items", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("WorldId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_world_id_name");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.Faction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_factions");

                    b.HasIndex("WorldId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_factions_world_id_name");

                    b.ToTable("factions", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.FactionMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("faction_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_faction_members");

                    b.HasIndex("FactionId")
                        .HasDatabaseName("ix_faction_members_faction_id");

                    b.HasIndex("PersonId", "FactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_faction_members_person_id_faction_id");

                    b.ToTable("faction_members", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EquippedSlot")
                        .HasColumnType("text")
                        .HasColumnName("equipped_slot");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_inventory_items");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_inventory_items_item_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_inventory_items_person_id");

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("GoldValue")
                        .HasColumnType("integer")
                        .HasColumnName("gold_value");

                    b.Property<bool>("IsStackable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_stackable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("WorldId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_items_world_id_name");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<bool>("Daily")
                        .HasColumnType("boolean")
                        .HasColumnName("daily");

                    b.Property<int>("EndHour")
                        .HasColumnType("integer")
                        .HasColumnName("end_hour");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("StartHour")
                        .HasColumnType("integer")
                        .HasColumnName("start_hour");

                    b.HasKey("Id")
                        .HasName("pk_jobs");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_jobs_person_id");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.NpcChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.HasKey("Id")
                        .HasName("pk_npc_chat_messages");

                    b.HasIndex("ConversationId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_npc_chat_messages_conversation_id_index");

                    b.ToTable("npc_chat_messages", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.NpcConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("LastSummarizedIndex")
                        .HasColumnType("integer")
                        .HasColumnName("last_summarized_index");

                    b.Property<Guid>("NpcId")
                        .HasColumnType("uuid")
                        .HasColumnName("npc_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_npc_conversations");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_npc_conversations_world_id");

                    b.HasIndex("NpcId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_npc_conversations_npc_id_person_id");

                    b.ToTable("npc_conversations", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActiveConditions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("active_conditions");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("biography");

                    b.Property<Guid>("BirthCityId")
                        .HasColumnType("uuid")
                        .HasColumnName("birth_city_id");

                    b.Property<int>("BirthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birth_year");

                    b.Property<int>("Gold")
                        .HasColumnType("integer")
                        .HasColumnName("gold");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProfessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("profession_id");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("race_id");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_persons");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_persons_world_id");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.PersonQuest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_person_quests");

                    b.HasIndex("QuestId")
                        .HasDatabaseName("ix_person_quests_quest_id");

                    b.HasIndex("PersonId", "QuestId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_quests_person_id_quest_id");

                    b.ToTable("person_quests", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.PersonQuestObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<Guid>("ObjectiveId")
                        .HasColumnType("uuid")
                        .HasColumnName("objective_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.HasKey("Id")
                        .HasName("pk_person_quest_objectives");

                    b.HasIndex("ObjectiveId")
                        .HasDatabaseName("ix_person_quest_objectives_objective_id");

                    b.HasIndex("PersonId", "ObjectiveId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_quest_objectives_person_id_objective_id");

                    b.ToTable("person_quest_objectives", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.PersonSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Cooldown")
                        .HasColumnType("integer")
                        .HasColumnName("cooldown");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.HasKey("Id")
                        .HasName("pk_person_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_person_skills_skill_id");

                    b.HasIndex("PersonId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("ix_person_skills_person_id_skill_id");

                    b.ToTable("person_skills", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.Profession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_professions");

                    b.HasIndex("WorldId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_professions_world_id_name");

                    b.ToTable("professions", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.Prop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("behavior_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("behavior_type");

                    b.HasKey("Id")
                        .HasName("pk_props");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_props_room_id");

                    b.ToTable("props", (string)null);

                    b.HasDiscriminator<string>("behavior_type").HasValue("Prop");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TRPG.Models.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("integer")
                        .HasColumnName("experience_reward");

                    b.Property<Guid>("GiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("giver_id");

                    b.Property<int>("GoldReward")
                        .HasColumnType("integer")
                        .HasColumnName("gold_reward");

                    b.PrimitiveCollection<List<Guid>>("ItemRewards")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("item_rewards");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<Guid>>("PrerequisiteQuestIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("prerequisite_quest_ids");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_quests");

                    b.HasIndex("GiverId")
                        .HasDatabaseName("ix_quests_giver_id");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_quests_world_id");

                    b.ToTable("quests", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.QuestObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.Property<Guid>("Target")
                        .HasColumnType("uuid")
                        .HasColumnName("target");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_quest_objectives");

                    b.HasIndex("QuestId")
                        .HasDatabaseName("ix_quest_objectives_quest_id");

                    b.ToTable("quest_objectives", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_races");

                    b.HasIndex("WorldId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_races_world_id_name");

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.Reputation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("faction_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id")
                        .HasName("pk_reputations");

                    b.HasIndex("PersonId", "FactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_reputations_person_id_faction_id");

                    b.ToTable("reputations", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.Road", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float>("DangerLevel")
                        .HasColumnType("real")
                        .HasColumnName("danger_level");

                    b.Property<Guid>("DestinationCityId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_city_id");

                    b.Property<float>("Distance")
                        .HasColumnType("real")
                        .HasColumnName("distance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OriginCityId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_city_id");

                    b.Property<int>("TravelTime")
                        .HasColumnType("integer")
                        .HasColumnName("travel_time");

                    b.HasKey("Id")
                        .HasName("pk_roads");

                    b.HasIndex("OriginCityId", "DestinationCityId")
                        .IsUnique()
                        .HasDatabaseName("ix_roads_origin_city_id_destination_city_id");

                    b.ToTable("roads", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer")
                        .HasColumnName("floor_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("BuildingId")
                        .HasDatabaseName("ix_rooms_building_id");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float?>("AoeRadius")
                        .HasColumnType("real")
                        .HasColumnName("aoe_radius");

                    b.Property<int>("Cooldown")
                        .HasColumnType("integer")
                        .HasColumnName("cooldown");

                    b.Property<int>("Cost")
                        .HasColumnType("integer")
                        .HasColumnName("cost");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<string>("skill_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("skill_type");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("WorldId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_world_id_name");

                    b.ToTable("skills", (string)null);

                    b.HasDiscriminator<string>("skill_type").HasValue("Skill");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TRPG.Models.SkillPrerequisite", b =>
                {
                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<Guid>("PrerequisiteSkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("prerequisite_skill_id");

                    b.HasKey("SkillId", "PrerequisiteSkillId")
                        .HasName("pk_skill_prerequisites");

                    b.ToTable("skill_prerequisites", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_worlds");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_worlds_name");

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.WorldEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_world_events");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_world_events_world_id");

                    b.ToTable("world_events", (string)null);
                });

            modelBuilder.Entity("TRPG.Models.Bed", b =>
                {
                    b.HasBaseType("TRPG.Models.Prop");

                    b.Property<Guid?>("AssignedPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_person_id");

                    b.Property<Guid?>("OccupantId")
                        .HasColumnType("uuid")
                        .HasColumnName("occupant_id");

                    b.ToTable("props", (string)null);

                    b.HasDiscriminator().HasValue("Bed");
                });

            modelBuilder.Entity("TRPG.Models.Container", b =>
                {
                    b.HasBaseType("TRPG.Models.Prop");

                    b.Property<Guid?>("KeyItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("key_item_id");

                    b.Property<string>("StorageItemCategories")
                        .HasColumnType("jsonb")
                        .HasColumnName("storage_item_categories");

                    b.Property<int?>("StorageSize")
                        .HasColumnType("integer")
                        .HasColumnName("storage_size");

                    b.ToTable("props", (string)null);

                    b.HasDiscriminator().HasValue("Container");
                });

            modelBuilder.Entity("TRPG.Models.RoomConnector", b =>
                {
                    b.HasBaseType("TRPG.Models.Prop");

                    b.Property<Guid?>("DestinationRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_room_id");

                    b.Property<Guid?>("KeyItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("key_item_id");

                    b.ToTable("props", null, t =>
                        {
                            t.Property("KeyItemId")
                                .HasColumnName("room_connector_key_item_id");
                        });

                    b.HasDiscriminator().HasValue("RoomConnector");
                });

            modelBuilder.Entity("TRPG.Models.Seat", b =>
                {
                    b.HasBaseType("TRPG.Models.Prop");

                    b.Property<Guid?>("OccupantId")
                        .HasColumnType("uuid")
                        .HasColumnName("occupant_id");

                    b.ToTable("props", null, t =>
                        {
                            t.Property("OccupantId")
                                .HasColumnName("seat_occupant_id");
                        });

                    b.HasDiscriminator().HasValue("Seat");
                });

            modelBuilder.Entity("TRPG.Models.Trigger", b =>
                {
                    b.HasBaseType("TRPG.Models.Prop");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.ToTable("props", (string)null);

                    b.HasDiscriminator().HasValue("Trigger");
                });

            modelBuilder.Entity("TRPG.Models.Workstation", b =>
                {
                    b.HasBaseType("TRPG.Models.Prop");

                    b.Property<Guid?>("AssignedPersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_person_id");

                    b.Property<Guid?>("OccupantId")
                        .HasColumnType("uuid")
                        .HasColumnName("occupant_id");

                    b.Property<string>("WorkstationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workstation_type");

                    b.ToTable("props", null, t =>
                        {
                            t.Property("AssignedPersonId")
                                .HasColumnName("workstation_assigned_person_id");

                            t.Property("OccupantId")
                                .HasColumnName("workstation_occupant_id");
                        });

                    b.HasDiscriminator().HasValue("Workstation");
                });

            modelBuilder.Entity("TRPG.Models.Attack", b =>
                {
                    b.HasBaseType("TRPG.Models.Skill");

                    b.Property<float>("DamageAmount")
                        .HasColumnType("real")
                        .HasColumnName("damage_amount");

                    b.Property<string>("DamageAmountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("damage_amount_type");

                    b.Property<string>("DamageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("damage_type");

                    b.ToTable("skills", (string)null);

                    b.HasDiscriminator().HasValue("Attack");
                });

            modelBuilder.Entity("TRPG.Models.Support", b =>
                {
                    b.HasBaseType("TRPG.Models.Skill");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.ToTable("skills", (string)null);

                    b.HasDiscriminator().HasValue("Support");
                });

            modelBuilder.Entity("TRPG.Models.Building", b =>
                {
                    b.OwnsOne("TRPG.Models.Rectangle", "Boundary", b1 =>
                        {
                            b1.Property<Guid>("BuildingId");

                            b1.Property<int>("Bottom");

                            b1.Property<int>("Left");

                            b1.Property<int>("Right");

                            b1.Property<int>("Top");

                            b1.HasKey("BuildingId");

                            b1.ToTable("buildings");

                            b1
                                .ToJson("boundary")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BuildingId")
                                .HasConstraintName("fk_buildings_buildings_id");
                        });

                    b.Navigation("Boundary")
                        .IsRequired();
                });

            modelBuilder.Entity("TRPG.Models.City", b =>
                {
                    b.OwnsOne("TRPG.Models.Polygon", "Boundary", b1 =>
                        {
                            b1.Property<Guid>("CityId");

                            b1.HasKey("CityId");

                            b1.ToTable("cities");

                            b1
                                .ToJson("boundary")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CityId")
                                .HasConstraintName("fk_cities_cities_id");

                            b1.OwnsMany("TRPG.Models.Point", "Points", b2 =>
                                {
                                    b2.Property<Guid>("PolygonCityId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<double>("X");

                                    b2.Property<double>("Y");

                                    b2.HasKey("PolygonCityId", "__synthesizedOrdinal");

                                    b2.ToTable("cities");

                                    b2.WithOwner()
                                        .HasForeignKey("PolygonCityId")
                                        .HasConstraintName("fk_cities_cities_polygon_city_id");
                                });

                            b1.Navigation("Points");
                        });

                    b.Navigation("Boundary")
                        .IsRequired();
                });

            modelBuilder.Entity("TRPG.Models.ContainerItem", b =>
                {
                    b.HasOne("TRPG.Models.Container", null)
                        .WithMany("Items")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_container_items_props_container_id");
                });

            modelBuilder.Entity("TRPG.Models.Country", b =>
                {
                    b.OwnsOne("TRPG.Models.Polygon", "Boundary", b1 =>
                        {
                            b1.Property<Guid>("CountryId");

                            b1.HasKey("CountryId")
                                .HasName("pk_countries");

                            b1.ToTable("countries");

                            b1
                                .ToJson("boundary")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CountryId")
                                .HasConstraintName("fk_countries_countries_country_id");

                            b1.OwnsMany("TRPG.Models.Point", "Points", b2 =>
                                {
                                    b2.Property<Guid>("PolygonCountryId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<double>("X");

                                    b2.Property<double>("Y");

                                    b2.HasKey("PolygonCountryId", "__synthesizedOrdinal")
                                        .HasName("pk_countries");

                                    b2.ToTable("countries");

                                    b2.WithOwner()
                                        .HasForeignKey("PolygonCountryId")
                                        .HasConstraintName("fk_countries_countries_polygon_country_id");
                                });

                            b1.Navigation("Points");
                        });

                    b.Navigation("Boundary")
                        .IsRequired();
                });

            modelBuilder.Entity("TRPG.Models.InventoryItem", b =>
                {
                    b.HasOne("TRPG.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_items_item_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("TRPG.Models.Item", b =>
                {
                    b.OwnsMany("TRPG.Models.AttributeModifier", "Modifiers", b1 =>
                        {
                            b1.Property<Guid>("ItemId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<float>("Amount");

                            b1.Property<string>("Attribute")
                                .IsRequired();

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.HasKey("ItemId", "__synthesizedOrdinal");

                            b1.ToTable("items");

                            b1
                                .ToJson("modifiers")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ItemId")
                                .HasConstraintName("fk_items_items_item_id");
                        });

                    b.Navigation("Modifiers");
                });

            modelBuilder.Entity("TRPG.Models.Job", b =>
                {
                    b.OwnsOne("TRPG.Models.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("BuildingId")
                                .HasColumnType("uuid")
                                .HasColumnName("location_building_id");

                            b1.Property<Guid?>("CityId")
                                .HasColumnType("uuid")
                                .HasColumnName("location_city_id");

                            b1.HasKey("JobId");

                            b1.HasIndex("CityId", "BuildingId")
                                .HasDatabaseName("ix_jobs_location_city_id_location_building_id");

                            b1.ToTable("jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobId")
                                .HasConstraintName("fk_jobs_jobs_id");

                            b1.OwnsOne("TRPG.Models.Point", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("LocationJobId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<double>("X")
                                        .HasColumnType("double precision")
                                        .HasColumnName("location_coordinates_x");

                                    b2.Property<double>("Y")
                                        .HasColumnType("double precision")
                                        .HasColumnName("location_coordinates_y");

                                    b2.HasKey("LocationJobId");

                                    b2.ToTable("jobs");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationJobId")
                                        .HasConstraintName("fk_jobs_jobs_id");
                                });

                            b1.Navigation("Coordinates")
                                .IsRequired();
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("TRPG.Models.NpcChatMessage", b =>
                {
                    b.HasOne("TRPG.Models.NpcConversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_npc_chat_messages_npc_conversations_conversation_id");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("TRPG.Models.Person", b =>
                {
                    b.OwnsMany("TRPG.Models.ActiveModifier", "ActiveModifiers", b1 =>
                        {
                            b1.Property<Guid>("PersonId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<float>("Amount");

                            b1.Property<string>("Attribute")
                                .IsRequired();

                            b1.Property<int>("RemainingTurns");

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.HasKey("PersonId", "__synthesizedOrdinal");

                            b1.ToTable("persons");

                            b1
                                .ToJson("active_modifiers")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_persons_persons_person_id");
                        });

                    b.OwnsOne("TRPG.Models.Attributes", "Attributes", b1 =>
                        {
                            b1.Property<Guid>("PersonId");

                            b1.Property<int>("Defense");

                            b1.Property<int>("Dexterity");

                            b1.Property<int>("Endurance");

                            b1.Property<float>("FireResistance");

                            b1.Property<float>("IceResistance");

                            b1.Property<int>("Intelligence");

                            b1.Property<float>("LightningResistance");

                            b1.Property<float>("MagicResistance");

                            b1.Property<float>("MovementSpeed");

                            b1.Property<float>("PhysicalResistance");

                            b1.Property<float>("PoisonResistance");

                            b1.Property<int>("Strength");

                            b1.HasKey("PersonId");

                            b1.ToTable("persons");

                            b1
                                .ToJson("attributes")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_persons_persons_id");

                            b1.OwnsOne("TRPG.Models.Meter", "Ap", b2 =>
                                {
                                    b2.Property<Guid>("AttributesPersonId");

                                    b2.Property<int>("Current");

                                    b2.Property<int>("Maximum");

                                    b2.HasKey("AttributesPersonId")
                                        .HasName("pk_persons");

                                    b2.ToTable("persons");

                                    b2.WithOwner()
                                        .HasForeignKey("AttributesPersonId")
                                        .HasConstraintName("fk_persons_persons_attributes_person_id");
                                });

                            b1.OwnsOne("TRPG.Models.Meter", "Hp", b2 =>
                                {
                                    b2.Property<Guid>("AttributesPersonId");

                                    b2.Property<int>("Current");

                                    b2.Property<int>("Maximum");

                                    b2.HasKey("AttributesPersonId")
                                        .HasName("pk_persons");

                                    b2.ToTable("persons");

                                    b2.WithOwner()
                                        .HasForeignKey("AttributesPersonId")
                                        .HasConstraintName("fk_persons_persons_attributes_person_id");
                                });

                            b1.Navigation("Ap")
                                .IsRequired();

                            b1.Navigation("Hp")
                                .IsRequired();
                        });

                    b.OwnsOne("TRPG.Models.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("BuildingId")
                                .HasColumnType("uuid")
                                .HasColumnName("location_building_id");

                            b1.Property<Guid?>("CityId")
                                .HasColumnType("uuid")
                                .HasColumnName("location_city_id");

                            b1.HasKey("PersonId");

                            b1.HasIndex("CityId", "BuildingId")
                                .HasDatabaseName("ix_persons_location_city_id_location_building_id");

                            b1.ToTable("persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_persons_persons_id");

                            b1.OwnsOne("TRPG.Models.Point", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("LocationPersonId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<double>("X")
                                        .HasColumnType("double precision")
                                        .HasColumnName("location_coordinates_x");

                                    b2.Property<double>("Y")
                                        .HasColumnType("double precision")
                                        .HasColumnName("location_coordinates_y");

                                    b2.HasKey("LocationPersonId");

                                    b2.ToTable("persons");

                                    b2.WithOwner()
                                        .HasForeignKey("LocationPersonId")
                                        .HasConstraintName("fk_persons_persons_id");
                                });

                            b1.Navigation("Coordinates")
                                .IsRequired();
                        });

                    b.OwnsOne("TRPG.Models.Progression", "Progression", b1 =>
                        {
                            b1.Property<Guid>("PersonId");

                            b1.Property<int>("Level");

                            b1.HasKey("PersonId");

                            b1.ToTable("persons");

                            b1
                                .ToJson("progression")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("PersonId")
                                .HasConstraintName("fk_persons_persons_id");

                            b1.OwnsOne("TRPG.Models.Meter", "Experience", b2 =>
                                {
                                    b2.Property<Guid>("ProgressionPersonId");

                                    b2.Property<int>("Current");

                                    b2.Property<int>("Maximum");

                                    b2.HasKey("ProgressionPersonId")
                                        .HasName("pk_persons");

                                    b2.ToTable("persons");

                                    b2.WithOwner()
                                        .HasForeignKey("ProgressionPersonId")
                                        .HasConstraintName("fk_persons_persons_progression_person_id");
                                });

                            b1.Navigation("Experience")
                                .IsRequired();
                        });

                    b.Navigation("ActiveModifiers");

                    b.Navigation("Attributes")
                        .IsRequired();

                    b.Navigation("Location")
                        .IsRequired();

                    b.Navigation("Progression")
                        .IsRequired();
                });

            modelBuilder.Entity("TRPG.Models.PersonQuest", b =>
                {
                    b.HasOne("TRPG.Models.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_quests_quests_quest_id");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("TRPG.Models.PersonQuestObjective", b =>
                {
                    b.HasOne("TRPG.Models.QuestObjective", "Objective")
                        .WithMany()
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_quest_objectives_quest_objectives_objective_id");

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("TRPG.Models.PersonSkill", b =>
                {
                    b.HasOne("TRPG.Models.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_skills_skills_skill_id");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("TRPG.Models.QuestObjective", b =>
                {
                    b.OwnsOne("TRPG.Models.Circle", "Region", b1 =>
                        {
                            b1.Property<Guid>("QuestObjectiveId");

                            b1.Property<float>("Radius");

                            b1.HasKey("QuestObjectiveId");

                            b1.ToTable("quest_objectives");

                            b1
                                .ToJson("region")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("QuestObjectiveId")
                                .HasConstraintName("fk_quest_objectives_quest_objectives_id");

                            b1.OwnsOne("TRPG.Models.Location", "Center", b2 =>
                                {
                                    b2.Property<Guid>("CircleQuestObjectiveId");

                                    b2.Property<Guid?>("BuildingId");

                                    b2.Property<Guid?>("CityId");

                                    b2.HasKey("CircleQuestObjectiveId")
                                        .HasName("pk_quest_objectives");

                                    b2.ToTable("quest_objectives");

                                    b2.WithOwner()
                                        .HasForeignKey("CircleQuestObjectiveId")
                                        .HasConstraintName("fk_quest_objectives_quest_objectives_circle_quest_objective_id");

                                    b2.OwnsOne("TRPG.Models.Point", "Coordinates", b3 =>
                                        {
                                            b3.Property<Guid>("LocationCircleQuestObjectiveId");

                                            b3.Property<double>("X");

                                            b3.Property<double>("Y");

                                            b3.HasKey("LocationCircleQuestObjectiveId")
                                                .HasName("pk_quest_objectives");

                                            b3.ToTable("quest_objectives");

                                            b3.WithOwner()
                                                .HasForeignKey("LocationCircleQuestObjectiveId")
                                                .HasConstraintName("fk_quest_objectives_quest_objectives_location_circle_quest_object");
                                        });

                                    b2.Navigation("Coordinates")
                                        .IsRequired();
                                });

                            b1.Navigation("Center")
                                .IsRequired();
                        });

                    b.Navigation("Region")
                        .IsRequired();
                });

            modelBuilder.Entity("TRPG.Models.World", b =>
                {
                    b.OwnsOne("TRPG.Models.Rectangle", "Boundary", b1 =>
                        {
                            b1.Property<Guid>("WorldId");

                            b1.Property<int>("Bottom");

                            b1.Property<int>("Left");

                            b1.Property<int>("Right");

                            b1.Property<int>("Top");

                            b1.HasKey("WorldId")
                                .HasName("pk_worlds");

                            b1.ToTable("worlds");

                            b1
                                .ToJson("boundary")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorldId")
                                .HasConstraintName("fk_worlds_worlds_world_id");
                        });

                    b.Navigation("Boundary")
                        .IsRequired();
                });

            modelBuilder.Entity("TRPG.Models.WorldEvent", b =>
                {
                    b.OwnsOne("TRPG.Models.Circle", "Region", b1 =>
                        {
                            b1.Property<Guid>("WorldEventId");

                            b1.Property<float>("Radius");

                            b1.HasKey("WorldEventId")
                                .HasName("pk_world_events");

                            b1.ToTable("world_events");

                            b1
                                .ToJson("region")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorldEventId")
                                .HasConstraintName("fk_world_events_world_events_world_event_id");

                            b1.OwnsOne("TRPG.Models.Location", "Center", b2 =>
                                {
                                    b2.Property<Guid>("CircleWorldEventId");

                                    b2.Property<Guid?>("BuildingId");

                                    b2.Property<Guid?>("CityId");

                                    b2.HasKey("CircleWorldEventId")
                                        .HasName("pk_world_events");

                                    b2.ToTable("world_events");

                                    b2.WithOwner()
                                        .HasForeignKey("CircleWorldEventId")
                                        .HasConstraintName("fk_world_events_world_events_circle_world_event_id");

                                    b2.OwnsOne("TRPG.Models.Point", "Coordinates", b3 =>
                                        {
                                            b3.Property<Guid>("LocationCircleWorldEventId");

                                            b3.Property<double>("X");

                                            b3.Property<double>("Y");

                                            b3.HasKey("LocationCircleWorldEventId")
                                                .HasName("pk_world_events");

                                            b3.ToTable("world_events");

                                            b3.WithOwner()
                                                .HasForeignKey("LocationCircleWorldEventId")
                                                .HasConstraintName("fk_world_events_world_events_location_circle_world_event_id");
                                        });

                                    b2.Navigation("Coordinates")
                                        .IsRequired();
                                });

                            b1.Navigation("Center")
                                .IsRequired();
                        });

                    b.Navigation("Region")
                        .IsRequired();
                });

            modelBuilder.Entity("TRPG.Models.Attack", b =>
                {
                    b.OwnsMany("TRPG.Models.ConditionEffect", "Conditions", b1 =>
                        {
                            b1.Property<Guid>("AttackId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<float?>("Amount");

                            b1.Property<string>("Condition")
                                .IsRequired();

                            b1.Property<int>("Duration");

                            b1.Property<string>("Type");

                            b1.HasKey("AttackId", "__synthesizedOrdinal");

                            b1.ToTable("skills");

                            b1
                                .ToJson("conditions")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("AttackId")
                                .HasConstraintName("fk_skills_skills_attack_id");
                        });

                    b.Navigation("Conditions");
                });

            modelBuilder.Entity("TRPG.Models.Support", b =>
                {
                    b.OwnsMany("TRPG.Models.AttributeModifier", "Modifiers", b1 =>
                        {
                            b1.Property<Guid>("SupportId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<float>("Amount");

                            b1.Property<string>("Attribute")
                                .IsRequired();

                            b1.Property<string>("Type")
                                .IsRequired();

                            b1.HasKey("SupportId", "__synthesizedOrdinal");

                            b1.ToTable("skills");

                            b1
                                .ToJson("modifiers")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("SupportId")
                                .HasConstraintName("fk_skills_skills_support_id");
                        });

                    b.Navigation("Modifiers");
                });

            modelBuilder.Entity("TRPG.Models.Container", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
