// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TRPG.Data;

#nullable disable

namespace TRPG.Data.Migrations
{
    [DbContext(typeof(TrpgDbContext))]
    [Migration("20260719221724_StoreAllEnumsAsStringByConvention")]
    partial class StoreAllEnumsAsStringByConvention
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TRPG.Data.Models.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("building_type");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("district_id");

                    b.Property<Guid?>("FactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("faction_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_buildings");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_buildings_world_id");

                    b.HasIndex("StateId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_buildings_state_id_name");

                    b.ToTable("buildings", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.BuildingOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_building_owners");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_building_owners_owner_id");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_building_owners_world_id");

                    b.HasIndex("BuildingId", "OwnerId")
                        .IsUnique()
                        .HasDatabaseName("ix_building_owners_building_id_owner_id");

                    b.ToTable("building_owners", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MessageJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("message_json");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("SessionId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ix_chat_messages_session_id_ordinal");

                    b.HasIndex("SessionId", "Role")
                        .HasDatabaseName("ix_chat_messages_session_id_role");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsCapital")
                        .HasColumnType("boolean")
                        .HasColumnName("is_capital");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("StateId")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_state_id");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_cities_world_id");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_country_id_name");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.ContainerItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_id");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_container_items");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_container_items_world_id");

                    b.HasIndex("ContainerId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_container_items_container_id_index");

                    b.ToTable("container_items", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DominantRace")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dominant_race");

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("focus");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("WorldId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_world_id_name");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.Creature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActiveBuffs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("active_buffs");

                    b.Property<string>("ActiveConditions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("active_conditions");

                    b.Property<string>("ActiveDots")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("active_dots");

                    b.Property<string>("ActiveHots")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("active_hots");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("biography");

                    b.Property<Guid>("BirthStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("birth_state_id");

                    b.Property<int>("BirthYear")
                        .HasColumnType("integer")
                        .HasColumnName("birth_year");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("CooldownRemainingByAbility")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cooldown_remaining_by_ability");

                    b.Property<string>("CreatureType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creature_type");

                    b.Property<int>("CurrentAp")
                        .HasColumnType("integer")
                        .HasColumnName("current_ap");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("integer")
                        .HasColumnName("current_hp");

                    b.Property<int>("CurrentMp")
                        .HasColumnType("integer")
                        .HasColumnName("current_mp");

                    b.Property<int>("Defense")
                        .HasColumnType("integer")
                        .HasColumnName("defense");

                    b.Property<int>("Dexterity")
                        .HasColumnType("integer")
                        .HasColumnName("dexterity");

                    b.Property<Guid?>("DistrictId")
                        .HasColumnType("uuid")
                        .HasColumnName("district_id");

                    b.Property<int>("Endurance")
                        .HasColumnType("integer")
                        .HasColumnName("endurance");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("experience");

                    b.Property<float>("FireResistance")
                        .HasColumnType("real")
                        .HasColumnName("fire_resistance");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<int>("Gold")
                        .HasColumnType("integer")
                        .HasColumnName("gold");

                    b.Property<float>("IceResistance")
                        .HasColumnType("real")
                        .HasColumnName("ice_resistance");

                    b.Property<int>("Intelligence")
                        .HasColumnType("integer")
                        .HasColumnName("intelligence");

                    b.Property<TimeSpan>("LastRegenPlaytime")
                        .HasColumnType("interval")
                        .HasColumnName("last_regen_playtime");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<float>("LightningResistance")
                        .HasColumnType("real")
                        .HasColumnName("lightning_resistance");

                    b.Property<float>("MagicResistance")
                        .HasColumnType("real")
                        .HasColumnName("magic_resistance");

                    b.Property<int>("Mana")
                        .HasColumnType("integer")
                        .HasColumnName("mana");

                    b.Property<int>("MaximumAp")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_ap");

                    b.Property<int>("MaximumHp")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_hp");

                    b.Property<int>("MaximumMp")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_mp");

                    b.Property<float>("MovementSpeed")
                        .HasColumnType("real")
                        .HasColumnName("movement_speed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<float>("PhysicalResistance")
                        .HasColumnType("real")
                        .HasColumnName("physical_resistance");

                    b.Property<float>("PoisonResistance")
                        .HasColumnType("real")
                        .HasColumnName("poison_resistance");

                    b.Property<string>("Profession")
                        .HasColumnType("text")
                        .HasColumnName("profession");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<int>("Stamina")
                        .HasColumnType("integer")
                        .HasColumnName("stamina");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_creatures");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_creatures_world_id");

                    b.HasIndex("StateId", "RoomId")
                        .HasDatabaseName("ix_creatures_state_id_room_id");

                    b.ToTable("creatures", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.CreatureAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AbilityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ability_name");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("creature_id");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_creature_abilities");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_creature_abilities_world_id");

                    b.HasIndex("CreatureId", "AbilityName")
                        .IsUnique()
                        .HasDatabaseName("ix_creature_abilities_creature_id_ability_name");

                    b.ToTable("creature_abilities", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.CreatureJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("creature_id");

                    b.Property<int>("EndHour")
                        .HasColumnType("integer")
                        .HasColumnName("end_hour");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("SpecificDay")
                        .HasColumnType("text")
                        .HasColumnName("specific_day");

                    b.Property<int>("StartHour")
                        .HasColumnType("integer")
                        .HasColumnName("start_hour");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_creature_jobs");

                    b.HasIndex("CreatureId")
                        .HasDatabaseName("ix_creature_jobs_creature_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_creature_jobs_room_id");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_creature_jobs_world_id");

                    b.HasIndex("StateId", "RoomId")
                        .HasDatabaseName("ix_creature_jobs_state_id_room_id");

                    b.ToTable("creature_jobs", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.CreatureKnowledge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("KnowerId")
                        .HasColumnType("uuid")
                        .HasColumnName("knower_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_creature_knowledge");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_creature_knowledge_world_id");

                    b.HasIndex("KnowerId", "SubjectType")
                        .HasDatabaseName("ix_creature_knowledge_knower_id_subject_type");

                    b.ToTable("creature_knowledge", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.CreatureQuest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("creature_id");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_creature_quests");

                    b.HasIndex("QuestId")
                        .HasDatabaseName("ix_creature_quests_quest_id");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_creature_quests_world_id");

                    b.HasIndex("CreatureId", "QuestId")
                        .IsUnique()
                        .HasDatabaseName("ix_creature_quests_creature_id_quest_id");

                    b.ToTable("creature_quests", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.CreatureQuestObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("creature_id");

                    b.Property<Guid>("ObjectiveId")
                        .HasColumnType("uuid")
                        .HasColumnName("objective_id");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_creature_quest_objectives");

                    b.HasIndex("ObjectiveId")
                        .HasDatabaseName("ix_creature_quest_objectives_objective_id");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_creature_quest_objectives_world_id");

                    b.HasIndex("CreatureId", "ObjectiveId")
                        .IsUnique()
                        .HasDatabaseName("ix_creature_quest_objectives_creature_id_objective_id");

                    b.ToTable("creature_quest_objectives", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.CreatureSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("creature_id");

                    b.Property<int>("Experience")
                        .HasColumnType("integer")
                        .HasColumnName("experience");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skill");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_creature_skills");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_creature_skills_world_id");

                    b.HasIndex("CreatureId", "Skill")
                        .IsUnique()
                        .HasDatabaseName("ix_creature_skills_creature_id_skill");

                    b.ToTable("creature_skills", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.CreatureWeaponProficiency", b =>
                {
                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("creature_id");

                    b.Property<string>("WeaponType")
                        .HasColumnType("text")
                        .HasColumnName("weapon_type");

                    b.Property<int>("Proficiency")
                        .HasColumnType("integer")
                        .HasColumnName("proficiency");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("CreatureId", "WeaponType")
                        .HasName("pk_creature_weapon_proficiencies");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_creature_weapon_proficiencies_world_id");

                    b.ToTable("creature_weapon_proficiencies", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DistrictType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("district_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_districts");

                    b.HasIndex("CityId")
                        .HasDatabaseName("ix_districts_city_id");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_districts_world_id");

                    b.HasIndex("CityId", "DistrictType")
                        .IsUnique()
                        .HasDatabaseName("ix_districts_city_id_district_type");

                    b.ToTable("districts", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.Faction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsCityFaction")
                        .HasColumnType("boolean")
                        .HasColumnName("is_city_faction");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_factions");

                    b.HasIndex("WorldId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_factions_world_id_name");

                    b.ToTable("factions", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.FactionMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("creature_id");

                    b.Property<Guid>("FactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("faction_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_faction_members");

                    b.HasIndex("FactionId")
                        .HasDatabaseName("ix_faction_members_faction_id");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_faction_members_world_id");

                    b.HasIndex("CreatureId", "FactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_faction_members_creature_id_faction_id");

                    b.ToTable("faction_members", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.Fight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<Guid>>("CombatantIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("combatant_ids");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_fights");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_fights_world_id");

                    b.ToTable("fights", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("OpenConversationCreatureIdsByName")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("open_conversation_creature_ids_by_name");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<TimeSpan>("Playtime")
                        .HasColumnType("interval")
                        .HasColumnName("playtime");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_game_sessions");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_game_sessions_world_id");

                    b.ToTable("game_sessions", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("creature_id");

                    b.Property<string>("EquippedSlot")
                        .HasColumnType("text")
                        .HasColumnName("equipped_slot");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_items");

                    b.HasIndex("CreatureId")
                        .HasDatabaseName("ix_inventory_items_creature_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_inventory_items_item_id");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_inventory_items_world_id");

                    b.ToTable("inventory_items", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("GoldValue")
                        .HasColumnType("integer")
                        .HasColumnName("gold_value");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Modifiers")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("modifiers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rarity");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<string>("item_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("item_type");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_items_world_id");

                    b.ToTable("items", (string)null);

                    b.HasDiscriminator<string>("item_type").HasValue("generic");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TRPG.Data.Models.NpcConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("creature_id");

                    b.Property<Guid>("NpcId")
                        .HasColumnType("uuid")
                        .HasColumnName("npc_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_npc_conversations");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_npc_conversations_world_id");

                    b.HasIndex("NpcId", "CreatureId")
                        .IsUnique()
                        .HasDatabaseName("ix_npc_conversations_npc_id_creature_id");

                    b.ToTable("npc_conversations", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.Prop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.Property<string>("behavior_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("behavior_type");

                    b.HasKey("Id")
                        .HasName("pk_props");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_props_room_id");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_props_world_id");

                    b.ToTable("props", (string)null);

                    b.HasDiscriminator<string>("behavior_type").HasValue("Prop");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TRPG.Data.Models.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("integer")
                        .HasColumnName("experience_reward");

                    b.Property<Guid>("GiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("giver_id");

                    b.Property<int>("GoldReward")
                        .HasColumnType("integer")
                        .HasColumnName("gold_reward");

                    b.PrimitiveCollection<List<Guid>>("ItemRewards")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("item_rewards");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<Guid>>("PrerequisiteQuestIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("prerequisite_quest_ids");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_quests");

                    b.HasIndex("GiverId")
                        .HasDatabaseName("ix_quests_giver_id");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_quests_world_id");

                    b.ToTable("quests", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.QuestObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("quest_id");

                    b.Property<Guid?>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.Property<Guid>("Target")
                        .HasColumnType("uuid")
                        .HasColumnName("target");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_quest_objectives");

                    b.HasIndex("QuestId")
                        .HasDatabaseName("ix_quest_objectives_quest_id");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_quest_objectives_world_id");

                    b.ToTable("quest_objectives", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relationship_type");

                    b.Property<Guid>("RelativeId")
                        .HasColumnType("uuid")
                        .HasColumnName("relative_id");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_relationships");

                    b.HasIndex("RelativeId")
                        .HasDatabaseName("ix_relationships_relative_id");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_relationships_world_id");

                    b.HasIndex("SubjectId", "RelativeId", "RelationshipType")
                        .IsUnique()
                        .HasDatabaseName("ix_relationships_subject_id_relative_id_relationship_type");

                    b.ToTable("relationships", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.Reputation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("creature_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_type");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_reputations");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_reputations_world_id");

                    b.HasIndex("CreatureId", "TargetId", "TargetType")
                        .IsUnique()
                        .HasDatabaseName("ix_reputations_creature_id_target_id_target_type");

                    b.ToTable("reputations", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.Road", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<float>("DangerLevel")
                        .HasColumnType("real")
                        .HasColumnName("danger_level");

                    b.Property<Guid>("DestinationStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_state_id");

                    b.Property<float>("Distance")
                        .HasColumnType("real")
                        .HasColumnName("distance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OriginStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("origin_state_id");

                    b.Property<int>("TravelTime")
                        .HasColumnType("integer")
                        .HasColumnName("travel_time");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_roads");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_roads_world_id");

                    b.HasIndex("OriginStateId", "DestinationStateId")
                        .IsUnique()
                        .HasDatabaseName("ix_roads_origin_state_id_destination_state_id");

                    b.ToTable("roads", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer")
                        .HasColumnName("floor_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("BuildingId")
                        .HasDatabaseName("ix_rooms_building_id");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_rooms_world_id");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.RoomConnectorKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("RoomConnectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_connector_id");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_room_connector_keys");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_room_connector_keys_item_id");

                    b.HasIndex("RoomConnectorId")
                        .HasDatabaseName("ix_room_connector_keys_room_connector_id");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_room_connector_keys_world_id");

                    b.ToTable("room_connector_keys", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_states");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_states_world_id");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_states_country_id_name");

                    b.ToTable("states", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<TimeSpan>("Playtime")
                        .HasColumnType("interval")
                        .HasColumnName("playtime");

                    b.HasKey("Id")
                        .HasName("pk_worlds");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_worlds_name");

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.WorldEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid")
                        .HasColumnName("world_id");

                    b.HasKey("Id")
                        .HasName("pk_world_events");

                    b.HasIndex("WorldId")
                        .HasDatabaseName("ix_world_events_world_id");

                    b.ToTable("world_events", (string)null);
                });

            modelBuilder.Entity("TRPG.Data.Models.AccessoryItem", b =>
                {
                    b.HasBaseType("TRPG.Data.Models.Item");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accessory_type");

                    b.ToTable("items", (string)null);

                    b.HasDiscriminator().HasValue("accessory");
                });

            modelBuilder.Entity("TRPG.Data.Models.AmmunitionItem", b =>
                {
                    b.HasBaseType("TRPG.Data.Models.Item");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ammo_type");

                    b.ToTable("items", (string)null);

                    b.HasDiscriminator().HasValue("ammunition");
                });

            modelBuilder.Entity("TRPG.Data.Models.ArmorItem", b =>
                {
                    b.HasBaseType("TRPG.Data.Models.Item");

                    b.Property<string>("ArmorClass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("armor_class");

                    b.Property<int>("Defense")
                        .HasColumnType("integer")
                        .HasColumnName("defense");

                    b.Property<int>("DurabilityCurrent")
                        .HasColumnType("integer")
                        .HasColumnName("durability_current");

                    b.Property<int>("DurabilityMax")
                        .HasColumnType("integer")
                        .HasColumnName("durability_max");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("armor_type");

                    b.ToTable("items", (string)null);

                    b.HasDiscriminator().HasValue("armor");
                });

            modelBuilder.Entity("TRPG.Data.Models.ConsumableItem", b =>
                {
                    b.HasBaseType("TRPG.Data.Models.Item");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attribute");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.ToTable("items", (string)null);

                    b.HasDiscriminator().HasValue("consumable");
                });

            modelBuilder.Entity("TRPG.Data.Models.ShieldItem", b =>
                {
                    b.HasBaseType("TRPG.Data.Models.Item");

                    b.Property<float>("BlockChance")
                        .HasColumnType("real")
                        .HasColumnName("block_chance");

                    b.Property<int>("Defense")
                        .HasColumnType("integer")
                        .HasColumnName("defense");

                    b.Property<int>("DurabilityCurrent")
                        .HasColumnType("integer")
                        .HasColumnName("durability_current");

                    b.Property<int>("DurabilityMax")
                        .HasColumnType("integer")
                        .HasColumnName("durability_max");

                    b.ToTable("items", null, t =>
                        {
                            t.Property("Defense")
                                .HasColumnName("shield_item_defense");

                            t.Property("DurabilityCurrent")
                                .HasColumnName("shield_item_durability_current");

                            t.Property("DurabilityMax")
                                .HasColumnName("shield_item_durability_max");
                        });

                    b.HasDiscriminator().HasValue("shield");
                });

            modelBuilder.Entity("TRPG.Data.Models.WeaponItem", b =>
                {
                    b.HasBaseType("TRPG.Data.Models.Item");

                    b.Property<int>("AttackSpeed")
                        .HasColumnType("integer")
                        .HasColumnName("attack_speed");

                    b.Property<int>("DurabilityCurrent")
                        .HasColumnType("integer")
                        .HasColumnName("durability_current");

                    b.Property<int>("DurabilityMax")
                        .HasColumnType("integer")
                        .HasColumnName("durability_max");

                    b.Property<int>("MaxDamage")
                        .HasColumnType("integer")
                        .HasColumnName("max_damage");

                    b.Property<int>("MinDamage")
                        .HasColumnType("integer")
                        .HasColumnName("min_damage");

                    b.Property<int>("Range")
                        .HasColumnType("integer")
                        .HasColumnName("range");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("weapon_type");

                    b.ToTable("items", null, t =>
                        {
                            t.Property("DurabilityCurrent")
                                .HasColumnName("weapon_item_durability_current");

                            t.Property("DurabilityMax")
                                .HasColumnName("weapon_item_durability_max");
                        });

                    b.HasDiscriminator().HasValue("weapon");
                });

            modelBuilder.Entity("TRPG.Data.Models.Bed", b =>
                {
                    b.HasBaseType("TRPG.Data.Models.Prop");

                    b.Property<Guid?>("AssignedCreatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_creature_id");

                    b.Property<Guid?>("OccupantId")
                        .HasColumnType("uuid")
                        .HasColumnName("occupant_id");

                    b.ToTable("props", (string)null);

                    b.HasDiscriminator().HasValue("Bed");
                });

            modelBuilder.Entity("TRPG.Data.Models.Container", b =>
                {
                    b.HasBaseType("TRPG.Data.Models.Prop");

                    b.Property<Guid?>("KeyItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("key_item_id");

                    b.Property<int?>("StorageSize")
                        .HasColumnType("integer")
                        .HasColumnName("storage_size");

                    b.ToTable("props", (string)null);

                    b.HasDiscriminator().HasValue("Container");
                });

            modelBuilder.Entity("TRPG.Data.Models.RoomConnector", b =>
                {
                    b.HasBaseType("TRPG.Data.Models.Prop");

                    b.Property<Guid?>("DestinationRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_room_id");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.ToTable("props", (string)null);

                    b.HasDiscriminator().HasValue("RoomConnector");
                });

            modelBuilder.Entity("TRPG.Data.Models.Seat", b =>
                {
                    b.HasBaseType("TRPG.Data.Models.Prop");

                    b.Property<Guid?>("OccupantId")
                        .HasColumnType("uuid")
                        .HasColumnName("occupant_id");

                    b.ToTable("props", null, t =>
                        {
                            t.Property("OccupantId")
                                .HasColumnName("seat_occupant_id");
                        });

                    b.HasDiscriminator().HasValue("Seat");
                });

            modelBuilder.Entity("TRPG.Data.Models.Trigger", b =>
                {
                    b.HasBaseType("TRPG.Data.Models.Prop");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.ToTable("props", (string)null);

                    b.HasDiscriminator().HasValue("Trigger");
                });

            modelBuilder.Entity("TRPG.Data.Models.Workstation", b =>
                {
                    b.HasBaseType("TRPG.Data.Models.Prop");

                    b.Property<Guid?>("AssignedCreatureId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_creature_id");

                    b.Property<Guid?>("OccupantId")
                        .HasColumnType("uuid")
                        .HasColumnName("occupant_id");

                    b.Property<string>("WorkstationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workstation_type");

                    b.ToTable("props", null, t =>
                        {
                            t.Property("AssignedCreatureId")
                                .HasColumnName("workstation_assigned_creature_id");

                            t.Property("OccupantId")
                                .HasColumnName("workstation_occupant_id");
                        });

                    b.HasDiscriminator().HasValue("Workstation");
                });

            modelBuilder.Entity("TRPG.Data.Models.ContainerItem", b =>
                {
                    b.HasOne("TRPG.Data.Models.Container", null)
                        .WithMany("Items")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_container_items_props_container_id");
                });

            modelBuilder.Entity("TRPG.Data.Models.Country", b =>
                {
                    b.OwnsOne("TRPG.Data.Models.Polygon", "Boundary", b1 =>
                        {
                            b1.Property<Guid>("CountryId");

                            b1.HasKey("CountryId")
                                .HasName("pk_countries");

                            b1.ToTable("countries");

                            b1
                                .ToJson("boundary")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CountryId")
                                .HasConstraintName("fk_countries_countries_country_id");

                            b1.OwnsMany("TRPG.Data.Models.Point", "Points", b2 =>
                                {
                                    b2.Property<Guid>("PolygonCountryId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<double>("X");

                                    b2.Property<double>("Y");

                                    b2.HasKey("PolygonCountryId", "__synthesizedOrdinal")
                                        .HasName("pk_countries");

                                    b2.ToTable("countries");

                                    b2.WithOwner()
                                        .HasForeignKey("PolygonCountryId")
                                        .HasConstraintName("fk_countries_countries_polygon_country_id");
                                });

                            b1.Navigation("Points");
                        });

                    b.Navigation("Boundary")
                        .IsRequired();
                });

            modelBuilder.Entity("TRPG.Data.Models.Creature", b =>
                {
                    b.OwnsOne("TRPG.Data.Models.Attributes", "BaseAttributes", b1 =>
                        {
                            b1.Property<Guid>("CreatureId");

                            b1.Property<int>("Defense");

                            b1.Property<int>("Dexterity");

                            b1.Property<int>("Endurance");

                            b1.Property<float>("FireResistance");

                            b1.Property<float>("IceResistance");

                            b1.Property<int>("Intelligence");

                            b1.Property<float>("LightningResistance");

                            b1.Property<float>("MagicResistance");

                            b1.Property<int>("Mana");

                            b1.Property<int>("MaximumAp");

                            b1.Property<int>("MaximumHp");

                            b1.Property<int>("MaximumMp");

                            b1.Property<float>("MovementSpeed");

                            b1.Property<float>("PhysicalResistance");

                            b1.Property<float>("PoisonResistance");

                            b1.Property<int>("Stamina");

                            b1.Property<int>("Strength");

                            b1.HasKey("CreatureId");

                            b1.ToTable("creatures");

                            b1
                                .ToJson("base_attributes")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CreatureId")
                                .HasConstraintName("fk_creatures_creatures_id");
                        });

                    b.Navigation("BaseAttributes")
                        .IsRequired();
                });

            modelBuilder.Entity("TRPG.Data.Models.CreatureQuest", b =>
                {
                    b.HasOne("TRPG.Data.Models.Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_quests_quests_quest_id");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("TRPG.Data.Models.CreatureQuestObjective", b =>
                {
                    b.HasOne("TRPG.Data.Models.QuestObjective", "Objective")
                        .WithMany()
                        .HasForeignKey("ObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_quest_objectives_quest_objectives_objective_id");

                    b.Navigation("Objective");
                });

            modelBuilder.Entity("TRPG.Data.Models.InventoryItem", b =>
                {
                    b.HasOne("TRPG.Data.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_items_items_item_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("TRPG.Data.Models.State", b =>
                {
                    b.OwnsOne("TRPG.Data.Models.Polygon", "Boundary", b1 =>
                        {
                            b1.Property<Guid>("StateId");

                            b1.HasKey("StateId");

                            b1.ToTable("states");

                            b1
                                .ToJson("boundary")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("StateId")
                                .HasConstraintName("fk_states_states_id");

                            b1.OwnsMany("TRPG.Data.Models.Point", "Points", b2 =>
                                {
                                    b2.Property<Guid>("PolygonStateId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<double>("X");

                                    b2.Property<double>("Y");

                                    b2.HasKey("PolygonStateId", "__synthesizedOrdinal");

                                    b2.ToTable("states");

                                    b2.WithOwner()
                                        .HasForeignKey("PolygonStateId")
                                        .HasConstraintName("fk_states_states_polygon_state_id");
                                });

                            b1.Navigation("Points");
                        });

                    b.OwnsOne("TRPG.Data.Models.Point", "Center", b1 =>
                        {
                            b1.Property<Guid>("StateId");

                            b1.Property<double>("X");

                            b1.Property<double>("Y");

                            b1.HasKey("StateId");

                            b1.ToTable("states");

                            b1
                                .ToJson("center")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("StateId")
                                .HasConstraintName("fk_states_states_id");
                        });

                    b.Navigation("Boundary")
                        .IsRequired();

                    b.Navigation("Center")
                        .IsRequired();
                });

            modelBuilder.Entity("TRPG.Data.Models.World", b =>
                {
                    b.OwnsOne("TRPG.Data.Models.Rectangle", "Boundary", b1 =>
                        {
                            b1.Property<Guid>("WorldId");

                            b1.Property<int>("Bottom");

                            b1.Property<int>("Left");

                            b1.Property<int>("Right");

                            b1.Property<int>("Top");

                            b1.HasKey("WorldId");

                            b1.ToTable("worlds");

                            b1
                                .ToJson("boundary")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WorldId")
                                .HasConstraintName("fk_worlds_worlds_id");
                        });

                    b.Navigation("Boundary")
                        .IsRequired();
                });

            modelBuilder.Entity("TRPG.Data.Models.Container", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
