<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TRPG.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TRPG.Application.Common\TRPG.Application.Common.csproj" />
    <ProjectReference Include="..\TRPG.Application.Reputations\TRPG.Application.Reputations.csproj" />
    <ProjectReference Include="..\TRPG.Domain\TRPG.Domain.csproj" />
    <ProjectReference Include="..\TRPG.Data\TRPG.Data.csproj" />
  </ItemGroup>
</Project>
