import type { ActionFailureReason } from '@/api/signalr-client/TRPG.GameSessions.Responses';

export const actionFailureCopy: Record<ActionFailureReason, string> = {
  NoEntrance: "There's no way in from here.",
  Locked: 'The door is locked.',
  NothingToEnter: "There's nothing to enter here.",
  EncounterActive: "You can't do that during an encounter.",
  SeatOccupied: 'Someone is already sitting there.',
  SeatNotNearby: "You're too far from that seat.",
  PlayerNotIdle: "You can't do that right now.",
  NotSitting: "You're not sitting down.",
  InvalidDuration: "That's not a valid length of time.",
  Afflicted: "You're too afflicted to do that.",
  NotYourRoom: "That room isn't yours.",
  NothingToActivate: "There's nothing to activate here.",
  AlreadyActivated: "It's already been activated.",
  QuestUnavailable: "That quest isn't available.",
  NothingToDeliver: 'You have nothing to hand over.',
  NoFight: "You're not in a fight.",
  NotDead: "You're not dead.",
  NoTicket: "You don't hold a ticket.",
  CaravanNotPresent: 'The caravan has already left.',
  TravelSuspended: 'Travel is suspended right now.',
  InsufficientGold: "You can't afford that.",
  AlreadyHoldsTicket: 'You already hold a ticket.',
  InvalidDestination: "The caravan doesn't go there.",
  NoEncounter: "There's no encounter to resolve.",
  AbilityNotFound: "You don't know that ability.",
  AbilityUnavailable: "You can't use that ability right now.",
};
