// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteAdminSessionsBySessionIdData, DeleteAdminSessionsBySessionIdResponses, DeleteWorldsByWorldIdData, DeleteWorldsByWorldIdResponses, GetAbilitiesBySkillData, GetAbilitiesBySkillResponses, GetCorpsesData, GetCorpsesResponses, GetCreatureGenerationOptionsData, GetCreatureGenerationOptionsResponses, GetCreaturesByCreatureIdAbilitiesData, GetCreaturesByCreatureIdAbilitiesResponses, GetCreaturesByCreatureIdAttributePointsData, GetCreaturesByCreatureIdAttributePointsResponses, GetCreaturesByCreatureIdAttributesData, GetCreaturesByCreatureIdAttributesResponses, GetCreaturesByCreatureIdConsumablesData, GetCreaturesByCreatureIdConsumablesResponses, GetCreaturesByCreatureIdInventoryData, GetCreaturesByCreatureIdInventoryResponses, GetCreaturesByCreatureIdLevelData, GetCreaturesByCreatureIdLevelResponses, GetCreaturesByCreatureIdSkillsData, GetCreaturesByCreatureIdSkillsResponses, GetJobsByIdData, GetJobsByIdErrors, GetJobsByIdResponses, GetPlayersByPlayerIdFightAbilitiesData, GetPlayersByPlayerIdFightAbilitiesResponses, GetPlayersByPlayerIdFightData, GetPlayersByPlayerIdFightErrors, GetPlayersByPlayerIdFightResponses, GetSessionsBySessionIdNamedEntitiesData, GetSessionsBySessionIdNamedEntitiesResponses, GetSessionsBySessionIdSceneData, GetSessionsBySessionIdSceneErrors, GetSessionsBySessionIdSceneResponses, GetWorldsData, GetWorldsResponses, PostAdminSessionsBySessionIdChatData, PostAdminSessionsBySessionIdChatResponses, PostAdminSessionsBySessionIdWaitData, PostAdminSessionsBySessionIdWaitErrors, PostAdminSessionsBySessionIdWaitResponses, PostCreaturesByCreatureIdAttributePointsAllocateData, PostCreaturesByCreatureIdAttributePointsAllocateResponses, PostSessionsData, PostSessionsErrors, PostSessionsResponses, PostTransfersData, PostTransfersResponses, PostWorldsData, PostWorldsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getWorlds = <ThrowOnError extends boolean = false>(options?: Options<GetWorldsData, ThrowOnError>): RequestResult<GetWorldsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetWorldsResponses, unknown, ThrowOnError>({ url: '/worlds', ...options });

export const postWorlds = <ThrowOnError extends boolean = false>(options: Options<PostWorldsData, ThrowOnError>): RequestResult<PostWorldsResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostWorldsResponses, unknown, ThrowOnError>({
    url: '/worlds',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteWorldsByWorldId = <ThrowOnError extends boolean = false>(options: Options<DeleteWorldsByWorldIdData, ThrowOnError>): RequestResult<DeleteWorldsByWorldIdResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteWorldsByWorldIdResponses, unknown, ThrowOnError>({ url: '/worlds/{worldId}', ...options });

export const getAbilitiesBySkill = <ThrowOnError extends boolean = false>(options: Options<GetAbilitiesBySkillData, ThrowOnError>): RequestResult<GetAbilitiesBySkillResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetAbilitiesBySkillResponses, unknown, ThrowOnError>({ url: '/abilities/{skill}', ...options });

export const getCreaturesByCreatureIdAbilities = <ThrowOnError extends boolean = false>(options: Options<GetCreaturesByCreatureIdAbilitiesData, ThrowOnError>): RequestResult<GetCreaturesByCreatureIdAbilitiesResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetCreaturesByCreatureIdAbilitiesResponses, unknown, ThrowOnError>({ url: '/creatures/{creatureId}/abilities', ...options });

export const getCreaturesByCreatureIdInventory = <ThrowOnError extends boolean = false>(options: Options<GetCreaturesByCreatureIdInventoryData, ThrowOnError>): RequestResult<GetCreaturesByCreatureIdInventoryResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetCreaturesByCreatureIdInventoryResponses, unknown, ThrowOnError>({ url: '/creatures/{creatureId}/inventory', ...options });

export const getCreaturesByCreatureIdConsumables = <ThrowOnError extends boolean = false>(options: Options<GetCreaturesByCreatureIdConsumablesData, ThrowOnError>): RequestResult<GetCreaturesByCreatureIdConsumablesResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetCreaturesByCreatureIdConsumablesResponses, unknown, ThrowOnError>({ url: '/creatures/{creatureId}/consumables', ...options });

export const getCreaturesByCreatureIdAttributePoints = <ThrowOnError extends boolean = false>(options: Options<GetCreaturesByCreatureIdAttributePointsData, ThrowOnError>): RequestResult<GetCreaturesByCreatureIdAttributePointsResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetCreaturesByCreatureIdAttributePointsResponses, unknown, ThrowOnError>({ url: '/creatures/{creatureId}/attribute-points', ...options });

export const postCreaturesByCreatureIdAttributePointsAllocate = <ThrowOnError extends boolean = false>(options: Options<PostCreaturesByCreatureIdAttributePointsAllocateData, ThrowOnError>): RequestResult<PostCreaturesByCreatureIdAttributePointsAllocateResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostCreaturesByCreatureIdAttributePointsAllocateResponses, unknown, ThrowOnError>({
    url: '/creatures/{creatureId}/attribute-points/allocate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getCreaturesByCreatureIdAttributes = <ThrowOnError extends boolean = false>(options: Options<GetCreaturesByCreatureIdAttributesData, ThrowOnError>): RequestResult<GetCreaturesByCreatureIdAttributesResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetCreaturesByCreatureIdAttributesResponses, unknown, ThrowOnError>({ url: '/creatures/{creatureId}/attributes', ...options });

export const getCreaturesByCreatureIdSkills = <ThrowOnError extends boolean = false>(options: Options<GetCreaturesByCreatureIdSkillsData, ThrowOnError>): RequestResult<GetCreaturesByCreatureIdSkillsResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetCreaturesByCreatureIdSkillsResponses, unknown, ThrowOnError>({ url: '/creatures/{creatureId}/skills', ...options });

export const getCreaturesByCreatureIdLevel = <ThrowOnError extends boolean = false>(options: Options<GetCreaturesByCreatureIdLevelData, ThrowOnError>): RequestResult<GetCreaturesByCreatureIdLevelResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetCreaturesByCreatureIdLevelResponses, unknown, ThrowOnError>({ url: '/creatures/{creatureId}/level', ...options });

export const getCorpses = <ThrowOnError extends boolean = false>(options: Options<GetCorpsesData, ThrowOnError>): RequestResult<GetCorpsesResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetCorpsesResponses, unknown, ThrowOnError>({ url: '/corpses', ...options });

export const getPlayersByPlayerIdFight = <ThrowOnError extends boolean = false>(options: Options<GetPlayersByPlayerIdFightData, ThrowOnError>): RequestResult<GetPlayersByPlayerIdFightResponses, GetPlayersByPlayerIdFightErrors, ThrowOnError> => (options.client ?? client).get<GetPlayersByPlayerIdFightResponses, GetPlayersByPlayerIdFightErrors, ThrowOnError>({ url: '/players/{playerId}/fight', ...options });

export const getPlayersByPlayerIdFightAbilities = <ThrowOnError extends boolean = false>(options: Options<GetPlayersByPlayerIdFightAbilitiesData, ThrowOnError>): RequestResult<GetPlayersByPlayerIdFightAbilitiesResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetPlayersByPlayerIdFightAbilitiesResponses, unknown, ThrowOnError>({ url: '/players/{playerId}/fight/abilities', ...options });

export const getCreatureGenerationOptions = <ThrowOnError extends boolean = false>(options?: Options<GetCreatureGenerationOptionsData, ThrowOnError>): RequestResult<GetCreatureGenerationOptionsResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetCreatureGenerationOptionsResponses, unknown, ThrowOnError>({ url: '/creature-generation/options', ...options });

export const postSessions = <ThrowOnError extends boolean = false>(options: Options<PostSessionsData, ThrowOnError>): RequestResult<PostSessionsResponses, PostSessionsErrors, ThrowOnError> => (options.client ?? client).post<PostSessionsResponses, PostSessionsErrors, ThrowOnError>({ url: '/sessions', ...options });

export const getSessionsBySessionIdScene = <ThrowOnError extends boolean = false>(options: Options<GetSessionsBySessionIdSceneData, ThrowOnError>): RequestResult<GetSessionsBySessionIdSceneResponses, GetSessionsBySessionIdSceneErrors, ThrowOnError> => (options.client ?? client).get<GetSessionsBySessionIdSceneResponses, GetSessionsBySessionIdSceneErrors, ThrowOnError>({ url: '/sessions/{sessionId}/scene', ...options });

export const getSessionsBySessionIdNamedEntities = <ThrowOnError extends boolean = false>(options: Options<GetSessionsBySessionIdNamedEntitiesData, ThrowOnError>): RequestResult<GetSessionsBySessionIdNamedEntitiesResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetSessionsBySessionIdNamedEntitiesResponses, unknown, ThrowOnError>({ url: '/sessions/{sessionId}/named-entities', ...options });

export const getJobsById = <ThrowOnError extends boolean = false>(options: Options<GetJobsByIdData, ThrowOnError>): RequestResult<GetJobsByIdResponses, GetJobsByIdErrors, ThrowOnError> => (options.client ?? client).get<GetJobsByIdResponses, GetJobsByIdErrors, ThrowOnError>({ url: '/jobs/{id}', ...options });

export const postAdminSessionsBySessionIdChat = <ThrowOnError extends boolean = false>(options: Options<PostAdminSessionsBySessionIdChatData, ThrowOnError>): RequestResult<PostAdminSessionsBySessionIdChatResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostAdminSessionsBySessionIdChatResponses, unknown, ThrowOnError>({
    url: '/admin/sessions/{sessionId}/chat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postAdminSessionsBySessionIdWait = <ThrowOnError extends boolean = false>(options: Options<PostAdminSessionsBySessionIdWaitData, ThrowOnError>): RequestResult<PostAdminSessionsBySessionIdWaitResponses, PostAdminSessionsBySessionIdWaitErrors, ThrowOnError> => (options.client ?? client).post<PostAdminSessionsBySessionIdWaitResponses, PostAdminSessionsBySessionIdWaitErrors, ThrowOnError>({
    url: '/admin/sessions/{sessionId}/wait',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const deleteAdminSessionsBySessionId = <ThrowOnError extends boolean = false>(options: Options<DeleteAdminSessionsBySessionIdData, ThrowOnError>): RequestResult<DeleteAdminSessionsBySessionIdResponses, unknown, ThrowOnError> => (options.client ?? client).delete<DeleteAdminSessionsBySessionIdResponses, unknown, ThrowOnError>({ url: '/admin/sessions/{sessionId}', ...options });

export const postTransfers = <ThrowOnError extends boolean = false>(options: Options<PostTransfersData, ThrowOnError>): RequestResult<PostTransfersResponses, unknown, ThrowOnError> => (options.client ?? client).post<PostTransfersResponses, unknown, ThrowOnError>({
    url: '/transfers',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
