// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AbilityAvailability = {
    name: string;
    isUsable: boolean;
    reason: null | string;
};

export type AbilityCategory = 'Offensive' | 'Support';

export type AbilitySummary = {
    name: string;
    skill: Skill;
    description: string;
    apCost: number;
    mpCost: number;
    cooldown: number;
    category: AbilityCategory;
    requiredSkillLevel: number;
    prerequisites: Array<string>;
};

export type ActiveBuff = {
    abilityName: string;
    attribute: AttributeName;
    amount: number;
    amountType: AmountType;
    remainingTurns: number;
};

export type ActiveDot = {
    abilityName: string;
    amount: number;
    damageType: DamageType;
    remainingTurns: number;
};

export type ActiveHot = {
    abilityName: string;
    amount: number;
    remainingTurns: number;
};

export type AllocateAttributePointsRequest = {
    deltas: {
        [key: string]: number;
    };
};

export type AmountType = 'Flat' | 'Percent';

export type ArmorClass = 'Cloth' | 'Leather' | 'Mail' | 'Plate';

export type AttributeName = 'MaximumHp' | 'MaximumAp' | 'MaximumMp' | 'Strength' | 'Defense' | 'Dexterity' | 'Endurance' | 'Stamina' | 'Mana' | 'Intelligence' | 'PhysicalResistance' | 'FireResistance' | 'IceResistance' | 'LightningResistance' | 'PoisonResistance' | 'MagicResistance' | 'MovementSpeed';

export type AttributePointsResponse = {
    unallocatedPoints: number;
};

export type BaseAttributesResponse = {
    strength: number;
    defense: number;
    dexterity: number;
    endurance: number;
    stamina: number;
    mana: number;
    intelligence: number;
};

export type BasicAttackDamageResponse = {
    damagePerTurn: number;
};

export type BuildingType = 'ArcaneShop' | 'Apothecary' | 'Bakery' | 'Barracks' | 'Blacksmith' | 'Carpenter' | 'Castle' | 'Cave' | 'Crypt' | 'GeneralGoods' | 'GuildHall' | 'House' | 'Inn' | 'Jail' | 'Jeweler' | 'Library' | 'Mine' | 'Ruins' | 'Stable' | 'Tailor' | 'Tavern' | 'Temple' | 'Tower';

export type ChatRequest = {
    message: string;
};

export type ChatResponse = {
    response: string;
    metrics: null | TurnMetricsDto;
};

export type CombatantState = {
    id: string;
    name: string;
    level: number;
    isPlayer: boolean;
    isAlive: boolean;
    currentHp: number;
    maximumHp: number;
    currentAp: number;
    maximumAp: number;
    currentMp: number;
    maximumMp: number;
    activeConditions: {
        [key: string]: number;
    };
    activeDots: Array<ActiveDot>;
    activeHots: Array<ActiveHot>;
    activeBuffs: Array<ActiveBuff>;
};

export type CombatSpeedType = 'IncreasedAttackSpeed' | 'FasterCastRate' | 'FasterHitRecovery';

export type ConsumableSummary = {
    itemId: string;
    name: string;
    quantity: number;
    resource: ResourceType;
    restoreAmount: number;
};

export type CreateSessionResponse = {
    sessionId: string;
    playerId: string;
};

export type CreateWorldRequest = {
    playerName: string;
    gender: Gender;
    age: number;
    race: Race;
    playerClass: PlayerClass;
    startingAttributeAllocation?: {
        [key: string]: number;
    };
    description?: string;
    minCityStates?: number;
    maxCityStates?: number;
    minRuralStates?: number;
    maxRuralStates?: number;
    minBuildingsPerState?: number;
    maxBuildingsPerState?: number;
    minFactionMembers?: number;
    maxFactionMembers?: number;
    housesPerCity?: number;
    minHouseholdSize?: number;
    maxHouseholdSize?: number;
    factionCount?: number;
};

export type CreatureGenerationOptionsResponse = {
    pointsPerLevel: number;
    baseAttributes: BaseAttributesResponse;
};

export type CreatureLevelResponse = {
    level: number;
};

export type CreatureState = 'Sleeping' | 'Idle' | 'Busy' | 'Studying' | 'Praying' | 'Training' | 'Sitting' | 'Dead';

export type CreatureStatusSnapshot = {
    id: string;
    name: string;
    creatureType: CreatureType;
    gender: Gender;
    profession: null | Profession;
    level: number;
    age: number;
    state: null | CreatureState;
    gold: number;
    currentHp: number;
    maximumHp: number;
    currentAp: number;
    maximumAp: number;
    currentMp: number;
    maximumMp: number;
    experienceCurrent: number;
    experienceToNextLevel: number;
    factionNames: null | Array<string>;
    reputation: null | number;
    strength: number;
    dexterity: number;
    intelligence: number;
    endurance: number;
    stamina: number;
    mana: number;
    defense: number;
    movementSpeed: number;
    physicalResistance: number;
    fireResistance: number;
    iceResistance: number;
    lightningResistance: number;
    poisonResistance: number;
    magicResistance: number;
};

export type CreatureType = 'Human' | 'Elf' | 'Dwarf' | 'Orc' | 'Halfling' | 'Gnome' | 'Undead' | 'Demon' | 'Beast' | 'Construct' | 'Elemental' | 'Goblin' | 'Wraith' | 'Giant' | 'Dragon';

export type DamageType = 'Physical' | 'Fire' | 'Ice' | 'Lightning' | 'Poison' | 'Magic';

export type EffectiveAttributesResponse = {
    strength: number;
    dexterity: number;
    intelligence: number;
    endurance: number;
    stamina: number;
    mana: number;
    defense: number;
    maximumHp: number;
    maximumAp: number;
    maximumMp: number;
    movementSpeed: number;
    physicalResistance: number;
    fireResistance: number;
    iceResistance: number;
    lightningResistance: number;
    poisonResistance: number;
    magicResistance: number;
};

export type EnqueueJobResponse = {
    jobId: string;
};

export type EntityType = 'Creature' | 'Building' | 'District' | 'World' | 'Country' | 'State' | 'City';

export type EquipItemRequest = {
    itemId: string;
    slot: EquipmentSlot;
};

export type EquipmentSlot = 'Helm' | 'Chest' | 'LeftHand' | 'RightHand' | 'Boots' | 'Necklace' | 'Gloves' | 'LeftRing' | 'RightRing' | 'Belt';

export type FightState = {
    combatants: Array<CombatantState>;
};

export type Gender = 'Male' | 'Female';

export type InventorySummary = {
    gold: number;
    items: Array<ItemDetail>;
};

export type InventoryTransferRequest = {
    items: Array<LootItemSelection>;
};

export type ItemDetail = ({
    $type: 'Weapon';
} & ItemDetailWeaponDetail) | ({
    $type: 'Armor';
} & ItemDetailArmorDetail) | ({
    $type: 'Shield';
} & ItemDetailShieldDetail) | ({
    $type: 'Accessory';
} & ItemDetailAccessoryDetail) | ({
    $type: 'Ammunition';
} & ItemDetailAmmunitionDetail) | ({
    $type: 'Consumable';
} & ItemDetailConsumableItemDetail) | ({
    $type: 'Gold';
} & ItemDetailGoldDetail);

export type ItemDetailAccessoryDetail = {
    $type?: 'Accessory';
    itemId: string;
    name: string;
    description: string;
    weight: number;
    quantity: number;
    equippedSlot: null | EquipmentSlot;
    type: ItemType;
    rarity: null | ItemRarity;
    goldValue: null | number;
    modifiers: Array<ItemModifierSummary>;
};

export type ItemDetailAmmunitionDetail = {
    $type?: 'Ammunition';
    itemId: string;
    name: string;
    description: string;
    weight: number;
    quantity: number;
    equippedSlot: null | EquipmentSlot;
    type: ItemType;
    rarity: null | ItemRarity;
    goldValue: null | number;
    modifiers: Array<ItemModifierSummary>;
};

export type ItemDetailArmorDetail = {
    $type?: 'Armor';
    defense: number;
    armorClass: ArmorClass;
    durabilityCurrent: number;
    durabilityMax: number;
    itemId: string;
    name: string;
    description: string;
    weight: number;
    quantity: number;
    equippedSlot: null | EquipmentSlot;
    type: ItemType;
    rarity: null | ItemRarity;
    goldValue: null | number;
    modifiers: Array<ItemModifierSummary>;
};

export type ItemDetailConsumableItemDetail = {
    $type?: 'Consumable';
    resource: ResourceType;
    restoreAmount: number;
    duration: number;
    itemId: string;
    name: string;
    description: string;
    weight: number;
    quantity: number;
    equippedSlot: null | EquipmentSlot;
    type: ItemType;
    rarity: null | ItemRarity;
    goldValue: null | number;
    modifiers: Array<ItemModifierSummary>;
};

export type ItemDetailGoldDetail = {
    $type?: 'Gold';
    itemId: string;
    name: string;
    description: string;
    weight: number;
    quantity: number;
    equippedSlot: null | EquipmentSlot;
    type: ItemType;
    rarity: null | ItemRarity;
    goldValue: null | number;
    modifiers: Array<ItemModifierSummary>;
};

export type ItemDetailShieldDetail = {
    $type?: 'Shield';
    blockChance: number;
    defense: number;
    magicResistance: number;
    fireResistance: number;
    iceResistance: number;
    lightningResistance: number;
    poisonResistance: number;
    durabilityCurrent: number;
    durabilityMax: number;
    itemId: string;
    name: string;
    description: string;
    weight: number;
    quantity: number;
    equippedSlot: null | EquipmentSlot;
    type: ItemType;
    rarity: null | ItemRarity;
    goldValue: null | number;
    modifiers: Array<ItemModifierSummary>;
};

export type ItemDetailWeaponDetail = {
    $type?: 'Weapon';
    minDamage: number;
    maxDamage: number;
    range: number;
    attacksPerTurn: number;
    isTwoHanded: boolean;
    durabilityCurrent: number;
    durabilityMax: number;
    itemId: string;
    name: string;
    description: string;
    weight: number;
    quantity: number;
    equippedSlot: null | EquipmentSlot;
    type: ItemType;
    rarity: null | ItemRarity;
    goldValue: null | number;
    modifiers: Array<ItemModifierSummary>;
};

export type ItemModifierSummary = ({
    $type: 'Attribute';
} & ItemModifierSummaryAttributeModifierSummary) | ({
    $type: 'CombatSpeed';
} & ItemModifierSummaryCombatSpeedModifierSummary) | ({
    $type: 'ElementalDamage';
} & ItemModifierSummaryElementalDamageModifierSummary) | ({
    $type: 'Leech';
} & ItemModifierSummaryLeechModifierSummary) | ({
    $type: 'SpecialHit';
} & ItemModifierSummarySpecialHitModifierSummary) | ({
    $type: 'SkillBonus';
} & ItemModifierSummarySkillBonusModifierSummary) | ({
    $type: 'Proc';
} & ItemModifierSummaryProcModifierSummary);

export type ItemModifierSummaryAttributeModifierSummary = {
    $type?: 'Attribute';
    amount: number;
    attribute: AttributeName;
    amountType: AmountType;
};

export type ItemModifierSummaryCombatSpeedModifierSummary = {
    $type?: 'CombatSpeed';
    amount: number;
    speedType: CombatSpeedType;
};

export type ItemModifierSummaryElementalDamageModifierSummary = {
    $type?: 'ElementalDamage';
    damageType: DamageType;
    minDamage: number;
    maxDamage: number;
};

export type ItemModifierSummaryLeechModifierSummary = {
    $type?: 'Leech';
    leechType: LeechType;
    percent: number;
};

export type ItemModifierSummaryProcModifierSummary = {
    $type?: 'Proc';
    abilityName: string;
    chance: number;
    trigger: ProcTrigger;
};

export type ItemModifierSummarySkillBonusModifierSummary = {
    $type?: 'SkillBonus';
    amount: number;
    skill: null | Skill;
};

export type ItemModifierSummarySpecialHitModifierSummary = {
    $type?: 'SpecialHit';
    chance: number;
    hitType: SpecialHitType;
};

export type ItemRarity = 'Low' | 'Normal' | 'Magic' | 'Rare' | 'Unique';

export type ItemType = 'Dagger' | 'Sword' | 'Axe' | 'Mace' | 'Hammer' | 'Staff' | 'Wand' | 'Bow' | 'Crossbow' | 'Javelin' | 'GreatSword' | 'GreatAxe' | 'GreatHammer' | 'Helm' | 'Chest' | 'Boots' | 'Gloves' | 'Arrow' | 'Bolt' | 'Ring' | 'Necklace' | 'Belt' | 'Shield' | 'Consumable' | 'Gold';

export type JobStatus = 'Idle' | 'Queued' | 'InProgress' | 'Done' | 'Failed' | 'Cancelled';

export type JobStatusResponse = {
    jobId: string;
    status: JobStatus;
    resultJson: null | string;
    errorMessage: null | string;
};

export type LeechType = 'Life' | 'Mana';

export type LootItemSelection = {
    itemId: string;
    quantity: number;
};

export type NamedEntity = {
    id: string;
    name: string;
    type: EntityType;
    subtype: null | string;
    description: string;
};

export type NearbyBuildingSnapshot = {
    id: string;
    name: string;
    type: BuildingType;
    typeDescription: string;
};

export type NearbyCorpseSummary = {
    id: string;
    name: string;
    itemCount: number;
};

export type NearbyExitSnapshot = {
    description: string;
    destinationRoomName: string;
};

export type NearbyPropSnapshot = {
    id: string;
    name: string;
    type: string;
};

export type PlayerClass = 'Knight' | 'Rogue' | 'Ranger' | 'Mage' | 'Cleric';

export type ProcTrigger = 'OnStriking' | 'WhenStruck' | 'OnKill';

export type Profession = 'Knight' | 'Rogue' | 'Ranger' | 'Mage' | 'Cleric' | 'Mercenary' | 'Alchemist' | 'Blacksmith' | 'Scholar' | 'Merchant' | 'Politician' | 'StableMaster' | 'Bartender' | 'Guard' | 'Baker' | 'Innkeeper' | 'Tailor' | 'Carpenter' | 'Jeweler' | 'Homemaker' | 'Unemployed';

export type Race = 'Human' | 'Elf' | 'Dwarf' | 'Orc' | 'Halfling' | 'Gnome';

export type ResourceType = 'Hp' | 'Ap' | 'Mp';

export type SceneSnapshot = {
    stateName: string;
    cityName: null | string;
    districtName: null | string;
    buildingName: null | string;
    roomName: null | string;
    year: number;
    monthName: string;
    day: number;
    weekdayName: string;
    hour: number;
    playerStatus: CreatureStatusSnapshot;
    nearbyCreatures: Array<CreatureStatusSnapshot>;
    nearbyBuildings: Array<NearbyBuildingSnapshot>;
    nearbyProps: Array<NearbyPropSnapshot>;
    exits: Array<NearbyExitSnapshot>;
};

export type Skill = 'Melee' | 'Unarmed' | 'Sneak' | 'Destruction' | 'Illusion' | 'Archery' | 'Restoration' | 'Alteration' | 'General' | 'Blocking';

export type SkillProgressSummary = {
    skill: Skill;
    level: number;
    experienceCurrent: number;
    experienceToNextLevel: number;
};

export type SpecialHitType = 'CrushingBlow' | 'DeadlyStrike' | 'OpenWounds';

export type TurnMetricsDto = {
    firstTokenMs: number;
    totalMs: number;
    tokenCount: number;
    tokensPerSecond: number;
};

export type UnequipItemRequest = {
    slot: EquipmentSlot;
};

export type WaitRequest = {
    hours: number;
};

export type WaitResponse = {
    message: string;
};

export type WorldSummary = {
    worldId: string;
    name: string;
    hasPlayer: boolean;
};

export type GetWorldsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/worlds';
};

export type GetWorldsResponses = {
    /**
     * OK
     */
    200: Array<WorldSummary>;
};

export type GetWorldsResponse = GetWorldsResponses[keyof GetWorldsResponses];

export type PostWorldsData = {
    body: CreateWorldRequest;
    path?: never;
    query?: never;
    url: '/worlds';
};

export type PostWorldsResponses = {
    /**
     * Accepted
     */
    202: EnqueueJobResponse;
};

export type PostWorldsResponse = PostWorldsResponses[keyof PostWorldsResponses];

export type DeleteWorldsByWorldIdData = {
    body?: never;
    path: {
        worldId: string;
    };
    query?: never;
    url: '/worlds/{worldId}';
};

export type DeleteWorldsByWorldIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteWorldsByWorldIdResponse = DeleteWorldsByWorldIdResponses[keyof DeleteWorldsByWorldIdResponses];

export type GetAbilitiesBySkillData = {
    body?: never;
    path: {
        skill: Skill;
    };
    query?: never;
    url: '/abilities/{skill}';
};

export type GetAbilitiesBySkillResponses = {
    /**
     * OK
     */
    200: Array<AbilitySummary>;
};

export type GetAbilitiesBySkillResponse = GetAbilitiesBySkillResponses[keyof GetAbilitiesBySkillResponses];

export type GetCreaturesByCreatureIdAbilitiesData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/abilities';
};

export type GetCreaturesByCreatureIdAbilitiesResponses = {
    /**
     * OK
     */
    200: Array<AbilitySummary>;
};

export type GetCreaturesByCreatureIdAbilitiesResponse = GetCreaturesByCreatureIdAbilitiesResponses[keyof GetCreaturesByCreatureIdAbilitiesResponses];

export type GetCreaturesByCreatureIdInventoryData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/inventory';
};

export type GetCreaturesByCreatureIdInventoryResponses = {
    /**
     * OK
     */
    200: InventorySummary;
};

export type GetCreaturesByCreatureIdInventoryResponse = GetCreaturesByCreatureIdInventoryResponses[keyof GetCreaturesByCreatureIdInventoryResponses];

export type GetCreaturesByCreatureIdConsumablesData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/consumables';
};

export type GetCreaturesByCreatureIdConsumablesResponses = {
    /**
     * OK
     */
    200: Array<ConsumableSummary>;
};

export type GetCreaturesByCreatureIdConsumablesResponse = GetCreaturesByCreatureIdConsumablesResponses[keyof GetCreaturesByCreatureIdConsumablesResponses];

export type GetCreaturesByCreatureIdAttributePointsData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/attribute-points';
};

export type GetCreaturesByCreatureIdAttributePointsResponses = {
    /**
     * OK
     */
    200: AttributePointsResponse;
};

export type GetCreaturesByCreatureIdAttributePointsResponse = GetCreaturesByCreatureIdAttributePointsResponses[keyof GetCreaturesByCreatureIdAttributePointsResponses];

export type PostCreaturesByCreatureIdAttributePointsAllocateData = {
    body: AllocateAttributePointsRequest;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/attribute-points/allocate';
};

export type PostCreaturesByCreatureIdAttributePointsAllocateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostCreaturesByCreatureIdAttributePointsAllocateResponse = PostCreaturesByCreatureIdAttributePointsAllocateResponses[keyof PostCreaturesByCreatureIdAttributePointsAllocateResponses];

export type GetCreaturesByCreatureIdAttributesData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/attributes';
};

export type GetCreaturesByCreatureIdAttributesResponses = {
    /**
     * OK
     */
    200: BaseAttributesResponse;
};

export type GetCreaturesByCreatureIdAttributesResponse = GetCreaturesByCreatureIdAttributesResponses[keyof GetCreaturesByCreatureIdAttributesResponses];

export type GetCreaturesByCreatureIdStatsData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/stats';
};

export type GetCreaturesByCreatureIdStatsResponses = {
    /**
     * OK
     */
    200: EffectiveAttributesResponse;
};

export type GetCreaturesByCreatureIdStatsResponse = GetCreaturesByCreatureIdStatsResponses[keyof GetCreaturesByCreatureIdStatsResponses];

export type GetCreaturesByCreatureIdBasicAttackDamageData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/basic-attack-damage';
};

export type GetCreaturesByCreatureIdBasicAttackDamageResponses = {
    /**
     * OK
     */
    200: BasicAttackDamageResponse;
};

export type GetCreaturesByCreatureIdBasicAttackDamageResponse = GetCreaturesByCreatureIdBasicAttackDamageResponses[keyof GetCreaturesByCreatureIdBasicAttackDamageResponses];

export type GetCreaturesByCreatureIdSkillsData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/skills';
};

export type GetCreaturesByCreatureIdSkillsResponses = {
    /**
     * OK
     */
    200: Array<SkillProgressSummary>;
};

export type GetCreaturesByCreatureIdSkillsResponse = GetCreaturesByCreatureIdSkillsResponses[keyof GetCreaturesByCreatureIdSkillsResponses];

export type GetCreaturesByCreatureIdLevelData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/level';
};

export type GetCreaturesByCreatureIdLevelResponses = {
    /**
     * OK
     */
    200: CreatureLevelResponse;
};

export type GetCreaturesByCreatureIdLevelResponse = GetCreaturesByCreatureIdLevelResponses[keyof GetCreaturesByCreatureIdLevelResponses];

export type PostCreaturesByCreatureIdEquipmentEquipData = {
    body: EquipItemRequest;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/equipment/equip';
};

export type PostCreaturesByCreatureIdEquipmentEquipResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostCreaturesByCreatureIdEquipmentEquipResponse = PostCreaturesByCreatureIdEquipmentEquipResponses[keyof PostCreaturesByCreatureIdEquipmentEquipResponses];

export type PostCreaturesByCreatureIdEquipmentUnequipData = {
    body: UnequipItemRequest;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/equipment/unequip';
};

export type PostCreaturesByCreatureIdEquipmentUnequipResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostCreaturesByCreatureIdEquipmentUnequipResponse = PostCreaturesByCreatureIdEquipmentUnequipResponses[keyof PostCreaturesByCreatureIdEquipmentUnequipResponses];

export type GetCreaturesByCreatureIdEquipmentPreviewData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query: {
        itemId: string;
        slot: EquipmentSlot;
    };
    url: '/creatures/{creatureId}/equipment/preview';
};

export type GetCreaturesByCreatureIdEquipmentPreviewResponses = {
    /**
     * OK
     */
    200: EffectiveAttributesResponse;
};

export type GetCreaturesByCreatureIdEquipmentPreviewResponse = GetCreaturesByCreatureIdEquipmentPreviewResponses[keyof GetCreaturesByCreatureIdEquipmentPreviewResponses];

export type GetCreaturesByCreatureIdEquipmentPreviewBasicAttackDamageData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query: {
        itemId: string;
        slot: EquipmentSlot;
    };
    url: '/creatures/{creatureId}/equipment/preview/basic-attack-damage';
};

export type GetCreaturesByCreatureIdEquipmentPreviewBasicAttackDamageResponses = {
    /**
     * OK
     */
    200: BasicAttackDamageResponse;
};

export type GetCreaturesByCreatureIdEquipmentPreviewBasicAttackDamageResponse = GetCreaturesByCreatureIdEquipmentPreviewBasicAttackDamageResponses[keyof GetCreaturesByCreatureIdEquipmentPreviewBasicAttackDamageResponses];

export type GetCorpsesData = {
    body?: never;
    path?: never;
    query: {
        nearPlayerId: string;
    };
    url: '/corpses';
};

export type GetCorpsesResponses = {
    /**
     * OK
     */
    200: Array<NearbyCorpseSummary>;
};

export type GetCorpsesResponse = GetCorpsesResponses[keyof GetCorpsesResponses];

export type GetPlayersByPlayerIdFightData = {
    body?: never;
    path: {
        playerId: string;
    };
    query?: never;
    url: '/players/{playerId}/fight';
};

export type GetPlayersByPlayerIdFightErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetPlayersByPlayerIdFightResponses = {
    /**
     * OK
     */
    200: FightState;
};

export type GetPlayersByPlayerIdFightResponse = GetPlayersByPlayerIdFightResponses[keyof GetPlayersByPlayerIdFightResponses];

export type GetPlayersByPlayerIdFightAbilitiesData = {
    body?: never;
    path: {
        playerId: string;
    };
    query?: never;
    url: '/players/{playerId}/fight/abilities';
};

export type GetPlayersByPlayerIdFightAbilitiesResponses = {
    /**
     * OK
     */
    200: Array<AbilityAvailability>;
};

export type GetPlayersByPlayerIdFightAbilitiesResponse = GetPlayersByPlayerIdFightAbilitiesResponses[keyof GetPlayersByPlayerIdFightAbilitiesResponses];

export type GetCreatureGenerationOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/creature-generation/options';
};

export type GetCreatureGenerationOptionsResponses = {
    /**
     * OK
     */
    200: CreatureGenerationOptionsResponse;
};

export type GetCreatureGenerationOptionsResponse = GetCreatureGenerationOptionsResponses[keyof GetCreatureGenerationOptionsResponses];

export type PostSessionsData = {
    body?: never;
    path?: never;
    query: {
        worldId: string;
    };
    url: '/sessions';
};

export type PostSessionsErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type PostSessionsResponses = {
    /**
     * OK
     */
    200: CreateSessionResponse;
};

export type PostSessionsResponse = PostSessionsResponses[keyof PostSessionsResponses];

export type GetSessionsBySessionIdSceneData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/sessions/{sessionId}/scene';
};

export type GetSessionsBySessionIdSceneErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetSessionsBySessionIdSceneResponses = {
    /**
     * OK
     */
    200: SceneSnapshot;
};

export type GetSessionsBySessionIdSceneResponse = GetSessionsBySessionIdSceneResponses[keyof GetSessionsBySessionIdSceneResponses];

export type GetSessionsBySessionIdNamedEntitiesData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/sessions/{sessionId}/named-entities';
};

export type GetSessionsBySessionIdNamedEntitiesResponses = {
    /**
     * OK
     */
    200: Array<NamedEntity>;
};

export type GetSessionsBySessionIdNamedEntitiesResponse = GetSessionsBySessionIdNamedEntitiesResponses[keyof GetSessionsBySessionIdNamedEntitiesResponses];

export type GetSessionsBySessionIdNamedEntitiesByEntityIdData = {
    body?: never;
    path: {
        sessionId: string;
        entityId: string;
    };
    query?: never;
    url: '/sessions/{sessionId}/named-entities/{entityId}';
};

export type GetSessionsBySessionIdNamedEntitiesByEntityIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetSessionsBySessionIdNamedEntitiesByEntityIdResponses = {
    /**
     * OK
     */
    200: NamedEntity;
};

export type GetSessionsBySessionIdNamedEntitiesByEntityIdResponse = GetSessionsBySessionIdNamedEntitiesByEntityIdResponses[keyof GetSessionsBySessionIdNamedEntitiesByEntityIdResponses];

export type GetJobsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/jobs/{id}';
};

export type GetJobsByIdErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetJobsByIdResponses = {
    /**
     * OK
     */
    200: JobStatusResponse;
};

export type GetJobsByIdResponse = GetJobsByIdResponses[keyof GetJobsByIdResponses];

export type PostAdminSessionsBySessionIdChatData = {
    body: ChatRequest;
    path: {
        sessionId: string;
    };
    query?: {
        includeMetrics?: boolean;
    };
    url: '/admin/sessions/{sessionId}/chat';
};

export type PostAdminSessionsBySessionIdChatResponses = {
    /**
     * OK
     */
    200: ChatResponse;
};

export type PostAdminSessionsBySessionIdChatResponse = PostAdminSessionsBySessionIdChatResponses[keyof PostAdminSessionsBySessionIdChatResponses];

export type PostAdminSessionsBySessionIdWaitData = {
    body: WaitRequest;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/admin/sessions/{sessionId}/wait';
};

export type PostAdminSessionsBySessionIdWaitErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PostAdminSessionsBySessionIdWaitResponses = {
    /**
     * OK
     */
    200: WaitResponse;
};

export type PostAdminSessionsBySessionIdWaitResponse = PostAdminSessionsBySessionIdWaitResponses[keyof PostAdminSessionsBySessionIdWaitResponses];

export type DeleteAdminSessionsBySessionIdData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/admin/sessions/{sessionId}';
};

export type DeleteAdminSessionsBySessionIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteAdminSessionsBySessionIdResponse = DeleteAdminSessionsBySessionIdResponses[keyof DeleteAdminSessionsBySessionIdResponses];

export type PostTransfersData = {
    body: InventoryTransferRequest;
    path?: never;
    query: {
        fromId: string;
        toId: string;
    };
    url: '/transfers';
};

export type PostTransfersErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostTransfersResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostTransfersResponse = PostTransfersResponses[keyof PostTransfersResponses];
