// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AbilityAvailability = {
    name: string;
    isUsable: boolean;
    reason: null | string;
};

export type AbilityCategory = 'Offensive' | 'Support';

export type AbilitySummary = {
    name: string;
    skill: Skill;
    description: string;
    apCost: number;
    mpCost: number;
    cooldown: number;
    category: AbilityCategory;
    requiredSkillLevel: number;
    prerequisites: Array<string>;
};

export type ActiveBuff = {
    abilityName: string;
    attribute: AttributeName;
    amount: number;
    amountType: AmountType;
    remainingTurns: number;
};

export type ActiveConditions = {
    blinded?: number;
    bleeding?: number;
    burning?: number;
    disarmed?: number;
    frozen?: number;
    poisoned?: number;
    silenced?: number;
    snared?: number;
    stunned?: number;
};

export type ActiveDot = {
    abilityName: string;
    amount: number;
    damageType: DamageType;
    remainingTurns: number;
};

export type ActiveHot = {
    abilityName: string;
    amount: number;
    remainingTurns: number;
};

export type AllocateAttributePointsRequest = {
    deltas: AttributeAllocation;
};

export type AmountType = 'Flat' | 'Percent';

export type ArmorClass = 'Cloth' | 'Leather' | 'Mail' | 'Plate';

export type AttributeAllocation = {
    strength?: number;
    dexterity?: number;
    endurance?: number;
    stamina?: number;
    mana?: number;
    intelligence?: number;
};

export type AttributeName = 'MaximumHp' | 'MaximumAp' | 'MaximumMp' | 'Strength' | 'Defense' | 'Dexterity' | 'Endurance' | 'Stamina' | 'Mana' | 'Intelligence' | 'PhysicalResistance' | 'FireResistance' | 'IceResistance' | 'LightningResistance' | 'PoisonResistance' | 'MagicResistance' | 'MovementSpeed';

export type AttributePointsResponse = {
    unallocatedPoints: number;
};

export type BaseAttributesResponse = {
    strength: number;
    defense: number;
    dexterity: number;
    endurance: number;
    stamina: number;
    mana: number;
    intelligence: number;
};

export type BasicAttackDamageResponse = {
    damagePerTurn: number;
};

export type BuildingType = 'ArcaneShop' | 'Apothecary' | 'Bakery' | 'Barracks' | 'Blacksmith' | 'Carpenter' | 'Castle' | 'Cave' | 'Crypt' | 'GeneralGoods' | 'GuildHall' | 'House' | 'Inn' | 'Jail' | 'Jeweler' | 'Library' | 'Mine' | 'Ruins' | 'Stable' | 'Tailor' | 'Tavern' | 'Temple' | 'Tower';

export type ChatRequest = {
    message: string;
};

export type ChatResponse = {
    response: string;
    metrics: null | TurnMetricsDto;
};

export type CombatActionResponse = {
    update: null | CombatUpdatePayload;
    errorMessage: null | string;
    outcome: null | CombatOutcome;
    scene?: null | SceneSnapshot;
};

export type CombatantState = {
    id: string;
    name: string;
    level: number;
    isPlayer: boolean;
    isAlive: boolean;
    currentHp: number;
    maximumHp: number;
    currentAp: number;
    maximumAp: number;
    currentMp: number;
    maximumMp: number;
    activeConditions: ActiveConditions;
    activeDots: Array<ActiveDot>;
    activeHots: Array<ActiveHot>;
    activeBuffs: Array<ActiveBuff>;
};

export type CombatOutcome = 'Victory' | 'Defeat' | 'Fled';

export type CombatRoundEvent = ({
    type: 'CombatHitEvent';
} & CombatRoundEventCombatHitEvent) | ({
    type: 'CombatMissEvent';
} & CombatRoundEventCombatMissEvent) | ({
    type: 'CombatBlockEvent';
} & CombatRoundEventCombatBlockEvent) | ({
    type: 'CombatRegeneratedEvent';
} & CombatRoundEventCombatRegeneratedEvent) | ({
    type: 'CombatResourceStateUpdatedEvent';
} & CombatRoundEventCombatResourceStateUpdatedEvent);

export type CombatRoundEventCombatBlockEvent = {
    type?: 'CombatBlockEvent';
    attackerId: string;
    attackerName: string;
    abilityName: string;
    targetId: string;
    targetName: string;
    narration?: null | string;
};

export type CombatRoundEventCombatHitEvent = {
    type?: 'CombatHitEvent';
    damage: number;
    damageType: DamageType;
    isCritical: boolean;
    killed: boolean;
    targetRemainingHp: number;
    targetMaximumHp: number;
    appliedConditions: Array<ConditionType>;
    attackerId: string;
    attackerName: string;
    abilityName: string;
    targetId: string;
    targetName: string;
    narration?: null | string;
};

export type CombatRoundEventCombatMissEvent = {
    type?: 'CombatMissEvent';
    attackerId: string;
    attackerName: string;
    abilityName: string;
    targetId: string;
    targetName: string;
    narration?: null | string;
};

export type CombatRoundEventCombatRegeneratedEvent = {
    type?: 'CombatRegeneratedEvent';
    previousAp: number;
    currentAp: number;
    maximumAp: number;
    previousMp: number;
    currentMp: number;
    maximumMp: number;
    attackerId: string;
    attackerName: string;
    abilityName?: string;
    targetId?: string;
    targetName?: string;
    narration?: null | string;
};

export type CombatRoundEventCombatResourceStateUpdatedEvent = {
    type?: 'CombatResourceStateUpdatedEvent';
    currentAp: number;
    maximumAp: number;
    currentMp: number;
    maximumMp: number;
    attackerId: string;
    attackerName: string;
    abilityName?: string;
    targetId?: string;
    targetName?: string;
    narration?: null | string;
};

export type CombatSpeedType = 'IncreasedAttackSpeed' | 'FasterCastRate' | 'FasterHitRecovery';

export type CombatUpdatePayload = {
    fightState: FightState;
    events: Array<CombatRoundEvent>;
};

export type ConditionType = 'Blinded' | 'Bleeding' | 'Burning' | 'Disarmed' | 'Frozen' | 'Poisoned' | 'Silenced' | 'Snared' | 'Stunned';

export type ConsumableSummary = {
    itemId: string;
    name: string;
    quantity: number;
    resource: ResourceType;
    restoreAmount: number;
};

export type CreateSessionRequest = {
    worldId: string;
};

export type CreateWorldRequest = {
    playerName: string;
    gender: Gender;
    age: number;
    race: Race;
    playerClass: PlayerClass;
    startingAttributeAllocation?: AttributeAllocation;
    description?: string;
    minCityStates?: number;
    maxCityStates?: number;
    minRuralStates?: number;
    maxRuralStates?: number;
    minBuildingsPerState?: number;
    maxBuildingsPerState?: number;
    minFactionMembers?: number;
    maxFactionMembers?: number;
    housesPerCity?: number;
    minHouseholdSize?: number;
    maxHouseholdSize?: number;
    factionCount?: number;
};

export type CreatureGenerationOptionsResponse = {
    pointsPerLevel: number;
    baseAttributes: BaseAttributesResponse;
};

export type CreatureLevelResponse = {
    level: number;
};

export type CreatureState = 'Sleeping' | 'Idle' | 'Busy' | 'Studying' | 'Praying' | 'Training' | 'Sitting' | 'Dead';

export type CreatureStatusSnapshot = {
    id: string;
    name: string;
    creatureType: CreatureType;
    gender: Gender;
    profession: null | Profession;
    level: number;
    age: number;
    state: null | CreatureState;
    gold: number;
    currentHp: number;
    maximumHp: number;
    currentAp: number;
    maximumAp: number;
    currentMp: number;
    maximumMp: number;
    experienceCurrent: number;
    experienceToNextLevel: number;
    factionNames: null | Array<string>;
    reputation: null | number;
    strength: number;
    dexterity: number;
    intelligence: number;
    endurance: number;
    stamina: number;
    mana: number;
    defense: number;
    movementSpeed: number;
    physicalResistance: number;
    fireResistance: number;
    iceResistance: number;
    lightningResistance: number;
    poisonResistance: number;
    magicResistance: number;
    tradeWorkstationId: null | string;
    questMarker: null | QuestMarker;
};

export type CreatureType = 'Human' | 'Elf' | 'Dwarf' | 'Orc' | 'Halfling' | 'Gnome' | 'Undead' | 'Demon' | 'Beast' | 'Construct' | 'Elemental' | 'Goblin' | 'Wraith' | 'Giant' | 'Dragon';

export type DamageType = 'Physical' | 'Fire' | 'Ice' | 'Lightning' | 'Poison' | 'Magic';

export type DistrictType = 'Residential' | 'Scientific' | 'CityCenter' | 'Governmental' | 'HolySite' | 'Encampment';

export type EffectiveAttributesResponse = {
    strength: number;
    dexterity: number;
    intelligence: number;
    endurance: number;
    stamina: number;
    mana: number;
    defense: number;
    maximumHp: number;
    maximumAp: number;
    maximumMp: number;
    movementSpeed: number;
    physicalResistance: number;
    fireResistance: number;
    iceResistance: number;
    lightningResistance: number;
    poisonResistance: number;
    magicResistance: number;
};

export type EnqueueJobResponse = {
    jobId: string;
};

export type EntityType = 'Creature' | 'Building' | 'District' | 'World' | 'Country' | 'State' | 'City' | 'Item';

export type EquipItemRequest = {
    itemId: string;
    slot: EquipmentSlot;
};

export type EquipmentSlot = 'Helm' | 'Chest' | 'LeftHand' | 'RightHand' | 'Boots' | 'Necklace' | 'Gloves' | 'LeftRing' | 'RightRing' | 'Belt';

export type FightState = {
    combatants: Array<CombatantState>;
};

export type Gender = 'Male' | 'Female';

export type InventorySummary = {
    gold: number;
    items: Array<ItemDetail>;
};

export type InventoryTransferRequest = {
    fromId: string;
    toId: string;
    items: Array<ItemSelection>;
};

export type ItemDetail = ({
    $type: 'Weapon';
} & ItemDetailWeaponDetail) | ({
    $type: 'Armor';
} & ItemDetailArmorDetail) | ({
    $type: 'Shield';
} & ItemDetailShieldDetail) | ({
    $type: 'Accessory';
} & ItemDetailAccessoryDetail) | ({
    $type: 'Ammunition';
} & ItemDetailAmmunitionDetail) | ({
    $type: 'Consumable';
} & ItemDetailConsumableItemDetail) | ({
    $type: 'Gold';
} & ItemDetailGoldDetail) | ({
    $type: 'Key';
} & ItemDetailKeyDetail);

export type ItemDetailAccessoryDetail = {
    $type?: 'Accessory';
    itemId: string;
    name: string;
    description: string;
    weight: number;
    quantity: number;
    equippedSlot: null | EquipmentSlot;
    type: ItemType;
    rarity: null | ItemRarity;
    goldValue: number;
    modifiers: Array<ItemModifierSummary>;
    isStackable: boolean;
    isQuestItem?: boolean;
};

export type ItemDetailAmmunitionDetail = {
    $type?: 'Ammunition';
    itemId: string;
    name: string;
    description: string;
    weight: number;
    quantity: number;
    equippedSlot: null | EquipmentSlot;
    type: ItemType;
    rarity: null | ItemRarity;
    goldValue: number;
    modifiers: Array<ItemModifierSummary>;
    isStackable: boolean;
    isQuestItem?: boolean;
};

export type ItemDetailArmorDetail = {
    $type?: 'Armor';
    defense: number;
    armorClass: ArmorClass;
    durabilityCurrent: number;
    durabilityMax: number;
    itemId: string;
    name: string;
    description: string;
    weight: number;
    quantity: number;
    equippedSlot: null | EquipmentSlot;
    type: ItemType;
    rarity: null | ItemRarity;
    goldValue: number;
    modifiers: Array<ItemModifierSummary>;
    isStackable: boolean;
    isQuestItem?: boolean;
};

export type ItemDetailConsumableItemDetail = {
    $type?: 'Consumable';
    resource: ResourceType;
    restoreAmount: number;
    duration: number;
    itemId: string;
    name: string;
    description: string;
    weight: number;
    quantity: number;
    equippedSlot: null | EquipmentSlot;
    type: ItemType;
    rarity: null | ItemRarity;
    goldValue: number;
    modifiers: Array<ItemModifierSummary>;
    isStackable: boolean;
    isQuestItem?: boolean;
};

export type ItemDetailGoldDetail = {
    $type?: 'Gold';
    itemId: string;
    name: string;
    description: string;
    weight: number;
    quantity: number;
    equippedSlot: null | EquipmentSlot;
    type: ItemType;
    rarity: null | ItemRarity;
    goldValue: number;
    modifiers: Array<ItemModifierSummary>;
    isStackable: boolean;
    isQuestItem?: boolean;
};

export type ItemDetailKeyDetail = {
    $type?: 'Key';
    itemId: string;
    name: string;
    description: string;
    weight: number;
    quantity: number;
    equippedSlot: null | EquipmentSlot;
    type: ItemType;
    rarity: null | ItemRarity;
    goldValue: number;
    modifiers: Array<ItemModifierSummary>;
    isStackable: boolean;
    isQuestItem?: boolean;
};

export type ItemDetailShieldDetail = {
    $type?: 'Shield';
    blockChance: number;
    defense: number;
    durabilityCurrent: number;
    durabilityMax: number;
    itemId: string;
    name: string;
    description: string;
    weight: number;
    quantity: number;
    equippedSlot: null | EquipmentSlot;
    type: ItemType;
    rarity: null | ItemRarity;
    goldValue: number;
    modifiers: Array<ItemModifierSummary>;
    isStackable: boolean;
    isQuestItem?: boolean;
};

export type ItemDetailWeaponDetail = {
    $type?: 'Weapon';
    minDamage: number;
    maxDamage: number;
    range: number;
    attacksPerTurn: number;
    isTwoHanded: boolean;
    durabilityCurrent: number;
    durabilityMax: number;
    itemId: string;
    name: string;
    description: string;
    weight: number;
    quantity: number;
    equippedSlot: null | EquipmentSlot;
    type: ItemType;
    rarity: null | ItemRarity;
    goldValue: number;
    modifiers: Array<ItemModifierSummary>;
    isStackable: boolean;
    isQuestItem?: boolean;
};

export type ItemModifierSummary = ({
    $type: 'Attribute';
} & ItemModifierSummaryAttributeModifierSummary) | ({
    $type: 'CombatSpeed';
} & ItemModifierSummaryCombatSpeedModifierSummary) | ({
    $type: 'ElementalDamage';
} & ItemModifierSummaryElementalDamageModifierSummary) | ({
    $type: 'Leech';
} & ItemModifierSummaryLeechModifierSummary) | ({
    $type: 'SpecialHit';
} & ItemModifierSummarySpecialHitModifierSummary) | ({
    $type: 'SkillBonus';
} & ItemModifierSummarySkillBonusModifierSummary) | ({
    $type: 'Proc';
} & ItemModifierSummaryProcModifierSummary);

export type ItemModifierSummaryAttributeModifierSummary = {
    $type?: 'Attribute';
    amount: number;
    attribute: AttributeName;
    amountType: AmountType;
};

export type ItemModifierSummaryCombatSpeedModifierSummary = {
    $type?: 'CombatSpeed';
    amount: number;
    speedType: CombatSpeedType;
};

export type ItemModifierSummaryElementalDamageModifierSummary = {
    $type?: 'ElementalDamage';
    damageType: DamageType;
    minDamage: number;
    maxDamage: number;
};

export type ItemModifierSummaryLeechModifierSummary = {
    $type?: 'Leech';
    leechType: LeechType;
    percent: number;
};

export type ItemModifierSummaryProcModifierSummary = {
    $type?: 'Proc';
    abilityName: string;
    chance: number;
    trigger: ProcTrigger;
};

export type ItemModifierSummarySkillBonusModifierSummary = {
    $type?: 'SkillBonus';
    amount: number;
    skill: null | Skill;
};

export type ItemModifierSummarySpecialHitModifierSummary = {
    $type?: 'SpecialHit';
    chance: number;
    hitType: SpecialHitType;
};

export type ItemRarity = 'Low' | 'Normal' | 'Magic' | 'Rare' | 'Unique';

export type ItemSelection = {
    itemId: string;
    quantity: number;
};

export type ItemType = 'Dagger' | 'Sword' | 'Axe' | 'Mace' | 'Hammer' | 'Staff' | 'Wand' | 'Bow' | 'Crossbow' | 'Javelin' | 'GreatSword' | 'GreatAxe' | 'GreatHammer' | 'Helm' | 'Chest' | 'Boots' | 'Gloves' | 'Arrow' | 'Bolt' | 'Ring' | 'Necklace' | 'Belt' | 'Shield' | 'Consumable' | 'Gold' | 'Key';

export type JobStatus = 'Idle' | 'Queued' | 'InProgress' | 'Done' | 'Failed' | 'Cancelled';

export type JobStatusResponse = {
    jobId: string;
    status: JobStatus;
    resultJson: null | string;
    errorMessage: null | string;
};

export type LeechType = 'Life' | 'Mana';

export type LoreAnchor = {
    id: string;
    name: string;
    type: EntityType;
    subtype: null | string;
    description: string;
};

export type NearbyBuildingSnapshot = {
    id: string;
    name: string;
    type: BuildingType;
    typeDescription: string;
};

export type NearbyCorpseSummary = {
    id: string;
    name: string;
    itemCount: number;
};

export type NearbyExitDestination = ({
    $type: 'District';
} & NearbyExitDestinationDistrictExitDestination) | ({
    $type: 'Building';
} & NearbyExitDestinationBuildingExitDestination) | ({
    $type: 'Room';
} & NearbyExitDestinationRoomExitDestination) | ({
    $type: 'Wilderness';
} & NearbyExitDestinationWildernessExitDestination);

export type NearbyExitDestinationBuildingExitDestination = {
    $type?: 'Building';
    buildingType: BuildingType;
    name: string;
};

export type NearbyExitDestinationDistrictExitDestination = {
    $type?: 'District';
    districtType: DistrictType;
    name: string;
};

export type NearbyExitDestinationRoomExitDestination = {
    $type?: 'Room';
    buildingType: BuildingType;
    name: string;
};

export type NearbyExitDestinationWildernessExitDestination = {
    $type?: 'Wilderness';
    name: string;
};

export type NearbyExitSnapshot = {
    description: string;
    destination: NearbyExitDestination;
};

export type NearbyPropSnapshot = {
    id: string;
    name: string;
    type: string;
};

export type PlayerClass = 'Knight' | 'Rogue' | 'Ranger' | 'Mage' | 'Cleric';

export type PlayerCombatAction = ({
    type: 'UseAbilityAction';
} & PlayerCombatActionUseAbilityAction) | ({
    type: 'UseItemAction';
} & PlayerCombatActionUseItemAction);

export type PlayerCombatActionUseAbilityAction = {
    type?: 'UseAbilityAction';
    targetId: string;
    abilityName: string;
};

export type PlayerCombatActionUseItemAction = {
    type?: 'UseItemAction';
    itemName: string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number;
    detail?: null | string;
    instance?: null | string;
};

export type ProcTrigger = 'OnStriking' | 'WhenStruck' | 'OnKill';

export type Profession = 'Knight' | 'Rogue' | 'Ranger' | 'Mage' | 'Cleric' | 'Mercenary' | 'Alchemist' | 'Blacksmith' | 'Scholar' | 'Merchant' | 'Politician' | 'StableMaster' | 'Bartender' | 'Guard' | 'Baker' | 'Innkeeper' | 'Tailor' | 'Carpenter' | 'Jeweler' | 'Homemaker' | 'Unemployed';

export type QuestJournalEntrySnapshot = {
    id: string;
    name: string;
    description: string;
    goldReward: number;
    status: string;
    isTracked: boolean;
    objectives: Array<QuestObjectiveProgressSnapshot>;
};

export type QuestMarker = 'Available' | 'ReadyToTurnIn';

export type QuestObjectiveProgressSnapshot = {
    name: string;
    description: string;
    amount: number;
    requiredAmount: number;
    locationName: null | string;
};

export type Race = 'Human' | 'Elf' | 'Dwarf' | 'Orc' | 'Halfling' | 'Gnome';

export type ResourceType = 'Hp' | 'Ap' | 'Mp';

export type SceneSnapshot = {
    worldId: string;
    stateName: string;
    cityName: null | string;
    districtName: null | string;
    buildingName: null | string;
    roomName: null | string;
    year: number;
    monthName: string;
    day: number;
    weekdayName: string;
    hour: number;
    playerStatus: CreatureStatusSnapshot;
    nearbyCreatures: Array<CreatureStatusSnapshot>;
    nearbyBuildings: Array<NearbyBuildingSnapshot>;
    nearbyProps: Array<NearbyPropSnapshot>;
    exits: Array<NearbyExitSnapshot>;
};

export type SessionCreatedResponse = {
    sessionId: string;
    playerId: string;
};

export type SetQuestTrackingRequest = {
    isTracked: boolean;
};

export type Skill = 'Melee' | 'Unarmed' | 'Sneak' | 'Destruction' | 'Illusion' | 'Archery' | 'Restoration' | 'Alteration' | 'General' | 'Blocking';

export type SkillProgressSummary = {
    skill: Skill;
    level: number;
    experienceCurrent: number;
    experienceToNextLevel: number;
};

export type SpecialHitType = 'CrushingBlow' | 'DeadlyStrike' | 'OpenWounds';

export type TradeProposalResponse = {
    status: TradeProposalStatus;
};

export type TradeProposalStatus = 'Accepted' | 'Rejected';

export type TradeRequest = {
    playerOffer: Array<ItemSelection>;
    shopOffer: Array<ItemSelection>;
};

export type TradeSnapshot = {
    playerInventory: InventorySummary;
    shopInventory: InventorySummary;
};

export type TurnMetricsDto = {
    firstTokenMs: number;
    totalMs: number;
    tokenCount: number;
    tokensPerSecond: number;
};

export type WaitRequest = {
    hours: number;
};

export type WaitResponse = {
    message: string;
};

export type WorldSummary = {
    worldId: string;
    name: string;
    hasPlayer: boolean;
};

export type ListWorldsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/worlds';
};

export type ListWorldsResponses = {
    /**
     * OK
     */
    200: Array<WorldSummary>;
};

export type ListWorldsResponse = ListWorldsResponses[keyof ListWorldsResponses];

export type CreateWorldData = {
    body: CreateWorldRequest;
    path?: never;
    query?: never;
    url: '/worlds';
};

export type CreateWorldResponses = {
    /**
     * Accepted
     */
    202: EnqueueJobResponse;
};

export type CreateWorldResponse = CreateWorldResponses[keyof CreateWorldResponses];

export type DropWorldData = {
    body?: never;
    path: {
        worldId: string;
    };
    query?: never;
    url: '/worlds/{worldId}';
};

export type DropWorldResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DropWorldResponse = DropWorldResponses[keyof DropWorldResponses];

export type GetAbilitiesBySkillData = {
    body?: never;
    path: {
        skill: Skill;
    };
    query?: never;
    url: '/abilities/{skill}';
};

export type GetAbilitiesBySkillResponses = {
    /**
     * OK
     */
    200: Array<AbilitySummary>;
};

export type GetAbilitiesBySkillResponse = GetAbilitiesBySkillResponses[keyof GetAbilitiesBySkillResponses];

export type GetCreatureAbilitiesData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/abilities';
};

export type GetCreatureAbilitiesResponses = {
    /**
     * OK
     */
    200: Array<AbilitySummary>;
};

export type GetCreatureAbilitiesResponse = GetCreatureAbilitiesResponses[keyof GetCreatureAbilitiesResponses];

export type GetCreatureInventoryData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/inventory';
};

export type GetCreatureInventoryResponses = {
    /**
     * OK
     */
    200: InventorySummary;
};

export type GetCreatureInventoryResponse = GetCreatureInventoryResponses[keyof GetCreatureInventoryResponses];

export type GetCreatureConsumablesData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/consumables';
};

export type GetCreatureConsumablesResponses = {
    /**
     * OK
     */
    200: Array<ConsumableSummary>;
};

export type GetCreatureConsumablesResponse = GetCreatureConsumablesResponses[keyof GetCreatureConsumablesResponses];

export type GetCreatureAttributePointsData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/attribute-points';
};

export type GetCreatureAttributePointsResponses = {
    /**
     * OK
     */
    200: AttributePointsResponse;
};

export type GetCreatureAttributePointsResponse = GetCreatureAttributePointsResponses[keyof GetCreatureAttributePointsResponses];

export type AllocateCreatureAttributePointsData = {
    body: AllocateAttributePointsRequest;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/attribute-points';
};

export type AllocateCreatureAttributePointsResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AllocateCreatureAttributePointsResponse = AllocateCreatureAttributePointsResponses[keyof AllocateCreatureAttributePointsResponses];

export type GetCreatureBaseAttributesData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/base-attributes';
};

export type GetCreatureBaseAttributesResponses = {
    /**
     * OK
     */
    200: BaseAttributesResponse;
};

export type GetCreatureBaseAttributesResponse = GetCreatureBaseAttributesResponses[keyof GetCreatureBaseAttributesResponses];

export type GetCreatureAttributesData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/attributes';
};

export type GetCreatureAttributesResponses = {
    /**
     * OK
     */
    200: EffectiveAttributesResponse;
};

export type GetCreatureAttributesResponse = GetCreatureAttributesResponses[keyof GetCreatureAttributesResponses];

export type GetCreatureBasicAttackDamageData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/basic-attack-damage';
};

export type GetCreatureBasicAttackDamageResponses = {
    /**
     * OK
     */
    200: BasicAttackDamageResponse;
};

export type GetCreatureBasicAttackDamageResponse = GetCreatureBasicAttackDamageResponses[keyof GetCreatureBasicAttackDamageResponses];

export type GetCreatureSkillsData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/skills';
};

export type GetCreatureSkillsResponses = {
    /**
     * OK
     */
    200: Array<SkillProgressSummary>;
};

export type GetCreatureSkillsResponse = GetCreatureSkillsResponses[keyof GetCreatureSkillsResponses];

export type GetCreatureLevelData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/level';
};

export type GetCreatureLevelResponses = {
    /**
     * OK
     */
    200: CreatureLevelResponse;
};

export type GetCreatureLevelResponse = GetCreatureLevelResponses[keyof GetCreatureLevelResponses];

export type EquipCreatureItemData = {
    body: EquipItemRequest;
    path: {
        creatureId: string;
    };
    query?: never;
    url: '/creatures/{creatureId}/equipment';
};

export type EquipCreatureItemResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EquipCreatureItemResponse = EquipCreatureItemResponses[keyof EquipCreatureItemResponses];

export type UnequipCreatureItemData = {
    body?: never;
    path: {
        creatureId: string;
        slot: EquipmentSlot;
    };
    query?: never;
    url: '/creatures/{creatureId}/equipment/{slot}';
};

export type UnequipCreatureItemResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UnequipCreatureItemResponse = UnequipCreatureItemResponses[keyof UnequipCreatureItemResponses];

export type PreviewCreatureEquipmentData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query: {
        itemId: string;
        slot: EquipmentSlot;
    };
    url: '/creatures/{creatureId}/equipment/preview';
};

export type PreviewCreatureEquipmentResponses = {
    /**
     * OK
     */
    200: EffectiveAttributesResponse;
};

export type PreviewCreatureEquipmentResponse = PreviewCreatureEquipmentResponses[keyof PreviewCreatureEquipmentResponses];

export type PreviewCreatureBasicAttackDamageData = {
    body?: never;
    path: {
        creatureId: string;
    };
    query: {
        itemId: string;
        slot: EquipmentSlot;
    };
    url: '/creatures/{creatureId}/equipment/preview/basic-attack-damage';
};

export type PreviewCreatureBasicAttackDamageResponses = {
    /**
     * OK
     */
    200: BasicAttackDamageResponse;
};

export type PreviewCreatureBasicAttackDamageResponse = PreviewCreatureBasicAttackDamageResponses[keyof PreviewCreatureBasicAttackDamageResponses];

export type GetNearbyCorpsesData = {
    body?: never;
    path: {
        playerId: string;
    };
    query?: never;
    url: '/players/{playerId}/nearby-corpses';
};

export type GetNearbyCorpsesResponses = {
    /**
     * OK
     */
    200: Array<NearbyCorpseSummary>;
};

export type GetNearbyCorpsesResponse = GetNearbyCorpsesResponses[keyof GetNearbyCorpsesResponses];

export type GetPlayerFightData = {
    body?: never;
    path: {
        playerId: string;
    };
    query?: never;
    url: '/players/{playerId}/fight';
};

export type GetPlayerFightErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetPlayerFightResponses = {
    /**
     * OK
     */
    200: FightState;
};

export type GetPlayerFightResponse = GetPlayerFightResponses[keyof GetPlayerFightResponses];

export type GetPlayerFightAbilitiesData = {
    body?: never;
    path: {
        playerId: string;
    };
    query?: never;
    url: '/players/{playerId}/fight/abilities';
};

export type GetPlayerFightAbilitiesResponses = {
    /**
     * OK
     */
    200: Array<AbilityAvailability>;
};

export type GetPlayerFightAbilitiesResponse = GetPlayerFightAbilitiesResponses[keyof GetPlayerFightAbilitiesResponses];

export type GetCreatureGenerationOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/creature-generation/options';
};

export type GetCreatureGenerationOptionsResponses = {
    /**
     * OK
     */
    200: CreatureGenerationOptionsResponse;
};

export type GetCreatureGenerationOptionsResponse = GetCreatureGenerationOptionsResponses[keyof GetCreatureGenerationOptionsResponses];

export type CreateSessionData = {
    body: CreateSessionRequest;
    path?: never;
    query?: never;
    url: '/sessions';
};

export type CreateSessionErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type CreateSessionResponses = {
    /**
     * OK
     */
    200: SessionCreatedResponse;
};

export type CreateSessionResponse = CreateSessionResponses[keyof CreateSessionResponses];

export type ResolveCombatActionData = {
    body: PlayerCombatAction;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/sessions/{sessionId}/combat-actions';
};

export type ResolveCombatActionResponses = {
    /**
     * OK
     */
    200: CombatActionResponse;
};

export type ResolveCombatActionResponse = ResolveCombatActionResponses[keyof ResolveCombatActionResponses];

export type GetSessionSceneData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/sessions/{sessionId}/scene';
};

export type GetSessionSceneErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetSessionSceneResponses = {
    /**
     * OK
     */
    200: SceneSnapshot;
};

export type GetSessionSceneResponse = GetSessionSceneResponses[keyof GetSessionSceneResponses];

export type ListSessionLoreAnchorsData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/sessions/{sessionId}/lore-anchors';
};

export type ListSessionLoreAnchorsResponses = {
    /**
     * OK
     */
    200: Array<LoreAnchor>;
};

export type ListSessionLoreAnchorsResponse = ListSessionLoreAnchorsResponses[keyof ListSessionLoreAnchorsResponses];

export type GetSessionLoreAnchorData = {
    body?: never;
    path: {
        sessionId: string;
        anchorId: string;
    };
    query?: never;
    url: '/sessions/{sessionId}/lore-anchors/{anchorId}';
};

export type GetSessionLoreAnchorErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetSessionLoreAnchorResponses = {
    /**
     * OK
     */
    200: LoreAnchor;
};

export type GetSessionLoreAnchorResponse = GetSessionLoreAnchorResponses[keyof GetSessionLoreAnchorResponses];

export type GetJobData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/jobs/{id}';
};

export type GetJobErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetJobResponses = {
    /**
     * OK
     */
    200: JobStatusResponse;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type SendAdminChatData = {
    body: ChatRequest;
    path: {
        sessionId: string;
    };
    query?: {
        includeMetrics?: boolean;
    };
    url: '/admin/sessions/{sessionId}/chat';
};

export type SendAdminChatResponses = {
    /**
     * OK
     */
    200: ChatResponse;
};

export type SendAdminChatResponse = SendAdminChatResponses[keyof SendAdminChatResponses];

export type AdvanceSessionTimeData = {
    body: WaitRequest;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/admin/sessions/{sessionId}/wait';
};

export type AdvanceSessionTimeErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type AdvanceSessionTimeError = AdvanceSessionTimeErrors[keyof AdvanceSessionTimeErrors];

export type AdvanceSessionTimeResponses = {
    /**
     * OK
     */
    200: WaitResponse;
};

export type AdvanceSessionTimeResponse = AdvanceSessionTimeResponses[keyof AdvanceSessionTimeResponses];

export type EndSessionData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/admin/sessions/{sessionId}';
};

export type EndSessionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type EndSessionResponse = EndSessionResponses[keyof EndSessionResponses];

export type TransferInventoryData = {
    body: InventoryTransferRequest;
    path: {
        playerId: string;
    };
    query?: never;
    url: '/players/{playerId}/inventory-transfers';
};

export type TransferInventoryErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: unknown;
};

export type TransferInventoryError = TransferInventoryErrors[keyof TransferInventoryErrors];

export type TransferInventoryResponses = {
    /**
     * No Content
     */
    204: void;
};

export type TransferInventoryResponse = TransferInventoryResponses[keyof TransferInventoryResponses];

export type GetTradeData = {
    body?: never;
    path: {
        playerId: string;
        workstationId: string;
    };
    query?: never;
    url: '/players/{playerId}/trades/{workstationId}';
};

export type GetTradeResponses = {
    /**
     * OK
     */
    200: TradeSnapshot;
};

export type GetTradeResponse = GetTradeResponses[keyof GetTradeResponses];

export type ProposeTradeData = {
    body: TradeRequest;
    path: {
        playerId: string;
        workstationId: string;
    };
    query?: never;
    url: '/players/{playerId}/trades/{workstationId}/proposal';
};

export type ProposeTradeErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type ProposeTradeResponses = {
    /**
     * OK
     */
    200: TradeProposalResponse;
};

export type ProposeTradeResponse = ProposeTradeResponses[keyof ProposeTradeResponses];

export type CompleteTradeData = {
    body: TradeRequest;
    path: {
        playerId: string;
        workstationId: string;
    };
    query: {
        worldId: string;
    };
    url: '/players/{playerId}/trades/{workstationId}/complete';
};

export type CompleteTradeResponses = {
    /**
     * No Content
     */
    204: void;
};

export type CompleteTradeResponse = CompleteTradeResponses[keyof CompleteTradeResponses];

export type GetSessionItemData = {
    body?: never;
    path: {
        sessionId: string;
        itemId: string;
    };
    query?: never;
    url: '/sessions/{sessionId}/items/{itemId}';
};

export type GetSessionItemErrors = {
    /**
     * Not Found
     */
    404: unknown;
};

export type GetSessionItemResponses = {
    /**
     * OK
     */
    200: ItemDetail;
};

export type GetSessionItemResponse = GetSessionItemResponses[keyof GetSessionItemResponses];

export type GetQuestJournalData = {
    body?: never;
    path: {
        playerId: string;
    };
    query: {
        worldId: string;
    };
    url: '/players/{playerId}/quests';
};

export type GetQuestJournalResponses = {
    /**
     * OK
     */
    200: Array<QuestJournalEntrySnapshot>;
};

export type GetQuestJournalResponse = GetQuestJournalResponses[keyof GetQuestJournalResponses];

export type AcceptQuestData = {
    body?: never;
    path: {
        playerId: string;
        questId: string;
    };
    query: {
        worldId: string;
    };
    url: '/players/{playerId}/quests/{questId}/accept';
};

export type AcceptQuestErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type AcceptQuestError = AcceptQuestErrors[keyof AcceptQuestErrors];

export type AcceptQuestResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AcceptQuestResponse = AcceptQuestResponses[keyof AcceptQuestResponses];

export type CompleteQuestData = {
    body?: never;
    path: {
        playerId: string;
        questId: string;
    };
    query: {
        worldId: string;
    };
    url: '/players/{playerId}/quests/{questId}/complete';
};

export type CompleteQuestErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type CompleteQuestError = CompleteQuestErrors[keyof CompleteQuestErrors];

export type CompleteQuestResponses = {
    /**
     * No Content
     */
    204: void;
};

export type CompleteQuestResponse = CompleteQuestResponses[keyof CompleteQuestResponses];

export type SetQuestTrackingData = {
    body: SetQuestTrackingRequest;
    path: {
        playerId: string;
        questId: string;
    };
    query: {
        worldId: string;
    };
    url: '/players/{playerId}/quests/{questId}/tracking';
};

export type SetQuestTrackingErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type SetQuestTrackingError = SetQuestTrackingErrors[keyof SetQuestTrackingErrors];

export type SetQuestTrackingResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SetQuestTrackingResponse = SetQuestTrackingResponses[keyof SetQuestTrackingResponses];
