<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <WarningsNotAsErrors>CS9057</WarningsNotAsErrors>
        <LangVersion>latest</LangVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="TRPG.Tests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.9" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
        <PackageReference Include="OllamaSharp" Version="5.4.25" />
        <PackageReference Include="SharpVoronoiLib" Version="1.2.0" />
        <PackageReference Include="ZLogger" Version="2.5.10" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Tools\" />
    </ItemGroup>

</Project>
