<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TRPG.Tests" />
    <InternalsVisibleTo Include="TRPG" />
    <InternalsVisibleTo Include="TRPG.Balance" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TRPG.Contracts\TRPG.Contracts.csproj" />
    <ProjectReference Include="..\TRPG.Data\TRPG.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.7.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.9" />
    <PackageReference Include="SharpVoronoiLib" Version="1.2.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Common\" />
  </ItemGroup>
</Project>
