import {
  Anvil,
  BedDouble,
  Beer,
  BookOpen,
  Building2,
  Castle,
  Church,
  Croissant,
  Cross,
  FlaskConical,
  Gem,
  Hammer,
  House,
  Landmark,
  type LucideIcon,
  Lock,
  Mountain,
  Pickaxe,
  Shirt,
  ShoppingBag,
  Sparkles,
  Swords,
  Users,
  Warehouse,
} from 'lucide-react';

import type { BuildingType } from '@/api/client';

export const BUILDING_TYPE_ICONS: Record<BuildingType, LucideIcon> = {
  ArcaneShop: Sparkles,
  Apothecary: FlaskConical,
  Bakery: Croissant,
  Barracks: Swords,
  Blacksmith: Anvil,
  Carpenter: Hammer,
  Castle: Castle,
  Cave: Mountain,
  Crypt: Cross,
  GeneralGoods: ShoppingBag,
  GuildHall: Users,
  House: House,
  Inn: BedDouble,
  Jail: Lock,
  Jeweler: Gem,
  Library: BookOpen,
  Mine: Pickaxe,
  Ruins: Landmark,
  Stable: Warehouse,
  Tailor: Shirt,
  Tavern: Beer,
  Temple: Church,
  Tower: Building2,
};
