<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TRPG.Client" />
    <InternalsVisibleTo Include="TRPG.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TRPG.Contracts\TRPG.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.9" />
  </ItemGroup>
</Project>
