/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from TRPG.Quests.ClientModels.QuestDialogMode */
export type QuestDialogMode = "Offer" | "TurnIn";

/** Transpiled from TRPG.Quests.ClientModels.QuestDialogObjective */
export type QuestDialogObjective = {
    /** Transpiled from string */
    name: string;
    /** Transpiled from string */
    description: string;
    /** Transpiled from int */
    requiredAmount: number;
}

/** Transpiled from TRPG.Quests.ClientModels.QuestDialogRequested */
export type QuestDialogRequested = {
    /** Transpiled from System.Guid */
    worldId: string;
    /** Transpiled from System.Guid */
    questId: string;
    /** Transpiled from string */
    name: string;
    /** Transpiled from string */
    description: string;
    /** Transpiled from int */
    goldReward: number;
    /** Transpiled from System.Collections.Generic.IReadOnlyCollection<TRPG.Quests.ClientModels.QuestDialogObjective> */
    objectives: QuestDialogObjective[];
    /** Transpiled from TRPG.Quests.ClientModels.QuestDialogMode */
    mode: QuestDialogMode;
}

/** Transpiled from TRPG.Quests.ClientModels.QuestObjectiveCompleted */
export type QuestObjectiveCompleted = {
    /** Transpiled from string */
    objectiveName: string;
}

