/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from TRPG.Combat.ClientModels.ActiveConditions */
export type ActiveConditions = {
    /** Transpiled from int */
    blinded: number;
    /** Transpiled from int */
    bleeding: number;
    /** Transpiled from int */
    burning: number;
    /** Transpiled from int */
    disarmed: number;
    /** Transpiled from int */
    frozen: number;
    /** Transpiled from int */
    poisoned: number;
    /** Transpiled from int */
    silenced: number;
    /** Transpiled from int */
    snared: number;
    /** Transpiled from int */
    stunned: number;
}

/** Transpiled from TRPG.Combat.ClientModels.CombatActionOutcome */
export type CombatActionOutcome = "Hit" | "Miss" | "Block";

/** Transpiled from TRPG.Combat.ClientModels.CombatActionResult */
export type CombatActionResult = {
    /** Transpiled from TRPG.Combat.ClientModels.CombatActionOutcome */
    outcome: CombatActionOutcome;
    /** Transpiled from System.Guid */
    attackerId: string;
    /** Transpiled from string */
    attackerName: string;
    /** Transpiled from string */
    abilityName: string;
    /** Transpiled from System.Guid */
    targetId: string;
    /** Transpiled from string */
    targetName: string;
    /** Transpiled from int */
    damage?: number;
    /** Transpiled from TRPG.Combat.ClientModels.DamageType */
    damageType?: DamageType;
    /** Transpiled from bool */
    isCritical?: boolean;
    /** Transpiled from bool */
    killed?: boolean;
    /** Transpiled from int */
    targetRemainingHp?: number;
    /** Transpiled from int */
    targetMaximumHp?: number;
    /** Transpiled from System.Collections.Generic.IReadOnlyCollection<TRPG.Combat.ClientModels.ConditionType>? */
    appliedConditions?: ConditionType[];
    /** Transpiled from string */
    narration: string;
}

/** Transpiled from TRPG.Combat.ClientModels.DamageType */
export type DamageType = "Physical" | "Fire" | "Ice" | "Lightning" | "Poison" | "Magic";

/** Transpiled from TRPG.Combat.ClientModels.AttributeName */
export type AttributeName = "MaximumHp" | "MaximumAp" | "MaximumMp" | "Strength" | "Defense" | "Dexterity" | "Endurance" | "Stamina" | "Mana" | "Intelligence" | "PhysicalResistance" | "FireResistance" | "IceResistance" | "LightningResistance" | "PoisonResistance" | "MagicResistance" | "MovementSpeed";

/** Transpiled from TRPG.Combat.ClientModels.AmountType */
export type AmountType = "Flat" | "Percent";

/** Transpiled from TRPG.Combat.ClientModels.ConditionType */
export type ConditionType = "Blinded" | "Bleeding" | "Burning" | "Disarmed" | "Frozen" | "Poisoned" | "Silenced" | "Snared" | "Stunned";

/** Transpiled from TRPG.Combat.ClientModels.CombatOutcome */
export type CombatOutcome = "Ongoing" | "Victory" | "Defeat" | "Fled";

/** Transpiled from TRPG.Combat.ClientModels.CombatantState */
export type CombatantState = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    name: string;
    /** Transpiled from int */
    level: number;
    /** Transpiled from bool */
    isPlayer: boolean;
    /** Transpiled from bool */
    isAlive: boolean;
    /** Transpiled from int */
    currentHp: number;
    /** Transpiled from int */
    maximumHp: number;
    /** Transpiled from int */
    currentAp: number;
    /** Transpiled from int */
    maximumAp: number;
    /** Transpiled from int */
    currentMp: number;
    /** Transpiled from int */
    maximumMp: number;
    /** Transpiled from TRPG.Combat.ClientModels.ActiveConditions */
    activeConditions: ActiveConditions;
    /** Transpiled from System.Collections.Generic.IReadOnlyCollection<TRPG.Combat.ClientModels.ActiveDot> */
    activeDots: ActiveDot[];
    /** Transpiled from System.Collections.Generic.IReadOnlyCollection<TRPG.Combat.ClientModels.ActiveHot> */
    activeHots: ActiveHot[];
    /** Transpiled from System.Collections.Generic.IReadOnlyCollection<TRPG.Combat.ClientModels.ActiveBuff> */
    activeBuffs: ActiveBuff[];
}

/** Transpiled from TRPG.Combat.ClientModels.ActiveDot */
export type ActiveDot = {
    /** Transpiled from string */
    abilityName: string;
    /** Transpiled from int */
    amount: number;
    /** Transpiled from TRPG.Combat.ClientModels.DamageType */
    damageType: DamageType;
    /** Transpiled from int */
    remainingTurns: number;
}

/** Transpiled from TRPG.Combat.ClientModels.ActiveHot */
export type ActiveHot = {
    /** Transpiled from string */
    abilityName: string;
    /** Transpiled from int */
    amount: number;
    /** Transpiled from int */
    remainingTurns: number;
}

/** Transpiled from TRPG.Combat.ClientModels.ActiveBuff */
export type ActiveBuff = {
    /** Transpiled from string */
    abilityName: string;
    /** Transpiled from TRPG.Combat.ClientModels.AttributeName */
    attribute: AttributeName;
    /** Transpiled from float */
    amount: number;
    /** Transpiled from TRPG.Combat.ClientModels.AmountType */
    amountType: AmountType;
    /** Transpiled from int */
    remainingTurns: number;
}

/** Transpiled from TRPG.Combat.ClientModels.CombatRegeneration */
export type CombatRegeneration = {
    /** Transpiled from System.Guid */
    combatantId: string;
    /** Transpiled from int */
    previousAp: number;
    /** Transpiled from int */
    currentAp: number;
    /** Transpiled from int */
    maximumAp: number;
    /** Transpiled from int */
    previousMp: number;
    /** Transpiled from int */
    currentMp: number;
    /** Transpiled from int */
    maximumMp: number;
}

/** Transpiled from TRPG.Combat.ClientModels.CombatResourceState */
export type CombatResourceState = {
    /** Transpiled from System.Guid */
    combatantId: string;
    /** Transpiled from int */
    currentAp: number;
    /** Transpiled from int */
    maximumAp: number;
    /** Transpiled from int */
    currentMp: number;
    /** Transpiled from int */
    maximumMp: number;
}

/** Transpiled from TRPG.Combat.ClientModels.CombatUpdatePayload */
export type CombatUpdatePayload = {
    /** Transpiled from System.Collections.Generic.IReadOnlyCollection<TRPG.Combat.ClientModels.CombatantState> */
    combatants: CombatantState[];
    /** Transpiled from System.Collections.Generic.IReadOnlyList<TRPG.Combat.ClientModels.CombatActionResult> */
    actions: CombatActionResult[];
    /** Transpiled from System.Collections.Generic.IReadOnlyList<TRPG.Combat.ClientModels.CombatRegeneration> */
    regenerations: CombatRegeneration[];
    /** Transpiled from System.Collections.Generic.IReadOnlyList<TRPG.Combat.ClientModels.CombatResourceState> */
    resourceStates: CombatResourceState[];
    /** Transpiled from TRPG.Combat.ClientModels.CombatOutcome */
    outcome: CombatOutcome;
}

