/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import type { CreatureType } from './TRPG.GameSessions.Responses';

/** Transpiled from TRPG.Encounters.Responses.EncounterResolutionOutcome */
export type EncounterResolutionOutcome = "Evaded" | "EvadeFailed" | "Retreated" | "RetreatFailed" | "Attacked";

/** Transpiled from TRPG.Encounters.Responses.EncounterResolutionFact */
export type EncounterResolutionFact = {
    /** Transpiled from System.Guid */
    encounterId: string;
    /** Transpiled from TRPG.Encounters.Responses.EncounterResolutionOutcome */
    outcome: EncounterResolutionOutcome;
    /** Transpiled from string */
    factionName: string;
    /** Transpiled from string */
    locationName: string;
    /** Transpiled from System.Collections.Generic.IReadOnlyCollection<string> */
    memberNames: string[];
}

/** Transpiled from TRPG.Encounters.Responses.HostileEncounterMemberState */
export type HostileEncounterMemberState = {
    /** Transpiled from string */
    name: string;
    /** Transpiled from TRPG.GameSessions.Responses.CreatureType */
    creatureType: CreatureType;
    /** Transpiled from int */
    level: number;
}

/** Transpiled from TRPG.Encounters.Responses.HostileEncounterState */
export type HostileEncounterState = {
    /** Transpiled from System.Guid */
    encounterId: string;
    /** Transpiled from string */
    factionName: string;
    /** Transpiled from string */
    locationName: string;
    /** Transpiled from System.Collections.Generic.IReadOnlyCollection<TRPG.Encounters.Responses.HostileEncounterMemberState> */
    members: HostileEncounterMemberState[];
    /** Transpiled from System.Collections.Generic.IReadOnlyCollection<string> */
    allowedActions: string[];
}

