/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import type { Skill } from './TRPG.Abilities.Responses';

/** Transpiled from TRPG.Creatures.ClientModels.CharacterLevelUp */
export type CharacterLevelUp = {
    /** Transpiled from int */
    level: number;
}

/** Transpiled from TRPG.Creatures.ClientModels.SkillLevelUp */
export type SkillLevelUp = {
    /** Transpiled from TRPG.Abilities.Responses.Skill */
    skill: Skill;
    /** Transpiled from int */
    level: number;
    /** Transpiled from int */
    characterExperienceCurrent: number;
    /** Transpiled from int */
    characterExperienceToNextLevel: number;
}

