/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from TRPG.GameSessions.Responses.CreatureType */
export type CreatureType = "Human" | "Elf" | "Dwarf" | "Orc" | "Halfling" | "Gnome" | "Undead" | "Demon" | "Beast" | "Construct" | "Elemental" | "Goblin" | "Wraith" | "Giant" | "Dragon";

/** Transpiled from TRPG.GameSessions.Responses.Gender */
export type Gender = "Male" | "Female";

/** Transpiled from TRPG.GameSessions.Responses.Profession */
export type Profession = "Knight" | "Rogue" | "Ranger" | "Mage" | "Cleric" | "Mercenary" | "Alchemist" | "Blacksmith" | "Scholar" | "Merchant" | "Politician" | "StableMaster" | "Bartender" | "Guard" | "Baker" | "Innkeeper" | "Tailor" | "Carpenter" | "Jeweler" | "Homemaker" | "Unemployed";

/** Transpiled from TRPG.GameSessions.Responses.CreatureState */
export type CreatureState = "Idle" | "Sleeping" | "Busy" | "Studying" | "Praying" | "Training" | "Sitting" | "Alerted" | "Dead";

/** Transpiled from TRPG.GameSessions.Responses.DistrictType */
export type DistrictType = "Residential" | "Scientific" | "CityCenter" | "CityEntrance" | "Governmental" | "HolySite" | "Encampment";

/** Transpiled from TRPG.GameSessions.Responses.BuildingType */
export type BuildingType = "ArcaneShop" | "Apothecary" | "Bakery" | "Barracks" | "Blacksmith" | "Carpenter" | "Castle" | "Cave" | "Crypt" | "GeneralGoods" | "GuildHall" | "House" | "Inn" | "Jail" | "Jeweler" | "Library" | "Mine" | "Ruins" | "Stable" | "Tailor" | "Tavern" | "Temple" | "Tower";

/** Transpiled from TRPG.GameSessions.Responses.SceneSnapshot */
export type SceneSnapshot = {
    /** Transpiled from System.Guid */
    worldId: string;
    /** Transpiled from string */
    stateName: string;
    /** Transpiled from string? */
    cityName?: string;
    /** Transpiled from string? */
    districtName?: string;
    /** Transpiled from string? */
    buildingName?: string;
    /** Transpiled from string? */
    roomName?: string;
    /** Transpiled from int */
    year: number;
    /** Transpiled from string */
    monthName: string;
    /** Transpiled from int */
    day: number;
    /** Transpiled from string */
    weekdayName: string;
    /** Transpiled from int */
    hour: number;
    /** Transpiled from TRPG.GameSessions.Responses.CreatureStatusSnapshot */
    playerStatus: CreatureStatusSnapshot;
    /** Transpiled from System.Collections.Generic.IReadOnlyCollection<TRPG.GameSessions.Responses.CreatureStatusSnapshot> */
    nearbyCreatures: CreatureStatusSnapshot[];
    /** Transpiled from System.Collections.Generic.IReadOnlyCollection<TRPG.GameSessions.Responses.NearbyBuildingSnapshot> */
    nearbyBuildings: NearbyBuildingSnapshot[];
    /** Transpiled from System.Collections.Generic.IReadOnlyCollection<TRPG.GameSessions.Responses.NearbyPropSnapshot> */
    nearbyProps: NearbyPropSnapshot[];
    /** Transpiled from System.Collections.Generic.IReadOnlyCollection<TRPG.GameSessions.Responses.NearbyExitSnapshot> */
    exits: NearbyExitSnapshot[];
}

/** Transpiled from TRPG.GameSessions.Responses.CreatureStatusSnapshot */
export type CreatureStatusSnapshot = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    name: string;
    /** Transpiled from TRPG.GameSessions.Responses.CreatureType */
    creatureType: CreatureType;
    /** Transpiled from TRPG.GameSessions.Responses.Gender */
    gender: Gender;
    /** Transpiled from TRPG.GameSessions.Responses.Profession */
    profession?: Profession;
    /** Transpiled from int */
    level: number;
    /** Transpiled from int */
    age: number;
    /** Transpiled from TRPG.GameSessions.Responses.CreatureState */
    state?: CreatureState;
    /** Transpiled from int */
    gold: number;
    /** Transpiled from int */
    currentHp: number;
    /** Transpiled from int */
    maximumHp: number;
    /** Transpiled from int */
    currentAp: number;
    /** Transpiled from int */
    maximumAp: number;
    /** Transpiled from int */
    currentMp: number;
    /** Transpiled from int */
    maximumMp: number;
    /** Transpiled from int */
    experienceCurrent: number;
    /** Transpiled from int */
    experienceToNextLevel: number;
    /** Transpiled from System.Collections.Generic.IReadOnlyCollection<string>? */
    factionNames?: string[];
    /** Transpiled from int */
    reputation?: number;
    /** Transpiled from int */
    strength: number;
    /** Transpiled from int */
    dexterity: number;
    /** Transpiled from int */
    intelligence: number;
    /** Transpiled from int */
    endurance: number;
    /** Transpiled from int */
    stamina: number;
    /** Transpiled from int */
    mana: number;
    /** Transpiled from int */
    defense: number;
    /** Transpiled from float */
    movementSpeed: number;
    /** Transpiled from float */
    physicalResistance: number;
    /** Transpiled from float */
    fireResistance: number;
    /** Transpiled from float */
    iceResistance: number;
    /** Transpiled from float */
    lightningResistance: number;
    /** Transpiled from float */
    poisonResistance: number;
    /** Transpiled from float */
    magicResistance: number;
    /** Transpiled from System.Guid */
    tradeWorkstationId?: string;
    /** Transpiled from TRPG.GameSessions.Responses.QuestMarker */
    questMarker?: QuestMarker;
}

/** Transpiled from TRPG.GameSessions.Responses.QuestMarker */
export type QuestMarker = "Available" | "ReadyToTurnIn";

/** Transpiled from TRPG.GameSessions.Responses.NearbyBuildingSnapshot */
export type NearbyBuildingSnapshot = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    name: string;
    /** Transpiled from TRPG.GameSessions.Responses.BuildingType */
    type: BuildingType;
    /** Transpiled from string */
    typeDescription: string;
}

/** Transpiled from TRPG.GameSessions.Responses.NearbyPropSnapshot */
export type NearbyPropSnapshot = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    name: string;
    /** Transpiled from string */
    type: string;
}

/** Transpiled from TRPG.GameSessions.Responses.NearbyExitDestination */
export type NearbyExitDestination = {
    /** Transpiled from string */
    name: string;
}

/** Transpiled from TRPG.GameSessions.Responses.DistrictExitDestination */
export type DistrictExitDestination = {
    /** Transpiled from TRPG.GameSessions.Responses.DistrictType */
    districtType: DistrictType;
} & NearbyExitDestination;

/** Transpiled from TRPG.GameSessions.Responses.BuildingExitDestination */
export type BuildingExitDestination = {
    /** Transpiled from TRPG.GameSessions.Responses.BuildingType */
    buildingType: BuildingType;
} & NearbyExitDestination;

/** Transpiled from TRPG.GameSessions.Responses.RoomExitDestination */
export type RoomExitDestination = {
    /** Transpiled from TRPG.GameSessions.Responses.BuildingType */
    buildingType: BuildingType;
} & NearbyExitDestination;

/** Transpiled from TRPG.GameSessions.Responses.WildernessExitDestination */
export type WildernessExitDestination = {
} & NearbyExitDestination;

/** Transpiled from TRPG.GameSessions.Responses.NearbyExitSnapshot */
export type NearbyExitSnapshot = {
    /** Transpiled from string */
    description: string;
    /** Transpiled from TRPG.GameSessions.Responses.NearbyExitDestination */
    destination: NearbyExitDestination;
}

