/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from TRPG.Abilities.Responses.Skill */
export type Skill = "Melee" | "Unarmed" | "Sneak" | "Destruction" | "Illusion" | "Archery" | "Restoration" | "Alteration" | "General" | "Blocking";

/** Transpiled from TRPG.Abilities.Responses.AbilityCategory */
export type AbilityCategory = "Offensive" | "Support";

/** Transpiled from TRPG.Abilities.Responses.AbilitySummary */
export type AbilitySummary = {
    /** Transpiled from string */
    name: string;
    /** Transpiled from TRPG.Abilities.Responses.Skill */
    skill: Skill;
    /** Transpiled from string */
    description: string;
    /** Transpiled from int */
    apCost: number;
    /** Transpiled from int */
    mpCost: number;
    /** Transpiled from int */
    cooldown: number;
    /** Transpiled from TRPG.Abilities.Responses.AbilityCategory */
    category: AbilityCategory;
    /** Transpiled from int */
    requiredSkillLevel: number;
    /** Transpiled from System.Collections.Generic.IReadOnlyCollection<string> */
    prerequisites: string[];
}

