using ContractPropModel = TRPG.GameSessions.Responses.PropModel;
using DataPropModel = TRPG.Domain.Models.PropModel;

namespace TRPG.GameSessions.Mappers;

internal static class PropModelMapper
{
    public static ContractPropModel ToResponse(this DataPropModel model) =>
        model switch
        {
            DataPropModel.Bed => ContractPropModel.Bed,
            DataPropModel.Cell => ContractPropModel.Cell,
            DataPropModel.Sign => ContractPropModel.Sign,
            DataPropModel.ContainerBasic => ContractPropModel.ContainerBasic,
            DataPropModel.ContainerBarrel => ContractPropModel.ContainerBarrel,
            DataPropModel.ContainerChest => ContractPropModel.ContainerChest,
            DataPropModel.ContainerCrate => ContractPropModel.ContainerCrate,
            DataPropModel.ContainerFootlocker => ContractPropModel.ContainerFootlocker,
            DataPropModel.ContainerStrongbox => ContractPropModel.ContainerStrongbox,
            DataPropModel.ContainerWeaponRack => ContractPropModel.ContainerWeaponRack,
            DataPropModel.FurnitureTable => ContractPropModel.FurnitureTable,
            DataPropModel.FurnitureWorkTable => ContractPropModel.FurnitureWorkTable,
            DataPropModel.FurnitureFireplace => ContractPropModel.FurnitureFireplace,
            DataPropModel.FurnitureStall => ContractPropModel.FurnitureStall,
            DataPropModel.FurnitureNoticeBoard => ContractPropModel.FurnitureNoticeBoard,
            DataPropModel.FurnitureDisplayShelf => ContractPropModel.FurnitureDisplayShelf,
            DataPropModel.FurnitureTrainingDummy => ContractPropModel.FurnitureTrainingDummy,
            DataPropModel.FurnitureRug => ContractPropModel.FurnitureRug,
            DataPropModel.FurnitureCauldron => ContractPropModel.FurnitureCauldron,
            DataPropModel.FurnitureHerbRack => ContractPropModel.FurnitureHerbRack,
            DataPropModel.FurnitureLectern => ContractPropModel.FurnitureLectern,
            DataPropModel.FurnitureStaffRack => ContractPropModel.FurnitureStaffRack,
            DataPropModel.FurnitureMannequin => ContractPropModel.FurnitureMannequin,
            DataPropModel.FurnitureClothShelf => ContractPropModel.FurnitureClothShelf,
            DataPropModel.FurnitureDisplayCase => ContractPropModel.FurnitureDisplayCase,
            DataPropModel.FurnitureFlourSacks => ContractPropModel.FurnitureFlourSacks,
            DataPropModel.FurnitureBreadRack => ContractPropModel.FurnitureBreadRack,
            DataPropModel.FurnitureLumberStack => ContractPropModel.FurnitureLumberStack,
            DataPropModel.FurnitureTimberRack => ContractPropModel.FurnitureTimberRack,
            DataPropModel.FurnitureBookcase => ContractPropModel.FurnitureBookcase,
            DataPropModel.FurnitureChair => ContractPropModel.FurnitureChair,
            DataPropModel.FurnitureBench => ContractPropModel.FurnitureBench,
            DataPropModel.FurniturePew => ContractPropModel.FurniturePew,
            DataPropModel.FurnitureFountain => ContractPropModel.FurnitureFountain,
            DataPropModel.FurnitureWell => ContractPropModel.FurnitureWell,
            DataPropModel.FurnitureFirePit => ContractPropModel.FurnitureFirePit,
            DataPropModel.FurnitureStatue => ContractPropModel.FurnitureStatue,
            DataPropModel.FurnitureMonument => ContractPropModel.FurnitureMonument,
            DataPropModel.FurnitureShrine => ContractPropModel.FurnitureShrine,
            DataPropModel.FurnitureWaystone => ContractPropModel.FurnitureWaystone,
            DataPropModel.SeatBasic => ContractPropModel.SeatBasic,
            DataPropModel.SeatChair => ContractPropModel.SeatChair,
            DataPropModel.SeatPew => ContractPropModel.SeatPew,
            DataPropModel.SeatThrone => ContractPropModel.SeatThrone,
            DataPropModel.SeatBench => ContractPropModel.SeatBench,
            DataPropModel.SeatStoneBench => ContractPropModel.SeatStoneBench,
            DataPropModel.SeatLowWall => ContractPropModel.SeatLowWall,
            DataPropModel.TrapMechanical => ContractPropModel.TrapMechanical,
            DataPropModel.TrapCollapse => ContractPropModel.TrapCollapse,
            DataPropModel.TrapSlope => ContractPropModel.TrapSlope,
            DataPropModel.TrapWater => ContractPropModel.TrapWater,
            DataPropModel.TriggerBasic => ContractPropModel.TriggerBasic,
            DataPropModel.TriggerLever => ContractPropModel.TriggerLever,
            DataPropModel.WorkstationAlchemy => ContractPropModel.WorkstationAlchemy,
            DataPropModel.WorkstationArmorsmithing => ContractPropModel.WorkstationArmorsmithing,
            DataPropModel.WorkstationCarpentry => ContractPropModel.WorkstationCarpentry,
            DataPropModel.WorkstationCooking => ContractPropModel.WorkstationCooking,
            DataPropModel.WorkstationEnchanting => ContractPropModel.WorkstationEnchanting,
            DataPropModel.WorkstationJewelcrafting => ContractPropModel.WorkstationJewelcrafting,
            DataPropModel.WorkstationPrayer => ContractPropModel.WorkstationPrayer,
            DataPropModel.WorkstationReading => ContractPropModel.WorkstationReading,
            DataPropModel.WorkstationTailoring => ContractPropModel.WorkstationTailoring,
            DataPropModel.WorkstationTrade => ContractPropModel.WorkstationTrade,
            DataPropModel.WorkstationWeaponsmithing => ContractPropModel.WorkstationWeaponsmithing,
        };
}
