// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { advanceSessionTime, allocateCreatureAttributePoints, createSession, createWorld, dropWorld, endSession, equipCreatureItem, getAbilitiesBySkill, getCreatureAbilities, getCreatureAttributePoints, getCreatureAttributes, getCreatureBasicAttackDamage, getCreatureConsumables, getCreatureGenerationOptions, getCreatureInventory, getCreatureLevel, getCreatureSkills, getCreatureStats, getJob, getNearbyCorpses, getPlayerFight, getPlayerFightAbilities, getSessionNamedEntity, getSessionScene, listSessionNamedEntities, listWorlds, type Options, previewCreatureBasicAttackDamage, previewCreatureEquipment, sendAdminChat, transferInventory, unequipCreatureItem } from '../sdk.gen';
import type { AdvanceSessionTimeData, AdvanceSessionTimeResponse, AllocateCreatureAttributePointsData, AllocateCreatureAttributePointsResponse, CreateSessionData, CreateSessionResponse2, CreateWorldData, CreateWorldResponse, DropWorldData, DropWorldResponse, EndSessionData, EndSessionResponse, EquipCreatureItemData, EquipCreatureItemResponse, GetAbilitiesBySkillData, GetAbilitiesBySkillResponse, GetCreatureAbilitiesData, GetCreatureAbilitiesResponse, GetCreatureAttributePointsData, GetCreatureAttributePointsResponse, GetCreatureAttributesData, GetCreatureAttributesResponse, GetCreatureBasicAttackDamageData, GetCreatureBasicAttackDamageResponse, GetCreatureConsumablesData, GetCreatureConsumablesResponse, GetCreatureGenerationOptionsData, GetCreatureGenerationOptionsResponse, GetCreatureInventoryData, GetCreatureInventoryResponse, GetCreatureLevelData, GetCreatureLevelResponse, GetCreatureSkillsData, GetCreatureSkillsResponse, GetCreatureStatsData, GetCreatureStatsResponse, GetJobData, GetJobResponse, GetNearbyCorpsesData, GetNearbyCorpsesResponse, GetPlayerFightAbilitiesData, GetPlayerFightAbilitiesResponse, GetPlayerFightData, GetPlayerFightResponse, GetSessionNamedEntityData, GetSessionNamedEntityResponse, GetSessionSceneData, GetSessionSceneResponse, ListSessionNamedEntitiesData, ListSessionNamedEntitiesResponse, ListWorldsData, ListWorldsResponse, PreviewCreatureBasicAttackDamageData, PreviewCreatureBasicAttackDamageResponse, PreviewCreatureEquipmentData, PreviewCreatureEquipmentResponse, SendAdminChatData, SendAdminChatResponse, TransferInventoryData, TransferInventoryResponse, UnequipCreatureItemData, UnequipCreatureItemResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listWorldsQueryKey = (options?: Options<ListWorldsData>) => createQueryKey('listWorlds', options);

export const listWorldsOptions = (options?: Options<ListWorldsData>) => queryOptions<ListWorldsResponse, DefaultError, ListWorldsResponse, ReturnType<typeof listWorldsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listWorlds({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listWorldsQueryKey(options)
});

export const createWorldMutation = (options?: Partial<Options<CreateWorldData>>): UseMutationOptions<CreateWorldResponse, DefaultError, Options<CreateWorldData>> => {
    const mutationOptions: UseMutationOptions<CreateWorldResponse, DefaultError, Options<CreateWorldData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createWorld({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const dropWorldMutation = (options?: Partial<Options<DropWorldData>>): UseMutationOptions<DropWorldResponse, DefaultError, Options<DropWorldData>> => {
    const mutationOptions: UseMutationOptions<DropWorldResponse, DefaultError, Options<DropWorldData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await dropWorld({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAbilitiesBySkillQueryKey = (options: Options<GetAbilitiesBySkillData>) => createQueryKey('getAbilitiesBySkill', options);

export const getAbilitiesBySkillOptions = (options: Options<GetAbilitiesBySkillData>) => queryOptions<GetAbilitiesBySkillResponse, DefaultError, GetAbilitiesBySkillResponse, ReturnType<typeof getAbilitiesBySkillQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAbilitiesBySkill({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAbilitiesBySkillQueryKey(options)
});

export const getCreatureAbilitiesQueryKey = (options: Options<GetCreatureAbilitiesData>) => createQueryKey('getCreatureAbilities', options);

export const getCreatureAbilitiesOptions = (options: Options<GetCreatureAbilitiesData>) => queryOptions<GetCreatureAbilitiesResponse, DefaultError, GetCreatureAbilitiesResponse, ReturnType<typeof getCreatureAbilitiesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCreatureAbilities({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCreatureAbilitiesQueryKey(options)
});

export const getCreatureInventoryQueryKey = (options: Options<GetCreatureInventoryData>) => createQueryKey('getCreatureInventory', options);

export const getCreatureInventoryOptions = (options: Options<GetCreatureInventoryData>) => queryOptions<GetCreatureInventoryResponse, DefaultError, GetCreatureInventoryResponse, ReturnType<typeof getCreatureInventoryQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCreatureInventory({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCreatureInventoryQueryKey(options)
});

export const getCreatureConsumablesQueryKey = (options: Options<GetCreatureConsumablesData>) => createQueryKey('getCreatureConsumables', options);

export const getCreatureConsumablesOptions = (options: Options<GetCreatureConsumablesData>) => queryOptions<GetCreatureConsumablesResponse, DefaultError, GetCreatureConsumablesResponse, ReturnType<typeof getCreatureConsumablesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCreatureConsumables({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCreatureConsumablesQueryKey(options)
});

export const getCreatureAttributePointsQueryKey = (options: Options<GetCreatureAttributePointsData>) => createQueryKey('getCreatureAttributePoints', options);

export const getCreatureAttributePointsOptions = (options: Options<GetCreatureAttributePointsData>) => queryOptions<GetCreatureAttributePointsResponse, DefaultError, GetCreatureAttributePointsResponse, ReturnType<typeof getCreatureAttributePointsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCreatureAttributePoints({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCreatureAttributePointsQueryKey(options)
});

export const allocateCreatureAttributePointsMutation = (options?: Partial<Options<AllocateCreatureAttributePointsData>>): UseMutationOptions<AllocateCreatureAttributePointsResponse, DefaultError, Options<AllocateCreatureAttributePointsData>> => {
    const mutationOptions: UseMutationOptions<AllocateCreatureAttributePointsResponse, DefaultError, Options<AllocateCreatureAttributePointsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await allocateCreatureAttributePoints({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCreatureAttributesQueryKey = (options: Options<GetCreatureAttributesData>) => createQueryKey('getCreatureAttributes', options);

export const getCreatureAttributesOptions = (options: Options<GetCreatureAttributesData>) => queryOptions<GetCreatureAttributesResponse, DefaultError, GetCreatureAttributesResponse, ReturnType<typeof getCreatureAttributesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCreatureAttributes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCreatureAttributesQueryKey(options)
});

export const getCreatureStatsQueryKey = (options: Options<GetCreatureStatsData>) => createQueryKey('getCreatureStats', options);

export const getCreatureStatsOptions = (options: Options<GetCreatureStatsData>) => queryOptions<GetCreatureStatsResponse, DefaultError, GetCreatureStatsResponse, ReturnType<typeof getCreatureStatsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCreatureStats({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCreatureStatsQueryKey(options)
});

export const getCreatureBasicAttackDamageQueryKey = (options: Options<GetCreatureBasicAttackDamageData>) => createQueryKey('getCreatureBasicAttackDamage', options);

export const getCreatureBasicAttackDamageOptions = (options: Options<GetCreatureBasicAttackDamageData>) => queryOptions<GetCreatureBasicAttackDamageResponse, DefaultError, GetCreatureBasicAttackDamageResponse, ReturnType<typeof getCreatureBasicAttackDamageQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCreatureBasicAttackDamage({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCreatureBasicAttackDamageQueryKey(options)
});

export const getCreatureSkillsQueryKey = (options: Options<GetCreatureSkillsData>) => createQueryKey('getCreatureSkills', options);

export const getCreatureSkillsOptions = (options: Options<GetCreatureSkillsData>) => queryOptions<GetCreatureSkillsResponse, DefaultError, GetCreatureSkillsResponse, ReturnType<typeof getCreatureSkillsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCreatureSkills({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCreatureSkillsQueryKey(options)
});

export const getCreatureLevelQueryKey = (options: Options<GetCreatureLevelData>) => createQueryKey('getCreatureLevel', options);

export const getCreatureLevelOptions = (options: Options<GetCreatureLevelData>) => queryOptions<GetCreatureLevelResponse, DefaultError, GetCreatureLevelResponse, ReturnType<typeof getCreatureLevelQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCreatureLevel({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCreatureLevelQueryKey(options)
});

export const equipCreatureItemMutation = (options?: Partial<Options<EquipCreatureItemData>>): UseMutationOptions<EquipCreatureItemResponse, DefaultError, Options<EquipCreatureItemData>> => {
    const mutationOptions: UseMutationOptions<EquipCreatureItemResponse, DefaultError, Options<EquipCreatureItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await equipCreatureItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const unequipCreatureItemMutation = (options?: Partial<Options<UnequipCreatureItemData>>): UseMutationOptions<UnequipCreatureItemResponse, DefaultError, Options<UnequipCreatureItemData>> => {
    const mutationOptions: UseMutationOptions<UnequipCreatureItemResponse, DefaultError, Options<UnequipCreatureItemData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await unequipCreatureItem({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const previewCreatureEquipmentQueryKey = (options: Options<PreviewCreatureEquipmentData>) => createQueryKey('previewCreatureEquipment', options);

export const previewCreatureEquipmentOptions = (options: Options<PreviewCreatureEquipmentData>) => queryOptions<PreviewCreatureEquipmentResponse, DefaultError, PreviewCreatureEquipmentResponse, ReturnType<typeof previewCreatureEquipmentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await previewCreatureEquipment({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: previewCreatureEquipmentQueryKey(options)
});

export const previewCreatureBasicAttackDamageQueryKey = (options: Options<PreviewCreatureBasicAttackDamageData>) => createQueryKey('previewCreatureBasicAttackDamage', options);

export const previewCreatureBasicAttackDamageOptions = (options: Options<PreviewCreatureBasicAttackDamageData>) => queryOptions<PreviewCreatureBasicAttackDamageResponse, DefaultError, PreviewCreatureBasicAttackDamageResponse, ReturnType<typeof previewCreatureBasicAttackDamageQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await previewCreatureBasicAttackDamage({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: previewCreatureBasicAttackDamageQueryKey(options)
});

export const getNearbyCorpsesQueryKey = (options: Options<GetNearbyCorpsesData>) => createQueryKey('getNearbyCorpses', options);

export const getNearbyCorpsesOptions = (options: Options<GetNearbyCorpsesData>) => queryOptions<GetNearbyCorpsesResponse, DefaultError, GetNearbyCorpsesResponse, ReturnType<typeof getNearbyCorpsesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getNearbyCorpses({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getNearbyCorpsesQueryKey(options)
});

export const getPlayerFightQueryKey = (options: Options<GetPlayerFightData>) => createQueryKey('getPlayerFight', options);

export const getPlayerFightOptions = (options: Options<GetPlayerFightData>) => queryOptions<GetPlayerFightResponse, DefaultError, GetPlayerFightResponse, ReturnType<typeof getPlayerFightQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPlayerFight({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPlayerFightQueryKey(options)
});

export const getPlayerFightAbilitiesQueryKey = (options: Options<GetPlayerFightAbilitiesData>) => createQueryKey('getPlayerFightAbilities', options);

export const getPlayerFightAbilitiesOptions = (options: Options<GetPlayerFightAbilitiesData>) => queryOptions<GetPlayerFightAbilitiesResponse, DefaultError, GetPlayerFightAbilitiesResponse, ReturnType<typeof getPlayerFightAbilitiesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getPlayerFightAbilities({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getPlayerFightAbilitiesQueryKey(options)
});

export const getCreatureGenerationOptionsQueryKey = (options?: Options<GetCreatureGenerationOptionsData>) => createQueryKey('getCreatureGenerationOptions', options);

export const getCreatureGenerationOptionsOptions = (options?: Options<GetCreatureGenerationOptionsData>) => queryOptions<GetCreatureGenerationOptionsResponse, DefaultError, GetCreatureGenerationOptionsResponse, ReturnType<typeof getCreatureGenerationOptionsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCreatureGenerationOptions({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCreatureGenerationOptionsQueryKey(options)
});

export const createSessionMutation = (options?: Partial<Options<CreateSessionData>>): UseMutationOptions<CreateSessionResponse2, DefaultError, Options<CreateSessionData>> => {
    const mutationOptions: UseMutationOptions<CreateSessionResponse2, DefaultError, Options<CreateSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSessionSceneQueryKey = (options: Options<GetSessionSceneData>) => createQueryKey('getSessionScene', options);

export const getSessionSceneOptions = (options: Options<GetSessionSceneData>) => queryOptions<GetSessionSceneResponse, DefaultError, GetSessionSceneResponse, ReturnType<typeof getSessionSceneQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSessionScene({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSessionSceneQueryKey(options)
});

export const listSessionNamedEntitiesQueryKey = (options: Options<ListSessionNamedEntitiesData>) => createQueryKey('listSessionNamedEntities', options);

export const listSessionNamedEntitiesOptions = (options: Options<ListSessionNamedEntitiesData>) => queryOptions<ListSessionNamedEntitiesResponse, DefaultError, ListSessionNamedEntitiesResponse, ReturnType<typeof listSessionNamedEntitiesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listSessionNamedEntities({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listSessionNamedEntitiesQueryKey(options)
});

export const getSessionNamedEntityQueryKey = (options: Options<GetSessionNamedEntityData>) => createQueryKey('getSessionNamedEntity', options);

export const getSessionNamedEntityOptions = (options: Options<GetSessionNamedEntityData>) => queryOptions<GetSessionNamedEntityResponse, DefaultError, GetSessionNamedEntityResponse, ReturnType<typeof getSessionNamedEntityQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSessionNamedEntity({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSessionNamedEntityQueryKey(options)
});

export const getJobQueryKey = (options: Options<GetJobData>) => createQueryKey('getJob', options);

export const getJobOptions = (options: Options<GetJobData>) => queryOptions<GetJobResponse, DefaultError, GetJobResponse, ReturnType<typeof getJobQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getJob({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getJobQueryKey(options)
});

export const sendAdminChatMutation = (options?: Partial<Options<SendAdminChatData>>): UseMutationOptions<SendAdminChatResponse, DefaultError, Options<SendAdminChatData>> => {
    const mutationOptions: UseMutationOptions<SendAdminChatResponse, DefaultError, Options<SendAdminChatData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await sendAdminChat({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const advanceSessionTimeMutation = (options?: Partial<Options<AdvanceSessionTimeData>>): UseMutationOptions<AdvanceSessionTimeResponse, DefaultError, Options<AdvanceSessionTimeData>> => {
    const mutationOptions: UseMutationOptions<AdvanceSessionTimeResponse, DefaultError, Options<AdvanceSessionTimeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await advanceSessionTime({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const endSessionMutation = (options?: Partial<Options<EndSessionData>>): UseMutationOptions<EndSessionResponse, DefaultError, Options<EndSessionData>> => {
    const mutationOptions: UseMutationOptions<EndSessionResponse, DefaultError, Options<EndSessionData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await endSession({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const transferInventoryMutation = (options?: Partial<Options<TransferInventoryData>>): UseMutationOptions<TransferInventoryResponse, DefaultError, Options<TransferInventoryData>> => {
    const mutationOptions: UseMutationOptions<TransferInventoryResponse, DefaultError, Options<TransferInventoryData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await transferInventory({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
