import type { IconType } from 'react-icons';
import {
  GiAchillesHeel,
  GiAngelOutfit,
  GiAngelWings,
  GiArrowCluster,
  GiArrowFlights,
  GiArrowScope,
  GiAxeSwing,
  GiBackstab,
  GiBarbedWire,
  GiBarrier,
  GiBleedingWound,
  GiBloodySword,
  GiBowArrow,
  GiBrightExplosion,
  GiBurningMeteor,
  GiChainLightning,
  GiCloakDagger,
  GiCrossedSwords,
  GiCrosshair,
  GiCrystalShrine,
  GiDaggerRose,
  GiDart,
  GiDeathNote,
  GiDrum,
  GiEclipseFlare,
  GiEnrage,
  GiFire,
  GiFireball,
  GiFirePunch,
  GiFootTrip,
  GiFrozenOrb,
  GiGhost,
  GiGuillotine,
  GiHalfTornado,
  GiHammerBreak,
  GiHammerDrop,
  GiHealing,
  GiHealthPotion,
  GiHolySymbol,
  GiIceBolt,
  GiIceCube,
  GiIceSpear,
  GiLaurelCrown,
  GiLightningStorm,
  GiLockedFortress,
  GiMagicShield,
  GiMagicSwirl,
  GiMailedFist,
  GiNailedFoot,
  GiOrbital,
  GiPentarrowsTornado,
  GiPoisonGas,
  GiPuppet,
  GiQuiver,
  GiRaiseSkeleton,
  GiRaiseZombie,
  GiScreaming,
  GiShadowFollower,
  GiShield,
  GiShieldBash,
  GiShieldReflect,
  GiShiningSword,
  GiShinyPurse,
  GiShouting,
  GiSkullCrack,
  GiSnakeBite,
  GiSnowing,
  GiSoulVessel,
  GiSpellBook,
  GiSplitArrows,
  GiSprint,
  GiStoneWall,
  GiSunbeams,
  GiSunRadiations,
  GiSwordArray,
  GiSwordBreak,
  GiSwordClash,
  GiSwordHilt,
  GiSwordsEmblem,
  GiTatteredBanner,
  GiTerror,
  GiThirdEye,
  GiThroneKing,
  GiTornado,
  GiTornadoDiscs,
  GiTripwire,
  GiVolcano,
} from 'react-icons/gi';

import type { AbilitySummary, Skill } from '@/api/client';

export const ABILITY_ICON: Record<string, IconType> = {
  // Melee
  'Battle Stance': GiTatteredBanner,
  Slash: GiSwordHilt,
  Cleave: GiAxeSwing,
  Rally: GiDrum,
  Devastate: GiHammerDrop,
  Whirlwind: GiTornado,
  Sunder: GiHammerBreak,
  Execute: GiGuillotine,
  'War Cry': GiShouting,
  'Berserker Stance': GiEnrage,
  'Mortal Strike': GiSwordClash,
  Bladestorm: GiTornadoDiscs,
  'Skull Splitter': GiSkullCrack,
  'Hundred Blades': GiSwordArray,
  "Legend's Blow": GiLaurelCrown,
  'Eternal Whirlwind': GiHalfTornado,
  'Legion Might': GiThroneKing,

  // Blocking
  Block: GiShield,
  'Iron Will': GiStoneWall,
  'Shield Bash': GiShieldBash,
  Fortify: GiLockedFortress,
  Riposte: GiShieldReflect,

  // Sneak
  Stab: GiCloakDagger,
  Backstab: GiBackstab,
  Hamstring: GiAchillesHeel,
  Haste: GiSprint,
  Hemorrhage: GiBleedingWound,
  Disarm: GiSwordBreak,
  'Shadowstep Strike': GiShadowFollower,
  'Kidney Shot': GiCrosshair,
  Cripple: GiTripwire,
  Garrote: GiBarbedWire,
  'Marked for Death': GiDeathNote,
  Phantasm: GiGhost,
  'Death Blossom': GiSwordsEmblem,
  Assassinate: GiDaggerRose,
  'Hemorrhagic Frenzy': GiBloodySword,

  // Destruction
  'Frost Bolt': GiIceBolt,
  Fireball: GiFireball,
  'Chain Lightning': GiChainLightning,
  'Poison Cloud': GiPoisonGas,
  'Arcane Blast': GiBrightExplosion,
  Blizzard: GiSnowing,
  Inferno: GiVolcano,
  Thunderstorm: GiLightningStorm,
  'Ice Lance': GiIceSpear,
  Scorch: GiFirePunch,
  'Glacial Spike': GiIceCube,
  Meteor: GiBurningMeteor,
  'Absolute Zero': GiFrozenOrb,
  'Ball Lightning': GiOrbital,
  Armageddon: GiEclipseFlare,
  'Void Bolt': GiFrozenOrb,

  // Illusion
  Fear: GiScreaming,
  'Maddening Whispers': GiPuppet,
  Paralyze: GiThirdEye,
  'Overwhelming Terror': GiTerror,

  // Archery
  'Arrow Shot': GiBowArrow,
  'Piercing Shot': GiArrowFlights,
  Quickdraw: GiSprint,
  'Poison Arrow': GiDart,
  Volley: GiQuiver,
  'Crippling Arrow': GiFootTrip,
  Multishot: GiSplitArrows,
  'Concussive Shot': GiCrosshair,
  Barrage: GiArrowCluster,
  'Venom Strike': GiSnakeBite,
  'Rain of Arrows': GiArrowCluster,
  'Pinning Shot': GiNailedFoot,
  'Arrow Storm': GiPentarrowsTornado,
  'Death from Afar': GiArrowScope,

  // Restoration
  Mend: GiHealing,
  'Silencing Word': GiHolySymbol,
  Regenerate: GiHealing,
  Smite: GiSunRadiations,
  'Mass Heal': GiAngelWings,
  'Greater Mend': GiHealthPotion,
  'Turn Undead': GiRaiseZombie,
  'Radiant Burst': GiSunbeams,
  'Sacred Ground': GiCrystalShrine,
  'Resurrection Pulse': GiSoulVessel,
  'Destroy Undead': GiRaiseSkeleton,
  'Wrath of the Divine': GiHolySymbol,
  'Divine Intervention': GiAngelOutfit,

  // Alteration
  'Arcane Infusion': GiMagicSwirl,
  'Divine Shield': GiMagicShield,
  'Spell Ward': GiBarrier,
  'Mystic Focus': GiSpellBook,

  // General
  Strike: GiShiningSword,
};

export const SKILL_FALLBACK_ICON: Record<Skill, IconType> = {
  Melee: GiCrossedSwords,
  Unarmed: GiMailedFist,
  Sneak: GiCloakDagger,
  Pickpocketing: GiShinyPurse,
  Destruction: GiFire,
  Illusion: GiGhost,
  Archery: GiBowArrow,
  Restoration: GiHealing,
  Alteration: GiMagicSwirl,
  General: GiShiningSword,
  Blocking: GiShield,
  Lockpicking: GiLockedFortress,
};

export function getAbilityIcon(ability: AbilitySummary): IconType {
  return ABILITY_ICON[ability.name] ?? SKILL_FALLBACK_ICON[ability.skill];
}
