import {
  Axe,
  Biohazard,
  Bomb,
  BookOpen,
  BowArrow,
  Brain,
  CloudLightning,
  Cross,
  Crosshair,
  Crown,
  Droplet,
  Eye,
  EyeOff,
  Flame,
  Footprints,
  Ghost,
  Hammer,
  Hand,
  Heart,
  HeartPulse,
  Repeat,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldHalf,
  Skull,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  SunMedium,
  Sword,
  Swords,
  Target,
  Tornado,
  UserPlus,
  Users,
  Wind,
  Zap,
  type LucideIcon,
} from 'lucide-react';

import type { AbilitySummary, Skill } from '@/api/client';

export const ABILITY_ICON: Record<string, LucideIcon> = {
  // Melee
  'Battle Stance': Swords,
  Slash: Sword,
  Cleave: Axe,
  Rally: Users,
  Devastate: Droplet,
  Whirlwind: Wind,
  Sunder: Hammer,
  Execute: Skull,
  'War Cry': UserPlus,
  'Berserker Stance': Flame,
  'Mortal Strike': Sword,
  Bladestorm: Tornado,
  'Skull Splitter': Skull,
  'Hundred Blades': Swords,
  "Legend's Blow": Star,
  'Eternal Whirlwind': Tornado,
  'Legion Might': Crown,

  // Blocking
  Block: Shield,
  'Iron Will': ShieldCheck,
  'Shield Bash': ShieldAlert,
  Fortify: ShieldHalf,
  Riposte: Repeat,

  // Sneak
  Stab: Sword,
  Backstab: Skull,
  Hamstring: Footprints,
  Haste: Wind,
  Hemorrhage: Droplet,
  Disarm: Hammer,
  'Shadowstep Strike': EyeOff,
  'Kidney Shot': Target,
  Cripple: Footprints,
  Garrote: Skull,
  'Marked for Death': Crosshair,
  Phantasm: Ghost,
  'Death Blossom': Tornado,
  Assassinate: Skull,
  'Hemorrhagic Frenzy': Droplet,

  // Destruction
  'Frost Bolt': Snowflake,
  Fireball: Flame,
  'Chain Lightning': Zap,
  'Poison Cloud': Biohazard,
  'Arcane Blast': Sparkles,
  Blizzard: Snowflake,
  Inferno: Flame,
  Thunderstorm: CloudLightning,
  'Ice Lance': Snowflake,
  Scorch: Flame,
  'Glacial Spike': Snowflake,
  Meteor: Bomb,
  'Absolute Zero': Snowflake,
  'Ball Lightning': Zap,
  Armageddon: Flame,
  'Void Bolt': Zap,

  // Illusion
  Fear: Ghost,
  'Maddening Whispers': Brain,
  Paralyze: Eye,
  'Overwhelming Terror': Skull,

  // Archery
  'Arrow Shot': BowArrow,
  'Piercing Shot': Target,
  Quickdraw: Wind,
  'Poison Arrow': Biohazard,
  Volley: BowArrow,
  'Crippling Arrow': Footprints,
  Multishot: BowArrow,
  'Concussive Shot': Target,
  Barrage: BowArrow,
  'Venom Strike': Droplet,
  'Rain of Arrows': BowArrow,
  'Pinning Shot': Target,
  'Arrow Storm': Tornado,
  'Death from Afar': Skull,

  // Restoration
  Mend: Heart,
  'Silencing Word': Sun,
  Regenerate: HeartPulse,
  Smite: Sun,
  'Mass Heal': HeartPulse,
  'Greater Mend': Heart,
  'Turn Undead': Cross,
  'Radiant Burst': SunMedium,
  'Sacred Ground': Cross,
  'Resurrection Pulse': Sparkles,
  'Destroy Undead': Sun,
  'Wrath of the Divine': SunMedium,
  'Divine Intervention': Crown,

  // Alteration
  'Arcane Infusion': Sparkles,
  'Divine Shield': ShieldCheck,
  'Spell Ward': Shield,
  'Mystic Focus': BookOpen,

  // General
  Strike: Sword,
};

export const SKILL_FALLBACK_ICON: Record<Skill, LucideIcon> = {
  Melee: Sword,
  Unarmed: Hand,
  Sneak: Footprints,
  Pickpocketing: Hand,
  Destruction: Flame,
  Illusion: Ghost,
  Archery: BowArrow,
  Restoration: Heart,
  Alteration: Sparkles,
  General: Sword,
  Blocking: Shield,
};

export function getAbilityIcon(ability: AbilitySummary): LucideIcon {
  return ABILITY_ICON[ability.name] ?? SKILL_FALLBACK_ICON[ability.skill];
}
